[workspace]

[package]
name = "tensat"
version = "0.1.0"
authors = ["Remy Wang <remywang@uw.edu>"]
edition = "2021"

[lib]
crate-type = ["staticlib", "lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
cxxbridge-cmd = "1.0.122"
env_logger = { version =  "0.7", default_features = false }
pest = "2.0"
pest_derive = "2.0"
rand = "0.9"
clap = "2.33"
itertools = "0.9"
arrayvec = "0.5.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
argmin = "0.10.0"
argmin-observer-slog = "0.1.0"

[dependencies.egg]
git = "https://github.com/aryavohra/egg"
rev = "b30d14cff61bff97336323f6eb0978cc7769140d"

[package.metadata.cxx]
library = "c++"

[build-dependencies]
cxx-build = "1.0"
cxxbridge-cmd = "1.0.122"
