// RUN: enzymexlamlir-opt --pass-pipeline="builtin.module(lower-enzymexla-lapack{backend=cpu blas_int_width=64},enzyme-hlo-opt)" %s | FileCheck %s --check-prefix=CPU

// NOTE wide QR (A is m-by-n where m < n) is not yet supported, so we use a square QR (A is m-by-m) instead that models the extraction of the leftmost m columns of A

module {
  func.func @main(%arg0: tensor<32x64xf32>, %arg1: tensor<32xf32>, %arg2: tensor<32x64xf32>) -> tensor<32x64xf32> {
    %0 = "stablehlo.slice"(%arg0) {start_indices = array<i64: 0, 0>, limit_indices = array<i64: 32, 32>, strides = array<i64: 1, 1>} : (tensor<32x64xf32>) -> tensor<32x32xf32>
    %1 = enzymexla.lapack.ormqr %0, %arg1, %arg2 {side = #enzymexla.side<left>} : (tensor<32x32xf32>, tensor<32xf32>, tensor<32x64xf32>) -> tensor<32x64xf32>
    return %1: tensor<32x64xf32>
  }
}

// CPU:  llvm.func @enzymexla_wrapper_lapacke_sormqr_[[WRAPPER_ID:[0-9]+]](%arg0: !llvm.ptr, %arg1: !llvm.ptr, %arg2: !llvm.ptr) {
// CPU-NEXT:    %0 = llvm.mlir.constant(101 : i64) : i64
// CPU-NEXT:    %1 = llvm.mlir.constant(76 : i8) : i8
// CPU-NEXT:    %2 = llvm.mlir.constant(78 : i8) : i8
// CPU-NEXT:    %3 = llvm.mlir.constant(32 : i64) : i64
// CPU-NEXT:    %4 = llvm.mlir.constant(64 : i64) : i64
// CPU-NEXT:    %5 = llvm.call @enzymexla_lapacke_sormqr_(%0, %1, %2, %3, %4, %3, %arg0, %3, %arg1, %arg2, %3) : (i64, i8, i8, i64, i64, i64, !llvm.ptr, i64, !llvm.ptr, !llvm.ptr, i64) -> i64
// CPU-NEXT:    llvm.return
// CPU-NEXT:  }
// CPU-NEXT:  llvm.func @enzymexla_lapacke_sormqr_(i64, i8, i8, i64, i64, i64, !llvm.ptr, i64, !llvm.ptr, !llvm.ptr, i64) -> i64
// CPU-NEXT:  func.func @main(%arg0: tensor<32x64xf32>, %arg1: tensor<32xf32>, %arg2: tensor<32x64xf32>) -> tensor<32x64xf32> {
// CPU-NEXT:    %0 = stablehlo.slice %arg0 [0:32, 0:32] : (tensor<32x64xf32>) -> tensor<32x32xf32>
// CPU-NEXT:    %1 = enzymexla.jit_call @enzymexla_wrapper_lapacke_sormqr_[[WRAPPER_ID]] (%0, %arg1, %arg2) {operand_layouts = [dense<[0, 1]> : tensor<2xindex>, dense<0> : tensor<1xindex>, dense<[0, 1]> : tensor<2xindex>], output_operand_aliases = [#stablehlo.output_operand_alias<output_tuple_indices = [], operand_index = 2, operand_tuple_indices = []>], result_layouts = [dense<[0, 1]> : tensor<2xindex>], xla_side_effect_free} : (tensor<32x32xf32>, tensor<32xf32>, tensor<32x64xf32>) -> tensor<32x64xf32>
// CPU-NEXT:    return %1 : tensor<32x64xf32>
// CPU-NEXT:  }

module {
  func.func @main(%arg0: tensor<32x64xf32>, %arg1: tensor<32xf32>, %arg2: tensor<32x64xf32>) -> tensor<32x64xf32> {
    %0 = "stablehlo.slice"(%arg0) {start_indices = array<i64: 0, 0>, limit_indices = array<i64: 32, 32>, strides = array<i64: 1, 1>} : (tensor<32x64xf32>) -> tensor<32x32xf32>
    %1 = enzymexla.lapack.ormqr %0, %arg1, %arg2 {side = #enzymexla.side<left>, transpose = #enzymexla.transpose<transpose>} : (tensor<32x32xf32>, tensor<32xf32>, tensor<32x64xf32>) -> tensor<32x64xf32>
    return %1: tensor<32x64xf32>
  }
}

// CPU:  llvm.func @enzymexla_wrapper_lapacke_sormqr_[[WRAPPER_ID:[0-9]+]](%arg0: !llvm.ptr, %arg1: !llvm.ptr, %arg2: !llvm.ptr) {
// CPU-NEXT:    %0 = llvm.mlir.constant(101 : i64) : i64
// CPU-NEXT:    %1 = llvm.mlir.constant(76 : i8) : i8
// CPU-NEXT:    %2 = llvm.mlir.constant(84 : i8) : i8
// CPU-NEXT:    %3 = llvm.mlir.constant(32 : i64) : i64
// CPU-NEXT:    %4 = llvm.mlir.constant(64 : i64) : i64
// CPU-NEXT:    %5 = llvm.call @enzymexla_lapacke_sormqr_(%0, %1, %2, %3, %4, %3, %arg0, %3, %arg1, %arg2, %3) : (i64, i8, i8, i64, i64, i64, !llvm.ptr, i64, !llvm.ptr, !llvm.ptr, i64) -> i64
// CPU-NEXT:    llvm.return
// CPU-NEXT:  }
// CPU-NEXT:  llvm.func @enzymexla_lapacke_sormqr_(i64, i8, i8, i64, i64, i64, !llvm.ptr, i64, !llvm.ptr, !llvm.ptr, i64) -> i64
// CPU-NEXT:  func.func @main(%arg0: tensor<32x64xf32>, %arg1: tensor<32xf32>, %arg2: tensor<32x64xf32>) -> tensor<32x64xf32> {
// CPU-NEXT:    %0 = stablehlo.slice %arg0 [0:32, 0:32] : (tensor<32x64xf32>) -> tensor<32x32xf32>
// CPU-NEXT:    %1 = enzymexla.jit_call @enzymexla_wrapper_lapacke_sormqr_[[WRAPPER_ID]] (%0, %arg1, %arg2) {operand_layouts = [dense<[0, 1]> : tensor<2xindex>, dense<0> : tensor<1xindex>, dense<[0, 1]> : tensor<2xindex>], output_operand_aliases = [#stablehlo.output_operand_alias<output_tuple_indices = [], operand_index = 2, operand_tuple_indices = []>], result_layouts = [dense<[0, 1]> : tensor<2xindex>], xla_side_effect_free} : (tensor<32x32xf32>, tensor<32xf32>, tensor<32x64xf32>) -> tensor<32x64xf32>
// CPU-NEXT:    return %1 : tensor<32x64xf32>
// CPU-NEXT:  }

module {
  func.func @main(%arg0: tensor<32x64xf32>, %arg1: tensor<32xf32>, %arg2: tensor<64x32xf32>) -> tensor<64x32xf32> {
    %0 = "stablehlo.slice"(%arg0) {start_indices = array<i64: 0, 0>, limit_indices = array<i64: 32, 32>, strides = array<i64: 1, 1>} : (tensor<32x64xf32>) -> tensor<32x32xf32>
    %1 = enzymexla.lapack.ormqr %0, %arg1, %arg2 {side = #enzymexla.side<right>} : (tensor<32x32xf32>, tensor<32xf32>, tensor<64x32xf32>) -> tensor<64x32xf32>
    return %1: tensor<64x32xf32>
  }
}

// CPU:  llvm.func @enzymexla_wrapper_lapacke_sormqr_[[WRAPPER_ID:[0-9]+]](%arg0: !llvm.ptr, %arg1: !llvm.ptr, %arg2: !llvm.ptr) {
// CPU-NEXT:    %0 = llvm.mlir.constant(101 : i64) : i64
// CPU-NEXT:    %1 = llvm.mlir.constant(82 : i8) : i8
// CPU-NEXT:    %2 = llvm.mlir.constant(78 : i8) : i8
// CPU-NEXT:    %3 = llvm.mlir.constant(64 : i64) : i64
// CPU-NEXT:    %4 = llvm.mlir.constant(32 : i64) : i64
// CPU-NEXT:    %5 = llvm.call @enzymexla_lapacke_sormqr_(%0, %1, %2, %3, %4, %4, %arg0, %4, %arg1, %arg2, %3) : (i64, i8, i8, i64, i64, i64, !llvm.ptr, i64, !llvm.ptr, !llvm.ptr, i64) -> i64
// CPU-NEXT:    llvm.return
// CPU-NEXT:  }
// CPU-NEXT:  llvm.func @enzymexla_lapacke_sormqr_(i64, i8, i8, i64, i64, i64, !llvm.ptr, i64, !llvm.ptr, !llvm.ptr, i64) -> i64
// CPU-NEXT:  func.func @main(%arg0: tensor<32x64xf32>, %arg1: tensor<32xf32>, %arg2: tensor<64x32xf32>) -> tensor<64x32xf32> {
// CPU-NEXT:    %0 = stablehlo.slice %arg0 [0:32, 0:32] : (tensor<32x64xf32>) -> tensor<32x32xf32>
// CPU-NEXT:    %1 = enzymexla.jit_call @enzymexla_wrapper_lapacke_sormqr_[[WRAPPER_ID]] (%0, %arg1, %arg2) {operand_layouts = [dense<[0, 1]> : tensor<2xindex>, dense<0> : tensor<1xindex>, dense<[0, 1]> : tensor<2xindex>], output_operand_aliases = [#stablehlo.output_operand_alias<output_tuple_indices = [], operand_index = 2, operand_tuple_indices = []>], result_layouts = [dense<[0, 1]> : tensor<2xindex>], xla_side_effect_free} : (tensor<32x32xf32>, tensor<32xf32>, tensor<64x32xf32>) -> tensor<64x32xf32>
// CPU-NEXT:    return %1 : tensor<64x32xf32>
// CPU-NEXT:  }

module {
  func.func @main(%arg0: tensor<32x64xf32>, %arg1: tensor<32xf32>, %arg2: tensor<64x32xf32>) -> tensor<64x32xf32> {
    %0 = "stablehlo.slice"(%arg0) {start_indices = array<i64: 0, 0>, limit_indices = array<i64: 32, 32>, strides = array<i64: 1, 1>} : (tensor<32x64xf32>) -> tensor<32x32xf32>
    %1 = enzymexla.lapack.ormqr %0, %arg1, %arg2 {side = #enzymexla.side<right>, transpose = #enzymexla.transpose<transpose>} : (tensor<32x32xf32>, tensor<32xf32>, tensor<64x32xf32>) -> tensor<64x32xf32>
    return %1: tensor<64x32xf32>
  }
}

// CPU:  llvm.func @enzymexla_wrapper_lapacke_sormqr_[[WRAPPER_ID:[0-9]+]](%arg0: !llvm.ptr, %arg1: !llvm.ptr, %arg2: !llvm.ptr) {
// CPU-NEXT:    %0 = llvm.mlir.constant(101 : i64) : i64
// CPU-NEXT:    %1 = llvm.mlir.constant(82 : i8) : i8
// CPU-NEXT:    %2 = llvm.mlir.constant(84 : i8) : i8
// CPU-NEXT:    %3 = llvm.mlir.constant(64 : i64) : i64
// CPU-NEXT:    %4 = llvm.mlir.constant(32 : i64) : i64
// CPU-NEXT:    %5 = llvm.call @enzymexla_lapacke_sormqr_(%0, %1, %2, %3, %4, %4, %arg0, %4, %arg1, %arg2, %3) : (i64, i8, i8, i64, i64, i64, !llvm.ptr, i64, !llvm.ptr, !llvm.ptr, i64) -> i64
// CPU-NEXT:    llvm.return
// CPU-NEXT:  }
// CPU-NEXT:  llvm.func @enzymexla_lapacke_sormqr_(i64, i8, i8, i64, i64, i64, !llvm.ptr, i64, !llvm.ptr, !llvm.ptr, i64) -> i64
// CPU-NEXT:  func.func @main(%arg0: tensor<32x64xf32>, %arg1: tensor<32xf32>, %arg2: tensor<64x32xf32>) -> tensor<64x32xf32> {
// CPU-NEXT:    %0 = stablehlo.slice %arg0 [0:32, 0:32] : (tensor<32x64xf32>) -> tensor<32x32xf32>
// CPU-NEXT:    %1 = enzymexla.jit_call @enzymexla_wrapper_lapacke_sormqr_[[WRAPPER_ID]] (%0, %arg1, %arg2) {operand_layouts = [dense<[0, 1]> : tensor<2xindex>, dense<0> : tensor<1xindex>, dense<[0, 1]> : tensor<2xindex>], output_operand_aliases = [#stablehlo.output_operand_alias<output_tuple_indices = [], operand_index = 2, operand_tuple_indices = []>], result_layouts = [dense<[0, 1]> : tensor<2xindex>], xla_side_effect_free} : (tensor<32x32xf32>, tensor<32xf32>, tensor<64x32xf32>) -> tensor<64x32xf32>
// CPU-NEXT:    return %1 : tensor<64x32xf32>
// CPU-NEXT:  }

module {
  func.func @main(%arg0: tensor<32x64xf64>, %arg1: tensor<32xf64>, %arg2: tensor<32x64xf64>) -> tensor<32x64xf64> {
    %0 = "stablehlo.slice"(%arg0) {start_indices = array<i64: 0, 0>, limit_indices = array<i64: 32, 32>, strides = array<i64: 1, 1>} : (tensor<32x64xf64>) -> tensor<32x32xf64>
    // CPU: enzymexla.jit_call @enzymexla_wrapper_lapacke_dormqr_[[WRAPPER_ID:[0-9]+]]
    %1 = enzymexla.lapack.ormqr %0, %arg1, %arg2 {side = #enzymexla.side<left>} : (tensor<32x32xf64>, tensor<32xf64>, tensor<32x64xf64>) -> tensor<32x64xf64>
    return %1: tensor<32x64xf64>
  }
}

module {
  func.func @main(%arg0: tensor<32x64xcomplex<f32>>, %arg1: tensor<32xcomplex<f32>>, %arg2: tensor<32x64xcomplex<f32>>) -> tensor<32x64xcomplex<f32>> {
    %0 = "stablehlo.slice"(%arg0) {start_indices = array<i64: 0, 0>, limit_indices = array<i64: 32, 32>, strides = array<i64: 1, 1>} : (tensor<32x64xcomplex<f32>>) -> tensor<32x32xcomplex<f32>>
    // CPU: enzymexla.jit_call @enzymexla_wrapper_lapacke_cunmqr_[[WRAPPER_ID:[0-9]+]]
    %1 = enzymexla.lapack.ormqr %0, %arg1, %arg2 {side = #enzymexla.side<left>} : (tensor<32x32xcomplex<f32>>, tensor<32xcomplex<f32>>, tensor<32x64xcomplex<f32>>) -> tensor<32x64xcomplex<f32>>
    return %1: tensor<32x64xcomplex<f32>>
  }
}

module {
  func.func @main(%arg0: tensor<32x64xcomplex<f64>>, %arg1: tensor<32xcomplex<f64>>, %arg2: tensor<32x64xcomplex<f64>>) -> tensor<32x64xcomplex<f64>> {
    %0 = "stablehlo.slice"(%arg0) {start_indices = array<i64: 0, 0>, limit_indices = array<i64: 32, 32>, strides = array<i64: 1, 1>} : (tensor<32x64xcomplex<f64>>) -> tensor<32x32xcomplex<f64>>
    // CPU: enzymexla.jit_call @enzymexla_wrapper_lapacke_zunmqr_[[WRAPPER_ID:[0-9]+]]
    %1 = enzymexla.lapack.ormqr %0, %arg1, %arg2 {side = #enzymexla.side<left>} : (tensor<32x32xcomplex<f64>>, tensor<32xcomplex<f64>>, tensor<32x64xcomplex<f64>>) -> tensor<32x64xcomplex<f64>>
    return %1: tensor<32x64xcomplex<f64>>
  }
}
