// RUN: enzymexlamlir-opt --enzyme-hlo-opt="enable_auto_batching_passes=true" %s | FileCheck %s

func.func @main(%arg0: tensor<5x5xf32>, %arg1: tensor<5xf32>, %arg2: tensor<3x5xf32>) -> tensor<3x5xf32> {
    %cst = stablehlo.constant dense<"0x000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040"> : tensor<15x3x5xf32>
    %cst_0 = stablehlo.constant dense<1.59576917> : tensor<15x5x3xf32>
    %cst_1 = stablehlo.constant dense<1.000000e+00> : tensor<5x3xf32>
    %cst_2 = stablehlo.constant dense<4.471500e-02> : tensor<5x3xf32>
    %cst_3 = stablehlo.constant dense<1.59576917> : tensor<5x3xf32>
    %c = stablehlo.constant dense<0> : tensor<i32>
    %c_4 = stablehlo.constant dense<5> : tensor<i64>
    %c_5 = stablehlo.constant dense<1> : tensor<i32>
    %c_6 = stablehlo.constant dense<0> : tensor<i64>
    %c_7 = stablehlo.constant dense<1> : tensor<i64>
    %cst_8 = stablehlo.constant dense<0.000000e+00> : tensor<3x5xf32>
    %cst_9 = stablehlo.constant dense<"0x0000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F"> : tensor<15x3x5xf32>
    %c_10 = stablehlo.constant dense<15> : tensor<i64>
    %0 = stablehlo.broadcast_in_dim %arg0, dims = [1, 2] : (tensor<5x5xf32>) -> tensor<15x5x5xf32>
    %1 = stablehlo.dot_general %0, %cst_9, batching_dims = [0] x [0], contracting_dims = [1] x [2] : (tensor<15x5x5xf32>, tensor<15x3x5xf32>) -> tensor<15x5x3xf32>
    %2 = stablehlo.multiply %1, %cst_0 : tensor<15x5x3xf32>
    %3 = stablehlo.broadcast_in_dim %arg1, dims = [0] : (tensor<5xf32>) -> tensor<5x3xf32>
    %4 = stablehlo.dot_general %0, %cst, batching_dims = [0] x [0], contracting_dims = [1] x [2] : (tensor<15x5x5xf32>, tensor<15x3x5xf32>) -> tensor<15x5x3xf32>
    %5:2 = stablehlo.while(%iterArg = %c_6, %iterArg_11 = %cst_8) : tensor<i64>, tensor<3x5xf32>
    cond {
      %6 = stablehlo.compare  LT, %iterArg, %c_10 : (tensor<i64>, tensor<i64>) -> tensor<i1>
      stablehlo.return %6 : tensor<i1>
    } do {
      %6 = stablehlo.add %c_7, %iterArg : tensor<i64>
      %7 = stablehlo.dynamic_slice %1, %iterArg, %c_6, %c_6, sizes = [1, 5, 3] : (tensor<15x5x3xf32>, tensor<i64>, tensor<i64>, tensor<i64>) -> tensor<1x5x3xf32>
      %8 = stablehlo.reshape %7 : (tensor<1x5x3xf32>) -> tensor<5x3xf32>
      %9 = stablehlo.dot_general %arg0, %arg2, contracting_dims = [0] x [1] : (tensor<5x5xf32>, tensor<3x5xf32>) -> tensor<5x3xf32>
      %10 = stablehlo.add %9, %3 : tensor<5x3xf32>
      %11 = stablehlo.dynamic_slice %4, %iterArg, %c_6, %c_6, sizes = [1, 5, 3] : (tensor<15x5x3xf32>, tensor<i64>, tensor<i64>, tensor<i64>) -> tensor<1x5x3xf32>
      %12 = stablehlo.reshape %11 : (tensor<1x5x3xf32>) -> tensor<5x3xf32>
      %13 = stablehlo.multiply %10, %12 : tensor<5x3xf32>
      %14 = stablehlo.multiply %10, %10 : tensor<5x3xf32>
      %15 = stablehlo.multiply %13, %cst_2 : tensor<5x3xf32>
      %16 = stablehlo.multiply %14, %cst_2 : tensor<5x3xf32>
      %17 = stablehlo.add %16, %cst_1 : tensor<5x3xf32>
      %18 = stablehlo.dynamic_slice %2, %iterArg, %c_6, %c_6, sizes = [1, 5, 3] : (tensor<15x5x3xf32>, tensor<i64>, tensor<i64>, tensor<i64>) -> tensor<1x5x3xf32>
      %19 = stablehlo.reshape %18 : (tensor<1x5x3xf32>) -> tensor<5x3xf32>
      %20 = stablehlo.multiply %cst_3, %10 : tensor<5x3xf32>
      %21 = stablehlo.multiply %19, %17 : tensor<5x3xf32>
      %22 = stablehlo.multiply %15, %20 : tensor<5x3xf32>
      %23 = stablehlo.add %21, %22 : tensor<5x3xf32>
      %24 = stablehlo.multiply %20, %17 : tensor<5x3xf32>
      %25 = stablehlo.logistic %24 : tensor<5x3xf32>
      %26 = stablehlo.subtract %cst_1, %25 : tensor<5x3xf32>
      %27 = stablehlo.multiply %25, %26 : tensor<5x3xf32>
      %28 = stablehlo.multiply %23, %27 : tensor<5x3xf32>
      %29 = stablehlo.multiply %8, %25 : tensor<5x3xf32>
      %30 = stablehlo.multiply %28, %10 : tensor<5x3xf32>
      %31 = stablehlo.add %29, %30 : tensor<5x3xf32>
      %32 = stablehlo.remainder %iterArg, %c_4 : tensor<i64>
      %33 = stablehlo.add %32, %c_7 : tensor<i64>
      %34 = stablehlo.convert %33 : (tensor<i64>) -> tensor<i32>
      %35 = stablehlo.subtract %34, %c_5 : tensor<i32>
      %36 = stablehlo.dynamic_slice %31, %35, %c, sizes = [1, 1] : (tensor<5x3xf32>, tensor<i32>, tensor<i32>) -> tensor<1x1xf32>
      %37 = stablehlo.dynamic_update_slice %iterArg_11, %36, %c, %35 : (tensor<3x5xf32>, tensor<1x1xf32>, tensor<i32>, tensor<i32>) -> tensor<3x5xf32>
      stablehlo.return %6, %37 : tensor<i64>, tensor<3x5xf32>
    }
    return %5#1 : tensor<3x5xf32>
}

// CHECK: func.func @main(%arg0: tensor<5x5xf32>, %arg1: tensor<5xf32>, %arg2: tensor<3x5xf32>) -> tensor<3x5xf32> {
// CHECK-NEXT:     %cst = stablehlo.constant dense<4.471500e-02> : tensor<15x5x3xf32>
// CHECK-NEXT:     %cst_0 = stablehlo.constant dense<1.59576917> : tensor<5x15x3xf32>
// CHECK-NEXT:     %cst_1 = stablehlo.constant dense<"0x000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040"> : tensor<15x3x5xf32>
// CHECK-NEXT:     %cst_2 = stablehlo.constant dense<1.000000e+00> : tensor<5x3xf32>
// CHECK-NEXT:     %cst_3 = stablehlo.constant dense<4.471500e-02> : tensor<5x3xf32>
// CHECK-NEXT:     %cst_4 = stablehlo.constant dense<1.59576917> : tensor<5x3xf32>
// CHECK-NEXT:     %c = stablehlo.constant dense<0> : tensor<i32>
// CHECK-NEXT:     %c_5 = stablehlo.constant dense<5> : tensor<i64>
// CHECK-NEXT:     %c_6 = stablehlo.constant dense<1> : tensor<i32>
// CHECK-NEXT:     %c_7 = stablehlo.constant dense<0> : tensor<i64>
// CHECK-NEXT:     %c_8 = stablehlo.constant dense<1> : tensor<i64>
// CHECK-NEXT:     %cst_9 = stablehlo.constant dense<0.000000e+00> : tensor<3x5xf32>
// CHECK-NEXT:     %cst_10 = stablehlo.constant dense<"0x0000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F"> : tensor<15x3x5xf32>
// CHECK-NEXT:     %c_11 = stablehlo.constant dense<15> : tensor<i64>
// CHECK-NEXT:     %0 = stablehlo.dot_general %arg0, %cst_10, contracting_dims = [0] x [2] : (tensor<5x5xf32>, tensor<15x3x5xf32>) -> tensor<5x15x3xf32>
// CHECK-NEXT:     %1 = stablehlo.transpose %0, dims = [1, 0, 2] : (tensor<5x15x3xf32>) -> tensor<15x5x3xf32>
// CHECK-NEXT:     %2 = stablehlo.multiply %0, %cst_0 : tensor<5x15x3xf32>
// CHECK-NEXT:     %3 = stablehlo.transpose %2, dims = [1, 0, 2] : (tensor<5x15x3xf32>) -> tensor<15x5x3xf32>
// CHECK-NEXT:     %4 = stablehlo.broadcast_in_dim %arg1, dims = [0] : (tensor<5xf32>) -> tensor<5x3xf32>
// CHECK-NEXT:     %5 = stablehlo.dot_general %arg0, %cst_1, contracting_dims = [0] x [2] : (tensor<5x5xf32>, tensor<15x3x5xf32>) -> tensor<5x15x3xf32>
// CHECK-NEXT:     %6 = stablehlo.transpose %5, dims = [1, 0, 2] : (tensor<5x15x3xf32>) -> tensor<15x5x3xf32>
// CHECK-NEXT:     %7 = stablehlo.dot_general %arg0, %arg2, contracting_dims = [0] x [1] : (tensor<5x5xf32>, tensor<3x5xf32>) -> tensor<5x3xf32>
// CHECK-NEXT:     %8 = stablehlo.add %7, %4 : tensor<5x3xf32>
// CHECK-NEXT:     %9 = stablehlo.multiply %8, %8 : tensor<5x3xf32>
// CHECK-NEXT:     %10 = stablehlo.multiply %9, %cst_3 : tensor<5x3xf32>
// CHECK-NEXT:     %11 = stablehlo.add %10, %cst_2 : tensor<5x3xf32>
// CHECK-NEXT:     %12 = stablehlo.broadcast_in_dim %11, dims = [1, 2] : (tensor<5x3xf32>) -> tensor<15x5x3xf32>
// CHECK-NEXT:     %13 = stablehlo.multiply %3, %12 : tensor<15x5x3xf32>
// CHECK-NEXT:     %14 = stablehlo.broadcast_in_dim %8, dims = [1, 2] : (tensor<5x3xf32>) -> tensor<15x5x3xf32>
// CHECK-NEXT:     %15 = stablehlo.multiply %14, %6 : tensor<15x5x3xf32>
// CHECK-NEXT:     %16 = stablehlo.multiply %cst_4, %8 : tensor<5x3xf32>
// CHECK-NEXT:     %17 = stablehlo.multiply %16, %11 : tensor<5x3xf32>
// CHECK-NEXT:     %18 = stablehlo.logistic %17 : tensor<5x3xf32>
// CHECK-NEXT:     %19 = stablehlo.broadcast_in_dim %18, dims = [1, 2] : (tensor<5x3xf32>) -> tensor<15x5x3xf32>
// CHECK-NEXT:     %20 = stablehlo.multiply %1, %19 : tensor<15x5x3xf32>
// CHECK-NEXT:     %21 = stablehlo.multiply %15, %cst : tensor<15x5x3xf32>
// CHECK-NEXT:     %22 = stablehlo.broadcast_in_dim %16, dims = [1, 2] : (tensor<5x3xf32>) -> tensor<15x5x3xf32>
// CHECK-NEXT:     %23 = stablehlo.multiply %21, %22 : tensor<15x5x3xf32>
// CHECK-NEXT:     %24 = stablehlo.add %13, %23 : tensor<15x5x3xf32>
// CHECK-NEXT:     %25 = stablehlo.logistic %17 : tensor<5x3xf32>
// CHECK-NEXT:     %26 = stablehlo.subtract %cst_2, %25 : tensor<5x3xf32>
// CHECK-NEXT:     %27 = stablehlo.multiply %25, %26 : tensor<5x3xf32>
// CHECK-NEXT:     %28 = stablehlo.broadcast_in_dim %27, dims = [1, 2] : (tensor<5x3xf32>) -> tensor<15x5x3xf32>
// CHECK-NEXT:     %29 = stablehlo.multiply %24, %28 : tensor<15x5x3xf32>
// CHECK-NEXT:     %30 = stablehlo.multiply %29, %14 : tensor<15x5x3xf32>
// CHECK-NEXT:     %31:2 = stablehlo.while(%iterArg = %c_7, %iterArg_12 = %cst_9) : tensor<i64>, tensor<3x5xf32>
// CHECK-NEXT:     cond {
// CHECK-NEXT:       %32 = stablehlo.compare  LT, %iterArg, %c_11 : (tensor<i64>, tensor<i64>) -> tensor<i1>
// CHECK-NEXT:       stablehlo.return %32 : tensor<i1>
// CHECK-NEXT:     } do {
// CHECK-NEXT:       %32 = stablehlo.add %c_8, %iterArg {enzymexla.bounds = {{.*}}} : tensor<i64>
// CHECK-NEXT:       %33 = stablehlo.dynamic_slice %20, %iterArg, %c_7, %c_7, sizes = [1, 5, 3] : (tensor<15x5x3xf32>, tensor<i64>, tensor<i64>, tensor<i64>) -> tensor<1x5x3xf32>
// CHECK-NEXT:       %34 = stablehlo.reshape %33 : (tensor<1x5x3xf32>) -> tensor<5x3xf32>
// CHECK-NEXT:       %35 = stablehlo.dynamic_slice %30, %iterArg, %c_7, %c_7, sizes = [1, 5, 3] : (tensor<15x5x3xf32>, tensor<i64>, tensor<i64>, tensor<i64>) -> tensor<1x5x3xf32>
// CHECK-NEXT:       %36 = stablehlo.reshape %35 : (tensor<1x5x3xf32>) -> tensor<5x3xf32>
// CHECK-NEXT:       %37 = stablehlo.remainder %iterArg, %c_5 {enzymexla.bounds = {{.*}}} : tensor<i64>
// CHECK-NEXT:       %38 = stablehlo.add %37, %c_8 {enzymexla.bounds = {{.*}}} : tensor<i64>
// CHECK-NEXT:       %39 = stablehlo.convert %38 {enzymexla.bounds = {{.*}}} : (tensor<i64>) -> tensor<i32>
// CHECK-NEXT:       %40 = stablehlo.subtract %39, %c_6 {enzymexla.bounds = {{.*}}} : tensor<i32>
// CHECK-NEXT:       %41 = stablehlo.dynamic_slice %34, %40, %c, sizes = [1, 1] : (tensor<5x3xf32>, tensor<i32>, tensor<i32>) -> tensor<1x1xf32>
// CHECK-NEXT:       %42 = stablehlo.dynamic_slice %36, %40, %c, sizes = [1, 1] : (tensor<5x3xf32>, tensor<i32>, tensor<i32>) -> tensor<1x1xf32>
// CHECK-NEXT:       %43 = stablehlo.add %41, %42 : tensor<1x1xf32>
// CHECK-NEXT:       %44 = stablehlo.dynamic_update_slice %iterArg_12, %43, %c, %40 : (tensor<3x5xf32>, tensor<1x1xf32>, tensor<i32>, tensor<i32>) -> tensor<3x5xf32>
// CHECK-NEXT:       stablehlo.return %32, %44 : tensor<i64>, tensor<3x5xf32>
// CHECK-NEXT:     }
// CHECK-NEXT:     return %31#1 : tensor<3x5xf32>
// CHECK-NEXT:   }
