steps:
  - name: "CI {{matrix.arch}} -- {{matrix.os}} python {{matrix.python}}"
    matrix:
      setup:
        arch:
          - aarch64
          - x86_64
        os:
          - macos
        python:
          - "3.12"
    agents:
      queue: "juliaecosystem"
      os: "{{matrix.os}}"
      arch: "{{matrix.arch}}"
    if: build.tag == null
    plugins:
      - cache#v0.6.0:
          manifest: .buildkite/pipeline.yml
          path: .local
          restore: file
          save: file
      - cache#v0.6.0:
          manifest: WORKSPACE
          path: .baztmp
          restore: file
          save: file
    commands: |
      mkdir -p .local/bin
      export PATH="`pwd`/.local/bin:`pwd`/conda/bin:\$PATH"
      echo "openssl md5 | cut -d' ' -f2" > .local/bin/md5
      chmod +x .local/bin/md5

      if [ "{{matrix.os}}" == "macos" ]; then
        curl -fLO "https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-darwin"
        mv bazelisk-darwin .local/bin/bazel
        chmod +x .local/bin/bazel
      elif [ "{{matrix.os}}" == "linux" ]; then
        mv bazel* .local/bin/bazel
        chmod +x .local/bin/bazel
      else
        if [ "{{matrix.arch}}" == "aarch64" ]; then
          wget https://github.com/bazelbuild/bazel/releases/download/6.2.1/bazel-6.2.1-windows-arm64.exe
        else
          wget https://github.com/bazelbuild/bazel/releases/download/6.2.1/bazel-6.2.1-windows-x86_64.exe
        fi
        mv bazel* .local/bin/bazel.exe
      fi
      mkdir -p .baztmp
      HERMETIC_PYTHON_VERSION={{matrix.python}} bazel --output_user_root=`pwd`/.baztmp test --test_output=errors //test/...
      HERMETIC_PYTHON_VERSION={{matrix.python}} bazel --output_user_root=`pwd`/.baztmp test --cache_test_results=no //test:bench_vs_xla
      HERMETIC_PYTHON_VERSION={{matrix.python}} bazel --output_user_root=`pwd`/.baztmp test --cache_test_results=no //test:llama
      cat bazel-out/*/testlogs/test/llama/test.log
      rm -f bazel-bin/*.whl
      HERMETIC_PYTHON_VERSION={{matrix.python}} bazel --output_user_root=`pwd`/.baztmp build :wheel
      cp bazel-bin/*.whl .
    artifact_paths:
      - "*.whl"
      - "bazel-out/*/testlogs/test/llama/test.log"
      - "bazel-out/*/testlogs/test/llama/bench_vs_xla.log"

    timeout_in_minutes: 180
