"""Backend detection and requirements selection for Enzyme-JAX.

This module provides:
- detect_backend: Repository rule that detects the appropriate backend
- get_requirements_files: Helper to get the right requirements lock files

Usage:
    Set ENZYMEXLA_BACKEND=cuda12|cuda13|tpu|cpu to force a specific backend.
    If not set, auto-detects based on available hardware and CUDA version:
    - nvidia-smi present -> cuda12 or cuda13 (based on installed version)
    - /dev/accel* present -> tpu
    - otherwise -> cpu
"""

def _detect_cuda_version(repository_ctx):
    """Detect CUDA major version from nvidia-smi output.

    Returns:
        "12", "13", or None if detection fails.
    """

    # Try nvidia-smi first - it shows CUDA version in header like "CUDA Version: 12.4"
    result = repository_ctx.execute([
        "sh",
        "-c",
        "nvidia-smi 2>/dev/null | grep 'CUDA Version' | sed -E 's/.*CUDA Version: ([0-9]+).*/\\1/'",
    ])
    if result.return_code == 0 and result.stdout.strip():
        cuda_major = result.stdout.strip()
        if cuda_major == "13":
            return "13"
        elif cuda_major == "12":
            return "12"

    # Fallback: Try nvcc --version
    result = repository_ctx.execute(["sh", "-c", "nvcc --version 2>/dev/null | grep 'release'"])
    if result.return_code == 0 and result.stdout.strip():
        # Output like: "Cuda compilation tools, release 12.4, V12.4.131"
        output = result.stdout.strip()
        if "release 13" in output:
            return "13"
        elif "release 12" in output:
            return "12"

    # Fallback: Try reading /usr/local/cuda/version.txt
    result = repository_ctx.execute(["sh", "-c", "cat /usr/local/cuda/version.txt 2>/dev/null"])
    if result.return_code == 0 and result.stdout.strip():
        output = result.stdout.strip()
        if "13." in output:
            return "13"
        elif "12." in output:
            return "12"

    # Default to CUDA 12 if detection fails but nvidia-smi exists
    return "12"

def _detect_backend_impl(repository_ctx):
    """Detect which backend to use based on environment variable or hardware."""
    backend_env = repository_ctx.os.environ.get("ENZYMEXLA_BACKEND", "")

    if backend_env != "":
        # Use explicitly specified backend
        backend = backend_env.lower()
        valid_backends = ["cuda12", "cuda13", "cuda", "tpu", "cpu"]
        if backend not in valid_backends:
            fail("Invalid ENZYMEXLA_BACKEND value: '{}'. Must be one of: {}.".format(
                backend,
                ", ".join(valid_backends),
            ))

        # Normalize "cuda" to detected version
        if backend == "cuda":
            cuda_version = _detect_cuda_version(repository_ctx)
            backend = "cuda" + cuda_version
    else:
        # Auto-detect based on available hardware
        # Check for CUDA (nvidia-smi)
        nvidia_result = repository_ctx.execute(["which", "nvidia-smi"])
        if nvidia_result.return_code == 0:
            cuda_version = _detect_cuda_version(repository_ctx)
            backend = "cuda" + cuda_version
        else:
            # Check for TPU (/dev/accel*)
            tpu_result = repository_ctx.execute(["sh", "-c", "ls /dev/accel* 2>/dev/null"])
            if tpu_result.return_code == 0 and tpu_result.stdout.strip() != "":
                backend = "tpu"
            else:
                backend = "cpu"

    # Determine if CUDA is enabled and which version
    cuda_enabled = backend.startswith("cuda")
    cuda_version = backend.replace("cuda", "") if cuda_enabled else ""

    repository_ctx.file("BUILD.bazel", "# Auto-generated by detect_backend rule")
    repository_ctx.file("defs.bzl", """
# Auto-generated: Backend variant selection
# Detected/configured backend: {backend}
BACKEND = "{backend}"
CUDA_ENABLED = {cuda_enabled}
CUDA_VERSION = "{cuda_version}"
TPU_ENABLED = {tpu_enabled}
""".format(
        backend = backend,
        cuda_enabled = str(cuda_enabled),
        cuda_version = cuda_version,
        tpu_enabled = str(backend == "tpu"),
    ))

detect_backend = repository_rule(
    implementation = _detect_backend_impl,
    environ = ["ENZYMEXLA_BACKEND"],
    local = True,  # Re-evaluate when environment changes
)

# Keep old name for backwards compatibility
detect_cuda = detect_backend

def get_requirements_files(backend = None):
    """Returns the requirements lock files dictionary for python_init_repositories.

    Args:
        backend: "cuda12", "cuda13", "tpu", "cpu", or None (use detected backend).

    Returns:
        A dictionary mapping Python versions to requirement lock file paths.
    """
    if backend == None:
        backend = "cpu"  # Default fallback

    valid_backends = ["cuda12", "cuda13", "tpu", "cpu"]
    if backend not in valid_backends:
        fail("Invalid backend: '{}'. Must be one of: {}.".format(
            backend,
            ", ".join(valid_backends),
        ))

    return {
        "3.11": "//builddeps:requirements_lock_3_11_{}.txt".format(backend),
        "3.12": "//builddeps:requirements_lock_3_12_{}.txt".format(backend),
        "3.13": "//builddeps:requirements_lock_3_13_{}.txt".format(backend),
    }
