// RUN: enzymexlamlir-opt %s --pass-pipeline="builtin.module(lower-probprog-to-stablehlo{backend=cpu},canonicalize,cse,canonicalize)" | FileCheck %s --check-prefix=CPU

module {
  // CPU:  func.func @test_split_2(%arg0: tensor<2xui64>) -> (tensor<2xui64>, tensor<2xui64>) {
  // CPU-NEXT:    %c = stablehlo.constant dense<5> : tensor<2xui32>
  // CPU-NEXT:    %c_0 = stablehlo.constant dense<4> : tensor<2xui32>
  // CPU-NEXT:    %c_1 = stablehlo.constant dense<3> : tensor<2xui32>
  // CPU-NEXT:    %c_2 = stablehlo.constant dense<2> : tensor<2xui32>
  // CPU-NEXT:    %c_3 = stablehlo.constant dense<24> : tensor<2xui32>
  // CPU-NEXT:    %c_4 = stablehlo.constant dense<16> : tensor<2xui32>
  // CPU-NEXT:    %c_5 = stablehlo.constant dense<29> : tensor<2xui32>
  // CPU-NEXT:    %c_6 = stablehlo.constant dense<17> : tensor<2xui32>
  // CPU-NEXT:    %c_7 = stablehlo.constant dense<1> : tensor<2xui32>
  // CPU-NEXT:    %c_8 = stablehlo.constant dense<6> : tensor<2xui32>
  // CPU-NEXT:    %c_9 = stablehlo.constant dense<26> : tensor<2xui32>
  // CPU-NEXT:    %c_10 = stablehlo.constant dense<15> : tensor<2xui32>
  // CPU-NEXT:    %c_11 = stablehlo.constant dense<32> : tensor<2xui32>
  // CPU-NEXT:    %c_12 = stablehlo.constant dense<13> : tensor<2xui32>
  // CPU-NEXT:    %c_13 = stablehlo.constant dense<466688986> : tensor<2xui32>
  // CPU-NEXT:    %c_14 = stablehlo.constant dense<0> : tensor<2xui32>
  // CPU-NEXT:    %0 = stablehlo.bitcast_convert %arg0 : (tensor<2xui64>) -> tensor<2x2xui32>
  // CPU-NEXT:    %1 = stablehlo.reshape %0 : (tensor<2x2xui32>) -> tensor<4xui32>
  // CPU-NEXT:    %2 = stablehlo.slice %1 [0:1] : (tensor<4xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %3 = stablehlo.reshape %2 : (tensor<1xui32>) -> tensor<ui32>
  // CPU-NEXT:    %4 = stablehlo.slice %1 [1:2] : (tensor<4xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %5 = stablehlo.reshape %4 : (tensor<1xui32>) -> tensor<ui32>
  // CPU-NEXT:    %6 = stablehlo.slice %1 [2:3] : (tensor<4xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %7 = stablehlo.reshape %6 : (tensor<1xui32>) -> tensor<ui32>
  // CPU-NEXT:    %8 = stablehlo.slice %1 [3:4] : (tensor<4xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %9 = stablehlo.reshape %8 : (tensor<1xui32>) -> tensor<ui32>
  // CPU-NEXT:    %10 = stablehlo.iota dim = 0 : tensor<2xui32>
  // CPU-NEXT:    %11 = stablehlo.broadcast_in_dim %3, dims = [] : (tensor<ui32>) -> tensor<2xui32>
  // CPU-NEXT:    %12 = stablehlo.broadcast_in_dim %5, dims = [] : (tensor<ui32>) -> tensor<2xui32>
  // CPU-NEXT:    %13 = stablehlo.broadcast_in_dim %7, dims = [] : (tensor<ui32>) -> tensor<2xui32>
  // CPU-NEXT:    %14 = stablehlo.broadcast_in_dim %9, dims = [] : (tensor<ui32>) -> tensor<2xui32>
  // CPU-NEXT:    %15 = stablehlo.xor %11, %12 : tensor<2xui32>
  // CPU-NEXT:    %16 = stablehlo.xor %15, %c_13 : tensor<2xui32>
  // CPU-NEXT:    %17 = stablehlo.add %c_14, %11 : tensor<2xui32>
  // CPU-NEXT:    %18 = stablehlo.add %10, %12 : tensor<2xui32>
  // CPU-NEXT:    %19 = stablehlo.add %17, %18 : tensor<2xui32>
  // CPU-NEXT:    %20 = stablehlo.subtract %c_11, %c_12 : tensor<2xui32>
  // CPU-NEXT:    %21 = stablehlo.shift_left %18, %c_12 : tensor<2xui32>
  // CPU-NEXT:    %22 = stablehlo.shift_right_logical %18, %20 : tensor<2xui32>
  // CPU-NEXT:    %23 = stablehlo.or %21, %22 : tensor<2xui32>
  // CPU-NEXT:    %24 = stablehlo.xor %19, %23 : tensor<2xui32>
  // CPU-NEXT:    %25 = stablehlo.add %19, %24 : tensor<2xui32>
  // CPU-NEXT:    %26 = stablehlo.subtract %c_11, %c_10 : tensor<2xui32>
  // CPU-NEXT:    %27 = stablehlo.shift_left %24, %c_10 : tensor<2xui32>
  // CPU-NEXT:    %28 = stablehlo.shift_right_logical %24, %26 : tensor<2xui32>
  // CPU-NEXT:    %29 = stablehlo.or %27, %28 : tensor<2xui32>
  // CPU-NEXT:    %30 = stablehlo.xor %25, %29 : tensor<2xui32>
  // CPU-NEXT:    %31 = stablehlo.add %25, %30 : tensor<2xui32>
  // CPU-NEXT:    %32 = stablehlo.subtract %c_11, %c_9 : tensor<2xui32>
  // CPU-NEXT:    %33 = stablehlo.shift_left %30, %c_9 : tensor<2xui32>
  // CPU-NEXT:    %34 = stablehlo.shift_right_logical %30, %32 : tensor<2xui32>
  // CPU-NEXT:    %35 = stablehlo.or %33, %34 : tensor<2xui32>
  // CPU-NEXT:    %36 = stablehlo.xor %31, %35 : tensor<2xui32>
  // CPU-NEXT:    %37 = stablehlo.add %31, %36 : tensor<2xui32>
  // CPU-NEXT:    %38 = stablehlo.subtract %c_11, %c_8 : tensor<2xui32>
  // CPU-NEXT:    %39 = stablehlo.shift_left %36, %c_8 : tensor<2xui32>
  // CPU-NEXT:    %40 = stablehlo.shift_right_logical %36, %38 : tensor<2xui32>
  // CPU-NEXT:    %41 = stablehlo.or %39, %40 : tensor<2xui32>
  // CPU-NEXT:    %42 = stablehlo.xor %37, %41 : tensor<2xui32>
  // CPU-NEXT:    %43 = stablehlo.add %37, %12 : tensor<2xui32>
  // CPU-NEXT:    %44 = stablehlo.add %42, %16 : tensor<2xui32>
  // CPU-NEXT:    %45 = stablehlo.add %44, %c_7 : tensor<2xui32>
  // CPU-NEXT:    %46 = stablehlo.add %43, %45 : tensor<2xui32>
  // CPU-NEXT:    %47 = stablehlo.subtract %c_11, %c_6 : tensor<2xui32>
  // CPU-NEXT:    %48 = stablehlo.shift_left %45, %c_6 : tensor<2xui32>
  // CPU-NEXT:    %49 = stablehlo.shift_right_logical %45, %47 : tensor<2xui32>
  // CPU-NEXT:    %50 = stablehlo.or %48, %49 : tensor<2xui32>
  // CPU-NEXT:    %51 = stablehlo.xor %46, %50 : tensor<2xui32>
  // CPU-NEXT:    %52 = stablehlo.add %46, %51 : tensor<2xui32>
  // CPU-NEXT:    %53 = stablehlo.subtract %c_11, %c_5 : tensor<2xui32>
  // CPU-NEXT:    %54 = stablehlo.shift_left %51, %c_5 : tensor<2xui32>
  // CPU-NEXT:    %55 = stablehlo.shift_right_logical %51, %53 : tensor<2xui32>
  // CPU-NEXT:    %56 = stablehlo.or %54, %55 : tensor<2xui32>
  // CPU-NEXT:    %57 = stablehlo.xor %52, %56 : tensor<2xui32>
  // CPU-NEXT:    %58 = stablehlo.add %52, %57 : tensor<2xui32>
  // CPU-NEXT:    %59 = stablehlo.subtract %c_11, %c_4 : tensor<2xui32>
  // CPU-NEXT:    %60 = stablehlo.shift_left %57, %c_4 : tensor<2xui32>
  // CPU-NEXT:    %61 = stablehlo.shift_right_logical %57, %59 : tensor<2xui32>
  // CPU-NEXT:    %62 = stablehlo.or %60, %61 : tensor<2xui32>
  // CPU-NEXT:    %63 = stablehlo.xor %58, %62 : tensor<2xui32>
  // CPU-NEXT:    %64 = stablehlo.add %58, %63 : tensor<2xui32>
  // CPU-NEXT:    %65 = stablehlo.subtract %c_11, %c_3 : tensor<2xui32>
  // CPU-NEXT:    %66 = stablehlo.shift_left %63, %c_3 : tensor<2xui32>
  // CPU-NEXT:    %67 = stablehlo.shift_right_logical %63, %65 : tensor<2xui32>
  // CPU-NEXT:    %68 = stablehlo.or %66, %67 : tensor<2xui32>
  // CPU-NEXT:    %69 = stablehlo.xor %64, %68 : tensor<2xui32>
  // CPU-NEXT:    %70 = stablehlo.add %64, %16 : tensor<2xui32>
  // CPU-NEXT:    %71 = stablehlo.add %69, %11 : tensor<2xui32>
  // CPU-NEXT:    %72 = stablehlo.add %71, %c_2 : tensor<2xui32>
  // CPU-NEXT:    %73 = stablehlo.add %70, %72 : tensor<2xui32>
  // CPU-NEXT:    %74 = stablehlo.shift_left %72, %c_12 : tensor<2xui32>
  // CPU-NEXT:    %75 = stablehlo.shift_right_logical %72, %20 : tensor<2xui32>
  // CPU-NEXT:    %76 = stablehlo.or %74, %75 : tensor<2xui32>
  // CPU-NEXT:    %77 = stablehlo.xor %73, %76 : tensor<2xui32>
  // CPU-NEXT:    %78 = stablehlo.add %73, %77 : tensor<2xui32>
  // CPU-NEXT:    %79 = stablehlo.shift_left %77, %c_10 : tensor<2xui32>
  // CPU-NEXT:    %80 = stablehlo.shift_right_logical %77, %26 : tensor<2xui32>
  // CPU-NEXT:    %81 = stablehlo.or %79, %80 : tensor<2xui32>
  // CPU-NEXT:    %82 = stablehlo.xor %78, %81 : tensor<2xui32>
  // CPU-NEXT:    %83 = stablehlo.add %78, %82 : tensor<2xui32>
  // CPU-NEXT:    %84 = stablehlo.shift_left %82, %c_9 : tensor<2xui32>
  // CPU-NEXT:    %85 = stablehlo.shift_right_logical %82, %32 : tensor<2xui32>
  // CPU-NEXT:    %86 = stablehlo.or %84, %85 : tensor<2xui32>
  // CPU-NEXT:    %87 = stablehlo.xor %83, %86 : tensor<2xui32>
  // CPU-NEXT:    %88 = stablehlo.add %83, %87 : tensor<2xui32>
  // CPU-NEXT:    %89 = stablehlo.shift_left %87, %c_8 : tensor<2xui32>
  // CPU-NEXT:    %90 = stablehlo.shift_right_logical %87, %38 : tensor<2xui32>
  // CPU-NEXT:    %91 = stablehlo.or %89, %90 : tensor<2xui32>
  // CPU-NEXT:    %92 = stablehlo.xor %88, %91 : tensor<2xui32>
  // CPU-NEXT:    %93 = stablehlo.add %88, %11 : tensor<2xui32>
  // CPU-NEXT:    %94 = stablehlo.add %92, %12 : tensor<2xui32>
  // CPU-NEXT:    %95 = stablehlo.add %94, %c_1 : tensor<2xui32>
  // CPU-NEXT:    %96 = stablehlo.add %93, %95 : tensor<2xui32>
  // CPU-NEXT:    %97 = stablehlo.shift_left %95, %c_6 : tensor<2xui32>
  // CPU-NEXT:    %98 = stablehlo.shift_right_logical %95, %47 : tensor<2xui32>
  // CPU-NEXT:    %99 = stablehlo.or %97, %98 : tensor<2xui32>
  // CPU-NEXT:    %100 = stablehlo.xor %96, %99 : tensor<2xui32>
  // CPU-NEXT:    %101 = stablehlo.add %96, %100 : tensor<2xui32>
  // CPU-NEXT:    %102 = stablehlo.shift_left %100, %c_5 : tensor<2xui32>
  // CPU-NEXT:    %103 = stablehlo.shift_right_logical %100, %53 : tensor<2xui32>
  // CPU-NEXT:    %104 = stablehlo.or %102, %103 : tensor<2xui32>
  // CPU-NEXT:    %105 = stablehlo.xor %101, %104 : tensor<2xui32>
  // CPU-NEXT:    %106 = stablehlo.add %101, %105 : tensor<2xui32>
  // CPU-NEXT:    %107 = stablehlo.shift_left %105, %c_4 : tensor<2xui32>
  // CPU-NEXT:    %108 = stablehlo.shift_right_logical %105, %59 : tensor<2xui32>
  // CPU-NEXT:    %109 = stablehlo.or %107, %108 : tensor<2xui32>
  // CPU-NEXT:    %110 = stablehlo.xor %106, %109 : tensor<2xui32>
  // CPU-NEXT:    %111 = stablehlo.add %106, %110 : tensor<2xui32>
  // CPU-NEXT:    %112 = stablehlo.shift_left %110, %c_3 : tensor<2xui32>
  // CPU-NEXT:    %113 = stablehlo.shift_right_logical %110, %65 : tensor<2xui32>
  // CPU-NEXT:    %114 = stablehlo.or %112, %113 : tensor<2xui32>
  // CPU-NEXT:    %115 = stablehlo.xor %111, %114 : tensor<2xui32>
  // CPU-NEXT:    %116 = stablehlo.add %111, %12 : tensor<2xui32>
  // CPU-NEXT:    %117 = stablehlo.add %115, %16 : tensor<2xui32>
  // CPU-NEXT:    %118 = stablehlo.add %117, %c_0 : tensor<2xui32>
  // CPU-NEXT:    %119 = stablehlo.add %116, %118 : tensor<2xui32>
  // CPU-NEXT:    %120 = stablehlo.shift_left %118, %c_12 : tensor<2xui32>
  // CPU-NEXT:    %121 = stablehlo.shift_right_logical %118, %20 : tensor<2xui32>
  // CPU-NEXT:    %122 = stablehlo.or %120, %121 : tensor<2xui32>
  // CPU-NEXT:    %123 = stablehlo.xor %119, %122 : tensor<2xui32>
  // CPU-NEXT:    %124 = stablehlo.add %119, %123 : tensor<2xui32>
  // CPU-NEXT:    %125 = stablehlo.shift_left %123, %c_10 : tensor<2xui32>
  // CPU-NEXT:    %126 = stablehlo.shift_right_logical %123, %26 : tensor<2xui32>
  // CPU-NEXT:    %127 = stablehlo.or %125, %126 : tensor<2xui32>
  // CPU-NEXT:    %128 = stablehlo.xor %124, %127 : tensor<2xui32>
  // CPU-NEXT:    %129 = stablehlo.add %124, %128 : tensor<2xui32>
  // CPU-NEXT:    %130 = stablehlo.shift_left %128, %c_9 : tensor<2xui32>
  // CPU-NEXT:    %131 = stablehlo.shift_right_logical %128, %32 : tensor<2xui32>
  // CPU-NEXT:    %132 = stablehlo.or %130, %131 : tensor<2xui32>
  // CPU-NEXT:    %133 = stablehlo.xor %129, %132 : tensor<2xui32>
  // CPU-NEXT:    %134 = stablehlo.add %129, %133 : tensor<2xui32>
  // CPU-NEXT:    %135 = stablehlo.shift_left %133, %c_8 : tensor<2xui32>
  // CPU-NEXT:    %136 = stablehlo.shift_right_logical %133, %38 : tensor<2xui32>
  // CPU-NEXT:    %137 = stablehlo.or %135, %136 : tensor<2xui32>
  // CPU-NEXT:    %138 = stablehlo.xor %134, %137 : tensor<2xui32>
  // CPU-NEXT:    %139 = stablehlo.add %134, %16 : tensor<2xui32>
  // CPU-NEXT:    %140 = stablehlo.add %138, %11 : tensor<2xui32>
  // CPU-NEXT:    %141 = stablehlo.add %140, %c : tensor<2xui32>
  // CPU-NEXT:    %142 = stablehlo.xor %13, %14 : tensor<2xui32>
  // CPU-NEXT:    %143 = stablehlo.xor %142, %c_13 : tensor<2xui32>
  // CPU-NEXT:    %144 = stablehlo.add %c_14, %13 : tensor<2xui32>
  // CPU-NEXT:    %145 = stablehlo.add %10, %14 : tensor<2xui32>
  // CPU-NEXT:    %146 = stablehlo.add %144, %145 : tensor<2xui32>
  // CPU-NEXT:    %147 = stablehlo.shift_left %145, %c_12 : tensor<2xui32>
  // CPU-NEXT:    %148 = stablehlo.shift_right_logical %145, %20 : tensor<2xui32>
  // CPU-NEXT:    %149 = stablehlo.or %147, %148 : tensor<2xui32>
  // CPU-NEXT:    %150 = stablehlo.xor %146, %149 : tensor<2xui32>
  // CPU-NEXT:    %151 = stablehlo.add %146, %150 : tensor<2xui32>
  // CPU-NEXT:    %152 = stablehlo.shift_left %150, %c_10 : tensor<2xui32>
  // CPU-NEXT:    %153 = stablehlo.shift_right_logical %150, %26 : tensor<2xui32>
  // CPU-NEXT:    %154 = stablehlo.or %152, %153 : tensor<2xui32>
  // CPU-NEXT:    %155 = stablehlo.xor %151, %154 : tensor<2xui32>
  // CPU-NEXT:    %156 = stablehlo.add %151, %155 : tensor<2xui32>
  // CPU-NEXT:    %157 = stablehlo.shift_left %155, %c_9 : tensor<2xui32>
  // CPU-NEXT:    %158 = stablehlo.shift_right_logical %155, %32 : tensor<2xui32>
  // CPU-NEXT:    %159 = stablehlo.or %157, %158 : tensor<2xui32>
  // CPU-NEXT:    %160 = stablehlo.xor %156, %159 : tensor<2xui32>
  // CPU-NEXT:    %161 = stablehlo.add %156, %160 : tensor<2xui32>
  // CPU-NEXT:    %162 = stablehlo.shift_left %160, %c_8 : tensor<2xui32>
  // CPU-NEXT:    %163 = stablehlo.shift_right_logical %160, %38 : tensor<2xui32>
  // CPU-NEXT:    %164 = stablehlo.or %162, %163 : tensor<2xui32>
  // CPU-NEXT:    %165 = stablehlo.xor %161, %164 : tensor<2xui32>
  // CPU-NEXT:    %166 = stablehlo.add %161, %14 : tensor<2xui32>
  // CPU-NEXT:    %167 = stablehlo.add %165, %143 : tensor<2xui32>
  // CPU-NEXT:    %168 = stablehlo.add %167, %c_7 : tensor<2xui32>
  // CPU-NEXT:    %169 = stablehlo.add %166, %168 : tensor<2xui32>
  // CPU-NEXT:    %170 = stablehlo.shift_left %168, %c_6 : tensor<2xui32>
  // CPU-NEXT:    %171 = stablehlo.shift_right_logical %168, %47 : tensor<2xui32>
  // CPU-NEXT:    %172 = stablehlo.or %170, %171 : tensor<2xui32>
  // CPU-NEXT:    %173 = stablehlo.xor %169, %172 : tensor<2xui32>
  // CPU-NEXT:    %174 = stablehlo.add %169, %173 : tensor<2xui32>
  // CPU-NEXT:    %175 = stablehlo.shift_left %173, %c_5 : tensor<2xui32>
  // CPU-NEXT:    %176 = stablehlo.shift_right_logical %173, %53 : tensor<2xui32>
  // CPU-NEXT:    %177 = stablehlo.or %175, %176 : tensor<2xui32>
  // CPU-NEXT:    %178 = stablehlo.xor %174, %177 : tensor<2xui32>
  // CPU-NEXT:    %179 = stablehlo.add %174, %178 : tensor<2xui32>
  // CPU-NEXT:    %180 = stablehlo.shift_left %178, %c_4 : tensor<2xui32>
  // CPU-NEXT:    %181 = stablehlo.shift_right_logical %178, %59 : tensor<2xui32>
  // CPU-NEXT:    %182 = stablehlo.or %180, %181 : tensor<2xui32>
  // CPU-NEXT:    %183 = stablehlo.xor %179, %182 : tensor<2xui32>
  // CPU-NEXT:    %184 = stablehlo.add %179, %183 : tensor<2xui32>
  // CPU-NEXT:    %185 = stablehlo.shift_left %183, %c_3 : tensor<2xui32>
  // CPU-NEXT:    %186 = stablehlo.shift_right_logical %183, %65 : tensor<2xui32>
  // CPU-NEXT:    %187 = stablehlo.or %185, %186 : tensor<2xui32>
  // CPU-NEXT:    %188 = stablehlo.xor %184, %187 : tensor<2xui32>
  // CPU-NEXT:    %189 = stablehlo.add %184, %143 : tensor<2xui32>
  // CPU-NEXT:    %190 = stablehlo.add %188, %13 : tensor<2xui32>
  // CPU-NEXT:    %191 = stablehlo.add %190, %c_2 : tensor<2xui32>
  // CPU-NEXT:    %192 = stablehlo.add %189, %191 : tensor<2xui32>
  // CPU-NEXT:    %193 = stablehlo.shift_left %191, %c_12 : tensor<2xui32>
  // CPU-NEXT:    %194 = stablehlo.shift_right_logical %191, %20 : tensor<2xui32>
  // CPU-NEXT:    %195 = stablehlo.or %193, %194 : tensor<2xui32>
  // CPU-NEXT:    %196 = stablehlo.xor %192, %195 : tensor<2xui32>
  // CPU-NEXT:    %197 = stablehlo.add %192, %196 : tensor<2xui32>
  // CPU-NEXT:    %198 = stablehlo.shift_left %196, %c_10 : tensor<2xui32>
  // CPU-NEXT:    %199 = stablehlo.shift_right_logical %196, %26 : tensor<2xui32>
  // CPU-NEXT:    %200 = stablehlo.or %198, %199 : tensor<2xui32>
  // CPU-NEXT:    %201 = stablehlo.xor %197, %200 : tensor<2xui32>
  // CPU-NEXT:    %202 = stablehlo.add %197, %201 : tensor<2xui32>
  // CPU-NEXT:    %203 = stablehlo.shift_left %201, %c_9 : tensor<2xui32>
  // CPU-NEXT:    %204 = stablehlo.shift_right_logical %201, %32 : tensor<2xui32>
  // CPU-NEXT:    %205 = stablehlo.or %203, %204 : tensor<2xui32>
  // CPU-NEXT:    %206 = stablehlo.xor %202, %205 : tensor<2xui32>
  // CPU-NEXT:    %207 = stablehlo.add %202, %206 : tensor<2xui32>
  // CPU-NEXT:    %208 = stablehlo.shift_left %206, %c_8 : tensor<2xui32>
  // CPU-NEXT:    %209 = stablehlo.shift_right_logical %206, %38 : tensor<2xui32>
  // CPU-NEXT:    %210 = stablehlo.or %208, %209 : tensor<2xui32>
  // CPU-NEXT:    %211 = stablehlo.xor %207, %210 : tensor<2xui32>
  // CPU-NEXT:    %212 = stablehlo.add %207, %13 : tensor<2xui32>
  // CPU-NEXT:    %213 = stablehlo.add %211, %14 : tensor<2xui32>
  // CPU-NEXT:    %214 = stablehlo.add %213, %c_1 : tensor<2xui32>
  // CPU-NEXT:    %215 = stablehlo.add %212, %214 : tensor<2xui32>
  // CPU-NEXT:    %216 = stablehlo.shift_left %214, %c_6 : tensor<2xui32>
  // CPU-NEXT:    %217 = stablehlo.shift_right_logical %214, %47 : tensor<2xui32>
  // CPU-NEXT:    %218 = stablehlo.or %216, %217 : tensor<2xui32>
  // CPU-NEXT:    %219 = stablehlo.xor %215, %218 : tensor<2xui32>
  // CPU-NEXT:    %220 = stablehlo.add %215, %219 : tensor<2xui32>
  // CPU-NEXT:    %221 = stablehlo.shift_left %219, %c_5 : tensor<2xui32>
  // CPU-NEXT:    %222 = stablehlo.shift_right_logical %219, %53 : tensor<2xui32>
  // CPU-NEXT:    %223 = stablehlo.or %221, %222 : tensor<2xui32>
  // CPU-NEXT:    %224 = stablehlo.xor %220, %223 : tensor<2xui32>
  // CPU-NEXT:    %225 = stablehlo.add %220, %224 : tensor<2xui32>
  // CPU-NEXT:    %226 = stablehlo.shift_left %224, %c_4 : tensor<2xui32>
  // CPU-NEXT:    %227 = stablehlo.shift_right_logical %224, %59 : tensor<2xui32>
  // CPU-NEXT:    %228 = stablehlo.or %226, %227 : tensor<2xui32>
  // CPU-NEXT:    %229 = stablehlo.xor %225, %228 : tensor<2xui32>
  // CPU-NEXT:    %230 = stablehlo.add %225, %229 : tensor<2xui32>
  // CPU-NEXT:    %231 = stablehlo.shift_left %229, %c_3 : tensor<2xui32>
  // CPU-NEXT:    %232 = stablehlo.shift_right_logical %229, %65 : tensor<2xui32>
  // CPU-NEXT:    %233 = stablehlo.or %231, %232 : tensor<2xui32>
  // CPU-NEXT:    %234 = stablehlo.xor %230, %233 : tensor<2xui32>
  // CPU-NEXT:    %235 = stablehlo.add %230, %14 : tensor<2xui32>
  // CPU-NEXT:    %236 = stablehlo.add %234, %143 : tensor<2xui32>
  // CPU-NEXT:    %237 = stablehlo.add %236, %c_0 : tensor<2xui32>
  // CPU-NEXT:    %238 = stablehlo.add %235, %237 : tensor<2xui32>
  // CPU-NEXT:    %239 = stablehlo.shift_left %237, %c_12 : tensor<2xui32>
  // CPU-NEXT:    %240 = stablehlo.shift_right_logical %237, %20 : tensor<2xui32>
  // CPU-NEXT:    %241 = stablehlo.or %239, %240 : tensor<2xui32>
  // CPU-NEXT:    %242 = stablehlo.xor %238, %241 : tensor<2xui32>
  // CPU-NEXT:    %243 = stablehlo.add %238, %242 : tensor<2xui32>
  // CPU-NEXT:    %244 = stablehlo.shift_left %242, %c_10 : tensor<2xui32>
  // CPU-NEXT:    %245 = stablehlo.shift_right_logical %242, %26 : tensor<2xui32>
  // CPU-NEXT:    %246 = stablehlo.or %244, %245 : tensor<2xui32>
  // CPU-NEXT:    %247 = stablehlo.xor %243, %246 : tensor<2xui32>
  // CPU-NEXT:    %248 = stablehlo.add %243, %247 : tensor<2xui32>
  // CPU-NEXT:    %249 = stablehlo.shift_left %247, %c_9 : tensor<2xui32>
  // CPU-NEXT:    %250 = stablehlo.shift_right_logical %247, %32 : tensor<2xui32>
  // CPU-NEXT:    %251 = stablehlo.or %249, %250 : tensor<2xui32>
  // CPU-NEXT:    %252 = stablehlo.xor %248, %251 : tensor<2xui32>
  // CPU-NEXT:    %253 = stablehlo.add %248, %252 : tensor<2xui32>
  // CPU-NEXT:    %254 = stablehlo.shift_left %252, %c_8 : tensor<2xui32>
  // CPU-NEXT:    %255 = stablehlo.shift_right_logical %252, %38 : tensor<2xui32>
  // CPU-NEXT:    %256 = stablehlo.or %254, %255 : tensor<2xui32>
  // CPU-NEXT:    %257 = stablehlo.xor %253, %256 : tensor<2xui32>
  // CPU-NEXT:    %258 = stablehlo.add %253, %143 : tensor<2xui32>
  // CPU-NEXT:    %259 = stablehlo.add %257, %13 : tensor<2xui32>
  // CPU-NEXT:    %260 = stablehlo.add %259, %c : tensor<2xui32>
  // CPU-NEXT:    %261 = stablehlo.slice %139 [0:1] : (tensor<2xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %262 = stablehlo.slice %141 [0:1] : (tensor<2xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %263 = stablehlo.slice %258 [0:1] : (tensor<2xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %264 = stablehlo.slice %260 [0:1] : (tensor<2xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %265 = stablehlo.concatenate %261, %262, %263, %264, dim = 0 : (tensor<1xui32>, tensor<1xui32>, tensor<1xui32>, tensor<1xui32>) -> tensor<4xui32>
  // CPU-NEXT:    %266 = stablehlo.reshape %265 : (tensor<4xui32>) -> tensor<2x2xui32>
  // CPU-NEXT:    %267 = stablehlo.bitcast_convert %266 : (tensor<2x2xui32>) -> tensor<2xui64>
  // CPU-NEXT:    %268 = stablehlo.slice %139 [1:2] : (tensor<2xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %269 = stablehlo.slice %141 [1:2] : (tensor<2xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %270 = stablehlo.slice %258 [1:2] : (tensor<2xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %271 = stablehlo.slice %260 [1:2] : (tensor<2xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %272 = stablehlo.concatenate %268, %269, %270, %271, dim = 0 : (tensor<1xui32>, tensor<1xui32>, tensor<1xui32>, tensor<1xui32>) -> tensor<4xui32>
  // CPU-NEXT:    %273 = stablehlo.reshape %272 : (tensor<4xui32>) -> tensor<2x2xui32>
  // CPU-NEXT:    %274 = stablehlo.bitcast_convert %273 : (tensor<2x2xui32>) -> tensor<2xui64>
  // CPU-NEXT:    return %267, %274 : tensor<2xui64>, tensor<2xui64>
  // CPU-NEXT:  }
  func.func @test_split_2(%rng: tensor<2xui64>) -> (tensor<2xui64>, tensor<2xui64>) {
    %key1, %key2 = enzyme.randomSplit %rng : (tensor<2xui64>) -> (tensor<2xui64>, tensor<2xui64>)
    return %key1, %key2 : tensor<2xui64>, tensor<2xui64>
  }

  // CPU:  func.func @test_split_3(%arg0: tensor<2xui64>) -> (tensor<2xui64>, tensor<2xui64>, tensor<2xui64>) {
  // CPU-NEXT:    %c = stablehlo.constant dense<5> : tensor<3xui32>
  // CPU-NEXT:    %c_0 = stablehlo.constant dense<4> : tensor<3xui32>
  // CPU-NEXT:    %c_1 = stablehlo.constant dense<3> : tensor<3xui32>
  // CPU-NEXT:    %c_2 = stablehlo.constant dense<2> : tensor<3xui32>
  // CPU-NEXT:    %c_3 = stablehlo.constant dense<24> : tensor<3xui32>
  // CPU-NEXT:    %c_4 = stablehlo.constant dense<16> : tensor<3xui32>
  // CPU-NEXT:    %c_5 = stablehlo.constant dense<29> : tensor<3xui32>
  // CPU-NEXT:    %c_6 = stablehlo.constant dense<17> : tensor<3xui32>
  // CPU-NEXT:    %c_7 = stablehlo.constant dense<1> : tensor<3xui32>
  // CPU-NEXT:    %c_8 = stablehlo.constant dense<6> : tensor<3xui32>
  // CPU-NEXT:    %c_9 = stablehlo.constant dense<26> : tensor<3xui32>
  // CPU-NEXT:    %c_10 = stablehlo.constant dense<15> : tensor<3xui32>
  // CPU-NEXT:    %c_11 = stablehlo.constant dense<32> : tensor<3xui32>
  // CPU-NEXT:    %c_12 = stablehlo.constant dense<13> : tensor<3xui32>
  // CPU-NEXT:    %c_13 = stablehlo.constant dense<466688986> : tensor<3xui32>
  // CPU-NEXT:    %c_14 = stablehlo.constant dense<0> : tensor<3xui32>
  // CPU-NEXT:    %0 = stablehlo.bitcast_convert %arg0 : (tensor<2xui64>) -> tensor<2x2xui32>
  // CPU-NEXT:    %1 = stablehlo.reshape %0 : (tensor<2x2xui32>) -> tensor<4xui32>
  // CPU-NEXT:    %2 = stablehlo.slice %1 [0:1] : (tensor<4xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %3 = stablehlo.reshape %2 : (tensor<1xui32>) -> tensor<ui32>
  // CPU-NEXT:    %4 = stablehlo.slice %1 [1:2] : (tensor<4xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %5 = stablehlo.reshape %4 : (tensor<1xui32>) -> tensor<ui32>
  // CPU-NEXT:    %6 = stablehlo.slice %1 [2:3] : (tensor<4xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %7 = stablehlo.reshape %6 : (tensor<1xui32>) -> tensor<ui32>
  // CPU-NEXT:    %8 = stablehlo.slice %1 [3:4] : (tensor<4xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %9 = stablehlo.reshape %8 : (tensor<1xui32>) -> tensor<ui32>
  // CPU-NEXT:    %10 = stablehlo.iota dim = 0 : tensor<3xui32>
  // CPU-NEXT:    %11 = stablehlo.broadcast_in_dim %3, dims = [] : (tensor<ui32>) -> tensor<3xui32>
  // CPU-NEXT:    %12 = stablehlo.broadcast_in_dim %5, dims = [] : (tensor<ui32>) -> tensor<3xui32>
  // CPU-NEXT:    %13 = stablehlo.broadcast_in_dim %7, dims = [] : (tensor<ui32>) -> tensor<3xui32>
  // CPU-NEXT:    %14 = stablehlo.broadcast_in_dim %9, dims = [] : (tensor<ui32>) -> tensor<3xui32>
  // CPU-NEXT:    %15 = stablehlo.xor %11, %12 : tensor<3xui32>
  // CPU-NEXT:    %16 = stablehlo.xor %15, %c_13 : tensor<3xui32>
  // CPU-NEXT:    %17 = stablehlo.add %c_14, %11 : tensor<3xui32>
  // CPU-NEXT:    %18 = stablehlo.add %10, %12 : tensor<3xui32>
  // CPU-NEXT:    %19 = stablehlo.add %17, %18 : tensor<3xui32>
  // CPU-NEXT:    %20 = stablehlo.subtract %c_11, %c_12 : tensor<3xui32>
  // CPU-NEXT:    %21 = stablehlo.shift_left %18, %c_12 : tensor<3xui32>
  // CPU-NEXT:    %22 = stablehlo.shift_right_logical %18, %20 : tensor<3xui32>
  // CPU-NEXT:    %23 = stablehlo.or %21, %22 : tensor<3xui32>
  // CPU-NEXT:    %24 = stablehlo.xor %19, %23 : tensor<3xui32>
  // CPU-NEXT:    %25 = stablehlo.add %19, %24 : tensor<3xui32>
  // CPU-NEXT:    %26 = stablehlo.subtract %c_11, %c_10 : tensor<3xui32>
  // CPU-NEXT:    %27 = stablehlo.shift_left %24, %c_10 : tensor<3xui32>
  // CPU-NEXT:    %28 = stablehlo.shift_right_logical %24, %26 : tensor<3xui32>
  // CPU-NEXT:    %29 = stablehlo.or %27, %28 : tensor<3xui32>
  // CPU-NEXT:    %30 = stablehlo.xor %25, %29 : tensor<3xui32>
  // CPU-NEXT:    %31 = stablehlo.add %25, %30 : tensor<3xui32>
  // CPU-NEXT:    %32 = stablehlo.subtract %c_11, %c_9 : tensor<3xui32>
  // CPU-NEXT:    %33 = stablehlo.shift_left %30, %c_9 : tensor<3xui32>
  // CPU-NEXT:    %34 = stablehlo.shift_right_logical %30, %32 : tensor<3xui32>
  // CPU-NEXT:    %35 = stablehlo.or %33, %34 : tensor<3xui32>
  // CPU-NEXT:    %36 = stablehlo.xor %31, %35 : tensor<3xui32>
  // CPU-NEXT:    %37 = stablehlo.add %31, %36 : tensor<3xui32>
  // CPU-NEXT:    %38 = stablehlo.subtract %c_11, %c_8 : tensor<3xui32>
  // CPU-NEXT:    %39 = stablehlo.shift_left %36, %c_8 : tensor<3xui32>
  // CPU-NEXT:    %40 = stablehlo.shift_right_logical %36, %38 : tensor<3xui32>
  // CPU-NEXT:    %41 = stablehlo.or %39, %40 : tensor<3xui32>
  // CPU-NEXT:    %42 = stablehlo.xor %37, %41 : tensor<3xui32>
  // CPU-NEXT:    %43 = stablehlo.add %37, %12 : tensor<3xui32>
  // CPU-NEXT:    %44 = stablehlo.add %42, %16 : tensor<3xui32>
  // CPU-NEXT:    %45 = stablehlo.add %44, %c_7 : tensor<3xui32>
  // CPU-NEXT:    %46 = stablehlo.add %43, %45 : tensor<3xui32>
  // CPU-NEXT:    %47 = stablehlo.subtract %c_11, %c_6 : tensor<3xui32>
  // CPU-NEXT:    %48 = stablehlo.shift_left %45, %c_6 : tensor<3xui32>
  // CPU-NEXT:    %49 = stablehlo.shift_right_logical %45, %47 : tensor<3xui32>
  // CPU-NEXT:    %50 = stablehlo.or %48, %49 : tensor<3xui32>
  // CPU-NEXT:    %51 = stablehlo.xor %46, %50 : tensor<3xui32>
  // CPU-NEXT:    %52 = stablehlo.add %46, %51 : tensor<3xui32>
  // CPU-NEXT:    %53 = stablehlo.subtract %c_11, %c_5 : tensor<3xui32>
  // CPU-NEXT:    %54 = stablehlo.shift_left %51, %c_5 : tensor<3xui32>
  // CPU-NEXT:    %55 = stablehlo.shift_right_logical %51, %53 : tensor<3xui32>
  // CPU-NEXT:    %56 = stablehlo.or %54, %55 : tensor<3xui32>
  // CPU-NEXT:    %57 = stablehlo.xor %52, %56 : tensor<3xui32>
  // CPU-NEXT:    %58 = stablehlo.add %52, %57 : tensor<3xui32>
  // CPU-NEXT:    %59 = stablehlo.subtract %c_11, %c_4 : tensor<3xui32>
  // CPU-NEXT:    %60 = stablehlo.shift_left %57, %c_4 : tensor<3xui32>
  // CPU-NEXT:    %61 = stablehlo.shift_right_logical %57, %59 : tensor<3xui32>
  // CPU-NEXT:    %62 = stablehlo.or %60, %61 : tensor<3xui32>
  // CPU-NEXT:    %63 = stablehlo.xor %58, %62 : tensor<3xui32>
  // CPU-NEXT:    %64 = stablehlo.add %58, %63 : tensor<3xui32>
  // CPU-NEXT:    %65 = stablehlo.subtract %c_11, %c_3 : tensor<3xui32>
  // CPU-NEXT:    %66 = stablehlo.shift_left %63, %c_3 : tensor<3xui32>
  // CPU-NEXT:    %67 = stablehlo.shift_right_logical %63, %65 : tensor<3xui32>
  // CPU-NEXT:    %68 = stablehlo.or %66, %67 : tensor<3xui32>
  // CPU-NEXT:    %69 = stablehlo.xor %64, %68 : tensor<3xui32>
  // CPU-NEXT:    %70 = stablehlo.add %64, %16 : tensor<3xui32>
  // CPU-NEXT:    %71 = stablehlo.add %69, %11 : tensor<3xui32>
  // CPU-NEXT:    %72 = stablehlo.add %71, %c_2 : tensor<3xui32>
  // CPU-NEXT:    %73 = stablehlo.add %70, %72 : tensor<3xui32>
  // CPU-NEXT:    %74 = stablehlo.shift_left %72, %c_12 : tensor<3xui32>
  // CPU-NEXT:    %75 = stablehlo.shift_right_logical %72, %20 : tensor<3xui32>
  // CPU-NEXT:    %76 = stablehlo.or %74, %75 : tensor<3xui32>
  // CPU-NEXT:    %77 = stablehlo.xor %73, %76 : tensor<3xui32>
  // CPU-NEXT:    %78 = stablehlo.add %73, %77 : tensor<3xui32>
  // CPU-NEXT:    %79 = stablehlo.shift_left %77, %c_10 : tensor<3xui32>
  // CPU-NEXT:    %80 = stablehlo.shift_right_logical %77, %26 : tensor<3xui32>
  // CPU-NEXT:    %81 = stablehlo.or %79, %80 : tensor<3xui32>
  // CPU-NEXT:    %82 = stablehlo.xor %78, %81 : tensor<3xui32>
  // CPU-NEXT:    %83 = stablehlo.add %78, %82 : tensor<3xui32>
  // CPU-NEXT:    %84 = stablehlo.shift_left %82, %c_9 : tensor<3xui32>
  // CPU-NEXT:    %85 = stablehlo.shift_right_logical %82, %32 : tensor<3xui32>
  // CPU-NEXT:    %86 = stablehlo.or %84, %85 : tensor<3xui32>
  // CPU-NEXT:    %87 = stablehlo.xor %83, %86 : tensor<3xui32>
  // CPU-NEXT:    %88 = stablehlo.add %83, %87 : tensor<3xui32>
  // CPU-NEXT:    %89 = stablehlo.shift_left %87, %c_8 : tensor<3xui32>
  // CPU-NEXT:    %90 = stablehlo.shift_right_logical %87, %38 : tensor<3xui32>
  // CPU-NEXT:    %91 = stablehlo.or %89, %90 : tensor<3xui32>
  // CPU-NEXT:    %92 = stablehlo.xor %88, %91 : tensor<3xui32>
  // CPU-NEXT:    %93 = stablehlo.add %88, %11 : tensor<3xui32>
  // CPU-NEXT:    %94 = stablehlo.add %92, %12 : tensor<3xui32>
  // CPU-NEXT:    %95 = stablehlo.add %94, %c_1 : tensor<3xui32>
  // CPU-NEXT:    %96 = stablehlo.add %93, %95 : tensor<3xui32>
  // CPU-NEXT:    %97 = stablehlo.shift_left %95, %c_6 : tensor<3xui32>
  // CPU-NEXT:    %98 = stablehlo.shift_right_logical %95, %47 : tensor<3xui32>
  // CPU-NEXT:    %99 = stablehlo.or %97, %98 : tensor<3xui32>
  // CPU-NEXT:    %100 = stablehlo.xor %96, %99 : tensor<3xui32>
  // CPU-NEXT:    %101 = stablehlo.add %96, %100 : tensor<3xui32>
  // CPU-NEXT:    %102 = stablehlo.shift_left %100, %c_5 : tensor<3xui32>
  // CPU-NEXT:    %103 = stablehlo.shift_right_logical %100, %53 : tensor<3xui32>
  // CPU-NEXT:    %104 = stablehlo.or %102, %103 : tensor<3xui32>
  // CPU-NEXT:    %105 = stablehlo.xor %101, %104 : tensor<3xui32>
  // CPU-NEXT:    %106 = stablehlo.add %101, %105 : tensor<3xui32>
  // CPU-NEXT:    %107 = stablehlo.shift_left %105, %c_4 : tensor<3xui32>
  // CPU-NEXT:    %108 = stablehlo.shift_right_logical %105, %59 : tensor<3xui32>
  // CPU-NEXT:    %109 = stablehlo.or %107, %108 : tensor<3xui32>
  // CPU-NEXT:    %110 = stablehlo.xor %106, %109 : tensor<3xui32>
  // CPU-NEXT:    %111 = stablehlo.add %106, %110 : tensor<3xui32>
  // CPU-NEXT:    %112 = stablehlo.shift_left %110, %c_3 : tensor<3xui32>
  // CPU-NEXT:    %113 = stablehlo.shift_right_logical %110, %65 : tensor<3xui32>
  // CPU-NEXT:    %114 = stablehlo.or %112, %113 : tensor<3xui32>
  // CPU-NEXT:    %115 = stablehlo.xor %111, %114 : tensor<3xui32>
  // CPU-NEXT:    %116 = stablehlo.add %111, %12 : tensor<3xui32>
  // CPU-NEXT:    %117 = stablehlo.add %115, %16 : tensor<3xui32>
  // CPU-NEXT:    %118 = stablehlo.add %117, %c_0 : tensor<3xui32>
  // CPU-NEXT:    %119 = stablehlo.add %116, %118 : tensor<3xui32>
  // CPU-NEXT:    %120 = stablehlo.shift_left %118, %c_12 : tensor<3xui32>
  // CPU-NEXT:    %121 = stablehlo.shift_right_logical %118, %20 : tensor<3xui32>
  // CPU-NEXT:    %122 = stablehlo.or %120, %121 : tensor<3xui32>
  // CPU-NEXT:    %123 = stablehlo.xor %119, %122 : tensor<3xui32>
  // CPU-NEXT:    %124 = stablehlo.add %119, %123 : tensor<3xui32>
  // CPU-NEXT:    %125 = stablehlo.shift_left %123, %c_10 : tensor<3xui32>
  // CPU-NEXT:    %126 = stablehlo.shift_right_logical %123, %26 : tensor<3xui32>
  // CPU-NEXT:    %127 = stablehlo.or %125, %126 : tensor<3xui32>
  // CPU-NEXT:    %128 = stablehlo.xor %124, %127 : tensor<3xui32>
  // CPU-NEXT:    %129 = stablehlo.add %124, %128 : tensor<3xui32>
  // CPU-NEXT:    %130 = stablehlo.shift_left %128, %c_9 : tensor<3xui32>
  // CPU-NEXT:    %131 = stablehlo.shift_right_logical %128, %32 : tensor<3xui32>
  // CPU-NEXT:    %132 = stablehlo.or %130, %131 : tensor<3xui32>
  // CPU-NEXT:    %133 = stablehlo.xor %129, %132 : tensor<3xui32>
  // CPU-NEXT:    %134 = stablehlo.add %129, %133 : tensor<3xui32>
  // CPU-NEXT:    %135 = stablehlo.shift_left %133, %c_8 : tensor<3xui32>
  // CPU-NEXT:    %136 = stablehlo.shift_right_logical %133, %38 : tensor<3xui32>
  // CPU-NEXT:    %137 = stablehlo.or %135, %136 : tensor<3xui32>
  // CPU-NEXT:    %138 = stablehlo.xor %134, %137 : tensor<3xui32>
  // CPU-NEXT:    %139 = stablehlo.add %134, %16 : tensor<3xui32>
  // CPU-NEXT:    %140 = stablehlo.add %138, %11 : tensor<3xui32>
  // CPU-NEXT:    %141 = stablehlo.add %140, %c : tensor<3xui32>
  // CPU-NEXT:    %142 = stablehlo.xor %13, %14 : tensor<3xui32>
  // CPU-NEXT:    %143 = stablehlo.xor %142, %c_13 : tensor<3xui32>
  // CPU-NEXT:    %144 = stablehlo.add %c_14, %13 : tensor<3xui32>
  // CPU-NEXT:    %145 = stablehlo.add %10, %14 : tensor<3xui32>
  // CPU-NEXT:    %146 = stablehlo.add %144, %145 : tensor<3xui32>
  // CPU-NEXT:    %147 = stablehlo.shift_left %145, %c_12 : tensor<3xui32>
  // CPU-NEXT:    %148 = stablehlo.shift_right_logical %145, %20 : tensor<3xui32>
  // CPU-NEXT:    %149 = stablehlo.or %147, %148 : tensor<3xui32>
  // CPU-NEXT:    %150 = stablehlo.xor %146, %149 : tensor<3xui32>
  // CPU-NEXT:    %151 = stablehlo.add %146, %150 : tensor<3xui32>
  // CPU-NEXT:    %152 = stablehlo.shift_left %150, %c_10 : tensor<3xui32>
  // CPU-NEXT:    %153 = stablehlo.shift_right_logical %150, %26 : tensor<3xui32>
  // CPU-NEXT:    %154 = stablehlo.or %152, %153 : tensor<3xui32>
  // CPU-NEXT:    %155 = stablehlo.xor %151, %154 : tensor<3xui32>
  // CPU-NEXT:    %156 = stablehlo.add %151, %155 : tensor<3xui32>
  // CPU-NEXT:    %157 = stablehlo.shift_left %155, %c_9 : tensor<3xui32>
  // CPU-NEXT:    %158 = stablehlo.shift_right_logical %155, %32 : tensor<3xui32>
  // CPU-NEXT:    %159 = stablehlo.or %157, %158 : tensor<3xui32>
  // CPU-NEXT:    %160 = stablehlo.xor %156, %159 : tensor<3xui32>
  // CPU-NEXT:    %161 = stablehlo.add %156, %160 : tensor<3xui32>
  // CPU-NEXT:    %162 = stablehlo.shift_left %160, %c_8 : tensor<3xui32>
  // CPU-NEXT:    %163 = stablehlo.shift_right_logical %160, %38 : tensor<3xui32>
  // CPU-NEXT:    %164 = stablehlo.or %162, %163 : tensor<3xui32>
  // CPU-NEXT:    %165 = stablehlo.xor %161, %164 : tensor<3xui32>
  // CPU-NEXT:    %166 = stablehlo.add %161, %14 : tensor<3xui32>
  // CPU-NEXT:    %167 = stablehlo.add %165, %143 : tensor<3xui32>
  // CPU-NEXT:    %168 = stablehlo.add %167, %c_7 : tensor<3xui32>
  // CPU-NEXT:    %169 = stablehlo.add %166, %168 : tensor<3xui32>
  // CPU-NEXT:    %170 = stablehlo.shift_left %168, %c_6 : tensor<3xui32>
  // CPU-NEXT:    %171 = stablehlo.shift_right_logical %168, %47 : tensor<3xui32>
  // CPU-NEXT:    %172 = stablehlo.or %170, %171 : tensor<3xui32>
  // CPU-NEXT:    %173 = stablehlo.xor %169, %172 : tensor<3xui32>
  // CPU-NEXT:    %174 = stablehlo.add %169, %173 : tensor<3xui32>
  // CPU-NEXT:    %175 = stablehlo.shift_left %173, %c_5 : tensor<3xui32>
  // CPU-NEXT:    %176 = stablehlo.shift_right_logical %173, %53 : tensor<3xui32>
  // CPU-NEXT:    %177 = stablehlo.or %175, %176 : tensor<3xui32>
  // CPU-NEXT:    %178 = stablehlo.xor %174, %177 : tensor<3xui32>
  // CPU-NEXT:    %179 = stablehlo.add %174, %178 : tensor<3xui32>
  // CPU-NEXT:    %180 = stablehlo.shift_left %178, %c_4 : tensor<3xui32>
  // CPU-NEXT:    %181 = stablehlo.shift_right_logical %178, %59 : tensor<3xui32>
  // CPU-NEXT:    %182 = stablehlo.or %180, %181 : tensor<3xui32>
  // CPU-NEXT:    %183 = stablehlo.xor %179, %182 : tensor<3xui32>
  // CPU-NEXT:    %184 = stablehlo.add %179, %183 : tensor<3xui32>
  // CPU-NEXT:    %185 = stablehlo.shift_left %183, %c_3 : tensor<3xui32>
  // CPU-NEXT:    %186 = stablehlo.shift_right_logical %183, %65 : tensor<3xui32>
  // CPU-NEXT:    %187 = stablehlo.or %185, %186 : tensor<3xui32>
  // CPU-NEXT:    %188 = stablehlo.xor %184, %187 : tensor<3xui32>
  // CPU-NEXT:    %189 = stablehlo.add %184, %143 : tensor<3xui32>
  // CPU-NEXT:    %190 = stablehlo.add %188, %13 : tensor<3xui32>
  // CPU-NEXT:    %191 = stablehlo.add %190, %c_2 : tensor<3xui32>
  // CPU-NEXT:    %192 = stablehlo.add %189, %191 : tensor<3xui32>
  // CPU-NEXT:    %193 = stablehlo.shift_left %191, %c_12 : tensor<3xui32>
  // CPU-NEXT:    %194 = stablehlo.shift_right_logical %191, %20 : tensor<3xui32>
  // CPU-NEXT:    %195 = stablehlo.or %193, %194 : tensor<3xui32>
  // CPU-NEXT:    %196 = stablehlo.xor %192, %195 : tensor<3xui32>
  // CPU-NEXT:    %197 = stablehlo.add %192, %196 : tensor<3xui32>
  // CPU-NEXT:    %198 = stablehlo.shift_left %196, %c_10 : tensor<3xui32>
  // CPU-NEXT:    %199 = stablehlo.shift_right_logical %196, %26 : tensor<3xui32>
  // CPU-NEXT:    %200 = stablehlo.or %198, %199 : tensor<3xui32>
  // CPU-NEXT:    %201 = stablehlo.xor %197, %200 : tensor<3xui32>
  // CPU-NEXT:    %202 = stablehlo.add %197, %201 : tensor<3xui32>
  // CPU-NEXT:    %203 = stablehlo.shift_left %201, %c_9 : tensor<3xui32>
  // CPU-NEXT:    %204 = stablehlo.shift_right_logical %201, %32 : tensor<3xui32>
  // CPU-NEXT:    %205 = stablehlo.or %203, %204 : tensor<3xui32>
  // CPU-NEXT:    %206 = stablehlo.xor %202, %205 : tensor<3xui32>
  // CPU-NEXT:    %207 = stablehlo.add %202, %206 : tensor<3xui32>
  // CPU-NEXT:    %208 = stablehlo.shift_left %206, %c_8 : tensor<3xui32>
  // CPU-NEXT:    %209 = stablehlo.shift_right_logical %206, %38 : tensor<3xui32>
  // CPU-NEXT:    %210 = stablehlo.or %208, %209 : tensor<3xui32>
  // CPU-NEXT:    %211 = stablehlo.xor %207, %210 : tensor<3xui32>
  // CPU-NEXT:    %212 = stablehlo.add %207, %13 : tensor<3xui32>
  // CPU-NEXT:    %213 = stablehlo.add %211, %14 : tensor<3xui32>
  // CPU-NEXT:    %214 = stablehlo.add %213, %c_1 : tensor<3xui32>
  // CPU-NEXT:    %215 = stablehlo.add %212, %214 : tensor<3xui32>
  // CPU-NEXT:    %216 = stablehlo.shift_left %214, %c_6 : tensor<3xui32>
  // CPU-NEXT:    %217 = stablehlo.shift_right_logical %214, %47 : tensor<3xui32>
  // CPU-NEXT:    %218 = stablehlo.or %216, %217 : tensor<3xui32>
  // CPU-NEXT:    %219 = stablehlo.xor %215, %218 : tensor<3xui32>
  // CPU-NEXT:    %220 = stablehlo.add %215, %219 : tensor<3xui32>
  // CPU-NEXT:    %221 = stablehlo.shift_left %219, %c_5 : tensor<3xui32>
  // CPU-NEXT:    %222 = stablehlo.shift_right_logical %219, %53 : tensor<3xui32>
  // CPU-NEXT:    %223 = stablehlo.or %221, %222 : tensor<3xui32>
  // CPU-NEXT:    %224 = stablehlo.xor %220, %223 : tensor<3xui32>
  // CPU-NEXT:    %225 = stablehlo.add %220, %224 : tensor<3xui32>
  // CPU-NEXT:    %226 = stablehlo.shift_left %224, %c_4 : tensor<3xui32>
  // CPU-NEXT:    %227 = stablehlo.shift_right_logical %224, %59 : tensor<3xui32>
  // CPU-NEXT:    %228 = stablehlo.or %226, %227 : tensor<3xui32>
  // CPU-NEXT:    %229 = stablehlo.xor %225, %228 : tensor<3xui32>
  // CPU-NEXT:    %230 = stablehlo.add %225, %229 : tensor<3xui32>
  // CPU-NEXT:    %231 = stablehlo.shift_left %229, %c_3 : tensor<3xui32>
  // CPU-NEXT:    %232 = stablehlo.shift_right_logical %229, %65 : tensor<3xui32>
  // CPU-NEXT:    %233 = stablehlo.or %231, %232 : tensor<3xui32>
  // CPU-NEXT:    %234 = stablehlo.xor %230, %233 : tensor<3xui32>
  // CPU-NEXT:    %235 = stablehlo.add %230, %14 : tensor<3xui32>
  // CPU-NEXT:    %236 = stablehlo.add %234, %143 : tensor<3xui32>
  // CPU-NEXT:    %237 = stablehlo.add %236, %c_0 : tensor<3xui32>
  // CPU-NEXT:    %238 = stablehlo.add %235, %237 : tensor<3xui32>
  // CPU-NEXT:    %239 = stablehlo.shift_left %237, %c_12 : tensor<3xui32>
  // CPU-NEXT:    %240 = stablehlo.shift_right_logical %237, %20 : tensor<3xui32>
  // CPU-NEXT:    %241 = stablehlo.or %239, %240 : tensor<3xui32>
  // CPU-NEXT:    %242 = stablehlo.xor %238, %241 : tensor<3xui32>
  // CPU-NEXT:    %243 = stablehlo.add %238, %242 : tensor<3xui32>
  // CPU-NEXT:    %244 = stablehlo.shift_left %242, %c_10 : tensor<3xui32>
  // CPU-NEXT:    %245 = stablehlo.shift_right_logical %242, %26 : tensor<3xui32>
  // CPU-NEXT:    %246 = stablehlo.or %244, %245 : tensor<3xui32>
  // CPU-NEXT:    %247 = stablehlo.xor %243, %246 : tensor<3xui32>
  // CPU-NEXT:    %248 = stablehlo.add %243, %247 : tensor<3xui32>
  // CPU-NEXT:    %249 = stablehlo.shift_left %247, %c_9 : tensor<3xui32>
  // CPU-NEXT:    %250 = stablehlo.shift_right_logical %247, %32 : tensor<3xui32>
  // CPU-NEXT:    %251 = stablehlo.or %249, %250 : tensor<3xui32>
  // CPU-NEXT:    %252 = stablehlo.xor %248, %251 : tensor<3xui32>
  // CPU-NEXT:    %253 = stablehlo.add %248, %252 : tensor<3xui32>
  // CPU-NEXT:    %254 = stablehlo.shift_left %252, %c_8 : tensor<3xui32>
  // CPU-NEXT:    %255 = stablehlo.shift_right_logical %252, %38 : tensor<3xui32>
  // CPU-NEXT:    %256 = stablehlo.or %254, %255 : tensor<3xui32>
  // CPU-NEXT:    %257 = stablehlo.xor %253, %256 : tensor<3xui32>
  // CPU-NEXT:    %258 = stablehlo.add %253, %143 : tensor<3xui32>
  // CPU-NEXT:    %259 = stablehlo.add %257, %13 : tensor<3xui32>
  // CPU-NEXT:    %260 = stablehlo.add %259, %c : tensor<3xui32>
  // CPU-NEXT:    %261 = stablehlo.slice %139 [0:1] : (tensor<3xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %262 = stablehlo.slice %141 [0:1] : (tensor<3xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %263 = stablehlo.slice %258 [0:1] : (tensor<3xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %264 = stablehlo.slice %260 [0:1] : (tensor<3xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %265 = stablehlo.concatenate %261, %262, %263, %264, dim = 0 : (tensor<1xui32>, tensor<1xui32>, tensor<1xui32>, tensor<1xui32>) -> tensor<4xui32>
  // CPU-NEXT:    %266 = stablehlo.reshape %265 : (tensor<4xui32>) -> tensor<2x2xui32>
  // CPU-NEXT:    %267 = stablehlo.bitcast_convert %266 : (tensor<2x2xui32>) -> tensor<2xui64>
  // CPU-NEXT:    %268 = stablehlo.slice %139 [1:2] : (tensor<3xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %269 = stablehlo.slice %141 [1:2] : (tensor<3xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %270 = stablehlo.slice %258 [1:2] : (tensor<3xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %271 = stablehlo.slice %260 [1:2] : (tensor<3xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %272 = stablehlo.concatenate %268, %269, %270, %271, dim = 0 : (tensor<1xui32>, tensor<1xui32>, tensor<1xui32>, tensor<1xui32>) -> tensor<4xui32>
  // CPU-NEXT:    %273 = stablehlo.reshape %272 : (tensor<4xui32>) -> tensor<2x2xui32>
  // CPU-NEXT:    %274 = stablehlo.bitcast_convert %273 : (tensor<2x2xui32>) -> tensor<2xui64>
  // CPU-NEXT:    %275 = stablehlo.slice %139 [2:3] : (tensor<3xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %276 = stablehlo.slice %141 [2:3] : (tensor<3xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %277 = stablehlo.slice %258 [2:3] : (tensor<3xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %278 = stablehlo.slice %260 [2:3] : (tensor<3xui32>) -> tensor<1xui32>
  // CPU-NEXT:    %279 = stablehlo.concatenate %275, %276, %277, %278, dim = 0 : (tensor<1xui32>, tensor<1xui32>, tensor<1xui32>, tensor<1xui32>) -> tensor<4xui32>
  // CPU-NEXT:    %280 = stablehlo.reshape %279 : (tensor<4xui32>) -> tensor<2x2xui32>
  // CPU-NEXT:    %281 = stablehlo.bitcast_convert %280 : (tensor<2x2xui32>) -> tensor<2xui64>
  // CPU-NEXT:    return %267, %274, %281 : tensor<2xui64>, tensor<2xui64>, tensor<2xui64>
  // CPU-NEXT:  }
  func.func @test_split_3(%rng: tensor<2xui64>) -> (tensor<2xui64>, tensor<2xui64>, tensor<2xui64>) {
    %key1, %key2, %key3 = enzyme.randomSplit %rng : (tensor<2xui64>) -> (tensor<2xui64>, tensor<2xui64>, tensor<2xui64>)
    return %key1, %key2, %key3 : tensor<2xui64>, tensor<2xui64>, tensor<2xui64>
  }
}
