// RUN: enzymexlamlir-opt %s --multi-float-conversion="source-type=f64 target-type=f32 concat-dimension=first" | FileCheck %s

func.func @divide_zero(%arg0: tensor<2xf64>) -> tensor<2xf64> {
  %cst = stablehlo.constant dense<0.000000e+00> : tensor<2xf64>
  %0 = stablehlo.divide %arg0, %cst : tensor<2xf64>
  return %0 : tensor<2xf64>
}
// CHECK: func @divide_zero(%arg0: tensor<2xf64>) -> tensor<2xf64> {
// CHECK: %[[C0:.*]] = stablehlo.convert %arg0 : (tensor<2xf64>) -> tensor<2xf32>
// CHECK: %[[C1:.*]] = stablehlo.convert %[[C0]] : (tensor<2xf32>) -> tensor<2xf64>
// CHECK: %[[S0:.*]] = stablehlo.subtract %arg0, %[[C1]] : tensor<2xf64>
// CHECK: %[[C2:.*]] = stablehlo.convert %[[S0]] : (tensor<2xf64>) -> tensor<2xf32>
// CHECK: %[[R1:.*]] = stablehlo.reshape %[[C0]] : (tensor<2xf32>) -> tensor<1x2xf32>
// CHECK: %[[R2:.*]] = stablehlo.reshape %[[C2]] : (tensor<2xf32>) -> tensor<1x2xf32>
// CHECK: %[[CAT:.*]] = stablehlo.concatenate %[[R1]], %[[R2]], dim = 0 : (tensor<1x2xf32>, tensor<1x2xf32>) -> tensor<2x2xf32>
// CHECK-DAG: %[[ZERO:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<1x2xf32>
// CHECK-DAG: %[[ZERO2:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<1x2xf32>
// CHECK: %[[CAT2:.*]] = stablehlo.concatenate %[[ZERO]], %[[ZERO2]], dim = 0 : (tensor<1x2xf32>, tensor<1x2xf32>) -> tensor<2x2xf32>
// CHECK: %[[X_HI:.*]] = stablehlo.slice %[[CAT]] [0:1, 0:2] : (tensor<2x2xf32>) -> tensor<1x2xf32>
// CHECK: %[[X_LO:.*]] = stablehlo.slice %[[CAT]] [1:2, 0:2] : (tensor<2x2xf32>) -> tensor<1x2xf32>
// CHECK: %[[ONE:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<1x2xf32>
// CHECK: %[[U:.*]] = stablehlo.divide %[[ONE]], %[[ZERO]] : tensor<1x2xf32>
// CHECK: %[[ZERO3:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<1x2xf32>
// CHECK: %[[Q_HI:.*]] = stablehlo.multiply %[[X_HI]], %[[U]] : tensor<1x2xf32>
// CHECK: %[[CST3:.*]] = stablehlo.constant dense<4.097000e+03> : tensor<1x2xf32>
// CHECK: %[[X_HI_BIG:.*]] = stablehlo.multiply %[[X_HI]], %[[CST3]] : tensor<1x2xf32>
// CHECK: %[[T:.*]] = stablehlo.subtract %[[X_HI_BIG]], %[[X_HI]] : tensor<1x2xf32>
// CHECK: %[[X_HI_HI:.*]] = stablehlo.subtract %[[X_HI_BIG]], %[[T]] : tensor<1x2xf32>
// CHECK: %[[X_HI_LO:.*]] = stablehlo.subtract %[[X_HI]], %[[X_HI_HI]] : tensor<1x2xf32>
// CHECK: %[[CST4:.*]] = stablehlo.constant dense<4.097000e+03> : tensor<1x2xf32>
// CHECK: %[[U_BIG:.*]] = stablehlo.multiply %[[U]], %[[CST4]] : tensor<1x2xf32>
// CHECK: %[[T_U:.*]] = stablehlo.subtract %[[U_BIG]], %[[U]] : tensor<1x2xf32>
// CHECK: %[[U_HI:.*]] = stablehlo.subtract %[[U_BIG]], %[[T_U]] : tensor<1x2xf32>
// CHECK: %[[U_LO:.*]] = stablehlo.subtract %[[U]], %[[U_HI]] : tensor<1x2xf32>
// CHECK: %[[P0:.*]] = stablehlo.multiply %[[X_HI_HI]], %[[U_HI]] : tensor<1x2xf32>
// CHECK: %[[P1:.*]] = stablehlo.multiply %[[X_HI_HI]], %[[U_LO]] : tensor<1x2xf32>
// CHECK: %[[P2:.*]] = stablehlo.multiply %[[X_HI_LO]], %[[U_HI]] : tensor<1x2xf32>
// CHECK: %[[P3:.*]] = stablehlo.multiply %[[X_HI_LO]], %[[U_LO]] : tensor<1x2xf32>
// CHECK: %[[E0:.*]] = stablehlo.subtract %[[P0]], %[[Q_HI]] : tensor<1x2xf32>
// CHECK: %[[E1:.*]] = stablehlo.add %[[E0]], %[[P1]] : tensor<1x2xf32>
// CHECK: %[[E2:.*]] = stablehlo.add %[[E1]], %[[P2]] : tensor<1x2xf32>
// CHECK: %[[E3:.*]] = stablehlo.add %[[E2]], %[[P3]] : tensor<1x2xf32>
// CHECK-DAG: %[[MUL_X_LO:.*]] = stablehlo.multiply %[[X_LO]], %[[U]] : tensor<1x2xf32>
// CHECK-DAG: %[[ZERO_MUL:.*]] = stablehlo.multiply %[[X_HI]], %[[ZERO3]] : tensor<1x2xf32>
// CHECK: %[[L_TUM:.*]] = stablehlo.add %[[ZERO_MUL]], %[[MUL_X_LO]] : tensor<1x2xf32>
// CHECK: %[[L_TUM2:.*]] = stablehlo.add %[[E3]], %[[L_TUM]] : tensor<1x2xf32>
// CHECK: %[[Q_HI_FINAL:.*]] = stablehlo.add %[[Q_HI]], %[[L_TUM2]] : tensor<1x2xf32>
// CHECK: %[[RES:.*]] = stablehlo.subtract %[[Q_HI_FINAL]], %[[Q_HI]] : tensor<1x2xf32>
// CHECK: %[[CORR:.*]] = stablehlo.subtract %[[L_TUM2]], %[[RES]] : tensor<1x2xf32>
// CHECK: %{{.*}} = stablehlo.constant dense<4.097000e+03>
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.constant dense<4.097000e+03>
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.negate
// CHECK: %{{.*}} = stablehlo.negate
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.constant dense<4.097000e+03>
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.constant dense<4.097000e+03>
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.multiply
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.negate
// CHECK: %{{.*}} = stablehlo.negate
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.add
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.subtract
// CHECK: %{{.*}} = stablehlo.concatenate
// CHECK: %{{.*}} = stablehlo.convert
// CHECK: %[[FINAL:.*]] = stablehlo.reduce
// CHECK: return %[[FINAL]] : tensor<2xf64>
