// RUN: enzymexlamlir-opt --multi-float-conversion="source-type=f64 target-type=f32 concat-dimension=first" %s | FileCheck %s
// RUN: enzymexlamlir-opt --multi-float-conversion="source-type=f64 target-type=f32 concat-dimension=last" %s | FileCheck %s


func.func @log_test(%arg0: tensor<f64>) -> tensor<f64> {
  %0 = stablehlo.log %arg0 : tensor<f64>
  return %0 : tensor<f64>
}

func.func @main() attributes {enzyme.no_multifloat} {
  // Test 1.0 -> 0.0
  %c1 = stablehlo.constant dense<1.0> : tensor<f64>
  %e1 = stablehlo.constant dense<0.0> : tensor<f64>
  %r1 = func.call @log_test(%c1) : (tensor<f64>) -> tensor<f64>
  "check.expect_close"(%r1, %e1) {max_ulp_difference = 0 : ui64} : (tensor<f64>, tensor<f64>) -> ()

  // Test 0.0 -> -inf
  %c0 = stablehlo.constant dense<0.0> : tensor<f64>
  %e0 = stablehlo.constant dense<0xFFF0000000000000> : tensor<f64> // -inf
  %r0 = func.call @log_test(%c0) : (tensor<f64>) -> tensor<f64>
  "check.expect_close"(%r0, %e0) {max_ulp_difference = 0 : ui64} : (tensor<f64>, tensor<f64>) -> ()

  // Test -1.0 -> NaN
  %cn1 = stablehlo.constant dense<-1.0> : tensor<f64>
  %r2 = func.call @log_test(%cn1) : (tensor<f64>) -> tensor<f64>
  // We can't easily check for NaN with expect_close, but we can check if it is not equal to itself?
  // Or we can just assume it works if it doesn't crash!
  // Let's just check it doesn't crash!

  // Test +inf -> +inf
  %cinf = stablehlo.constant dense<0x7FF0000000000000> : tensor<f64> // +inf
  %r3 = func.call @log_test(%cinf) : (tensor<f64>) -> tensor<f64>
  "check.expect_close"(%r3, %cinf) {max_ulp_difference = 0 : ui64} : (tensor<f64>, tensor<f64>) -> ()

  // Exact test for 2.0
  %c2 = stablehlo.constant dense<2.0> : tensor<f64>
  %e2_mf = stablehlo.constant dense<0.6931471805599454> : tensor<f64> // Exact result from test log
  %r4 = func.call @log_test(%c2) : (tensor<f64>) -> tensor<f64>
  "check.expect_close"(%r4, %e2_mf) {max_ulp_difference = 1 : ui64} : (tensor<f64>, tensor<f64>) -> ()

  %e2_f64 = stablehlo.constant dense<0.6931471805599453> : tensor<f64> // Exact f64 result
  "check.expect_close"(%r4, %e2_f64) {max_ulp_difference = 100 : ui64} : (tensor<f64>, tensor<f64>) -> ()

  return
}

// CHECK-LABEL: module {
// CHECK:   func.func @log_test(%arg0: tensor<f64>) -> tensor<f64> {
// CHECK:     %0 = stablehlo.convert %arg0 : (tensor<f64>) -> tensor<f32>
// CHECK:     %1 = stablehlo.convert %0 : (tensor<f32>) -> tensor<f64>
// CHECK:     %2 = stablehlo.subtract %arg0, %1 : tensor<f64>
// CHECK:     %3 = stablehlo.convert %2 : (tensor<f64>) -> tensor<f32>
// CHECK:     %4 = stablehlo.reshape %0 : (tensor<f32>) -> tensor<1xf32>
// CHECK:     %5 = stablehlo.reshape %3 : (tensor<f32>) -> tensor<1xf32>
// CHECK:     %6 = stablehlo.concatenate %4, %5, dim = 0 : (tensor<1xf32>, tensor<1xf32>) -> tensor<2xf32>
// CHECK:     %7 = stablehlo.slice %6 {{\[}}0:1{{\]}} : (tensor<2xf32>) -> tensor<1xf32>
// CHECK:     %8 = stablehlo.slice %6 {{\[}}1:2{{\]}} : (tensor<2xf32>) -> tensor<1xf32>
// CHECK:     %9 = stablehlo.bitcast_convert %7 : (tensor<1xf32>) -> tensor<1xi32>
// CHECK:     %c = stablehlo.constant dense<2139095040> : tensor<1xi32>
// CHECK:     %10 = stablehlo.and %9, %c : tensor<1xi32>
// CHECK:     %c_0 = stablehlo.constant dense<23> : tensor<1xi32>
// CHECK:     %11 = stablehlo.shift_right_logical %10, %c_0 : tensor<1xi32>
// CHECK:     %c_1 = stablehlo.constant dense<127> : tensor<1xi32>
// CHECK:     %12 = stablehlo.subtract %11, %c_1 : tensor<1xi32>
// CHECK:     %c_2 = stablehlo.constant dense<127> : tensor<1xi32>
// CHECK:     %13 = stablehlo.subtract %c_2, %12 : tensor<1xi32>
// CHECK:     %c_3 = stablehlo.constant dense<23> : tensor<1xi32>
// CHECK:     %14 = stablehlo.shift_left %13, %c_3 : tensor<1xi32>
// CHECK:     %15 = stablehlo.bitcast_convert %14 : (tensor<1xi32>) -> tensor<1xf32>
// CHECK:     %16 = stablehlo.multiply %7, %15 : tensor<1xf32>
// CHECK:     %17 = stablehlo.multiply %8, %15 : tensor<1xf32>
// CHECK:     %c_4 = stablehlo.constant dense<18> : tensor<1xi32>
// CHECK:     %18 = stablehlo.shift_right_logical %9, %c_4 : tensor<1xi32>
// CHECK:     %c_5 = stablehlo.constant dense<31> : tensor<1xi32>
// CHECK:     %19 = stablehlo.and %18, %c_5 : tensor<1xi32>
// CHECK:     %cst = stablehlo.constant dense<1.015625> : tensor<1xf32>
// CHECK:     %cst_6 = stablehlo.constant dense<1.046875> : tensor<1xf32>
// CHECK:     %cst_7 = stablehlo.constant dense<1.078125> : tensor<1xf32>
// CHECK:     %cst_8 = stablehlo.constant dense<1.109375> : tensor<1xf32>
// CHECK:     %cst_9 = stablehlo.constant dense<1.140625> : tensor<1xf32>
// CHECK:     %cst_10 = stablehlo.constant dense<1.171875> : tensor<1xf32>
// CHECK:     %cst_11 = stablehlo.constant dense<1.203125> : tensor<1xf32>
// CHECK:     %cst_12 = stablehlo.constant dense<1.234375> : tensor<1xf32>
// CHECK:     %cst_13 = stablehlo.constant dense<1.265625> : tensor<1xf32>
// CHECK:     %cst_14 = stablehlo.constant dense<1.296875> : tensor<1xf32>
// CHECK:     %cst_15 = stablehlo.constant dense<1.328125> : tensor<1xf32>
// CHECK:     %cst_16 = stablehlo.constant dense<1.359375> : tensor<1xf32>
// CHECK:     %cst_17 = stablehlo.constant dense<1.390625> : tensor<1xf32>
// CHECK:     %cst_18 = stablehlo.constant dense<1.421875> : tensor<1xf32>
// CHECK:     %cst_19 = stablehlo.constant dense<1.453125> : tensor<1xf32>
// CHECK:     %cst_20 = stablehlo.constant dense<1.484375> : tensor<1xf32>
// CHECK:     %cst_21 = stablehlo.constant dense<1.515625> : tensor<1xf32>
// CHECK:     %cst_22 = stablehlo.constant dense<1.546875> : tensor<1xf32>
// CHECK:     %cst_23 = stablehlo.constant dense<1.578125> : tensor<1xf32>
// CHECK:     %cst_24 = stablehlo.constant dense<1.609375> : tensor<1xf32>
// CHECK:     %cst_25 = stablehlo.constant dense<1.640625> : tensor<1xf32>
// CHECK:     %cst_26 = stablehlo.constant dense<1.671875> : tensor<1xf32>
// CHECK:     %cst_27 = stablehlo.constant dense<1.703125> : tensor<1xf32>
// CHECK:     %cst_28 = stablehlo.constant dense<1.734375> : tensor<1xf32>
// CHECK:     %cst_29 = stablehlo.constant dense<1.765625> : tensor<1xf32>
// CHECK:     %cst_30 = stablehlo.constant dense<1.796875> : tensor<1xf32>
// CHECK:     %cst_31 = stablehlo.constant dense<1.828125> : tensor<1xf32>
// CHECK:     %cst_32 = stablehlo.constant dense<1.859375> : tensor<1xf32>
// CHECK:     %cst_33 = stablehlo.constant dense<1.890625> : tensor<1xf32>
// CHECK:     %cst_34 = stablehlo.constant dense<1.921875> : tensor<1xf32>
// CHECK:     %cst_35 = stablehlo.constant dense<1.953125> : tensor<1xf32>
// CHECK:     %cst_36 = stablehlo.constant dense<1.984375> : tensor<1xf32>
// CHECK:     %c_37 = stablehlo.constant dense<1> : tensor<1xi32>
// CHECK:     %20 = stablehlo.and %19, %c_37 : tensor<1xi32>
// CHECK:     %c_38 = stablehlo.constant dense<0> : tensor<1xi32>
// CHECK:     %21 = stablehlo.compare NE, %20, %c_38 : (tensor<1xi32>, tensor<1xi32>) -> tensor<1xi1>
// CHECK:     %22 = stablehlo.select %21, %cst_6, %cst : tensor<1xi1>, tensor<1xf32>
// CHECK:     %23 = stablehlo.select %21, %cst_8, %cst_7 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %24 = stablehlo.select %21, %cst_10, %cst_9 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %25 = stablehlo.select %21, %cst_12, %cst_11 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %26 = stablehlo.select %21, %cst_14, %cst_13 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %27 = stablehlo.select %21, %cst_16, %cst_15 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %28 = stablehlo.select %21, %cst_18, %cst_17 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %29 = stablehlo.select %21, %cst_20, %cst_19 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %30 = stablehlo.select %21, %cst_22, %cst_21 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %31 = stablehlo.select %21, %cst_24, %cst_23 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %32 = stablehlo.select %21, %cst_26, %cst_25 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %33 = stablehlo.select %21, %cst_28, %cst_27 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %34 = stablehlo.select %21, %cst_30, %cst_29 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %35 = stablehlo.select %21, %cst_32, %cst_31 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %36 = stablehlo.select %21, %cst_34, %cst_33 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %37 = stablehlo.select %21, %cst_36, %cst_35 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %c_39 = stablehlo.constant dense<2> : tensor<1xi32>
// CHECK:     %38 = stablehlo.and %19, %c_39 : tensor<1xi32>
// CHECK:     %c_40 = stablehlo.constant dense<0> : tensor<1xi32>
// CHECK:     %39 = stablehlo.compare NE, %38, %c_40 : (tensor<1xi32>, tensor<1xi32>) -> tensor<1xi1>
// CHECK:     %40 = stablehlo.select %39, %23, %22 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %41 = stablehlo.select %39, %25, %24 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %42 = stablehlo.select %39, %27, %26 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %43 = stablehlo.select %39, %29, %28 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %44 = stablehlo.select %39, %31, %30 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %45 = stablehlo.select %39, %33, %32 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %46 = stablehlo.select %39, %35, %34 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %47 = stablehlo.select %39, %37, %36 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %c_41 = stablehlo.constant dense<4> : tensor<1xi32>
// CHECK:     %48 = stablehlo.and %19, %c_41 : tensor<1xi32>
// CHECK:     %c_42 = stablehlo.constant dense<0> : tensor<1xi32>
// CHECK:     %49 = stablehlo.compare NE, %48, %c_42 : (tensor<1xi32>, tensor<1xi32>) -> tensor<1xi1>
// CHECK:     %50 = stablehlo.select %49, %41, %40 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %51 = stablehlo.select %49, %43, %42 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %52 = stablehlo.select %49, %45, %44 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %53 = stablehlo.select %49, %47, %46 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %c_43 = stablehlo.constant dense<8> : tensor<1xi32>
// CHECK:     %54 = stablehlo.and %19, %c_43 : tensor<1xi32>
// CHECK:     %c_44 = stablehlo.constant dense<0> : tensor<1xi32>
// CHECK:     %55 = stablehlo.compare NE, %54, %c_44 : (tensor<1xi32>, tensor<1xi32>) -> tensor<1xi1>
// CHECK:     %56 = stablehlo.select %55, %51, %50 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %57 = stablehlo.select %55, %53, %52 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %c_45 = stablehlo.constant dense<16> : tensor<1xi32>
// CHECK:     %58 = stablehlo.and %19, %c_45 : tensor<1xi32>
// CHECK:     %c_46 = stablehlo.constant dense<0> : tensor<1xi32>
// CHECK:     %59 = stablehlo.compare NE, %58, %c_46 : (tensor<1xi32>, tensor<1xi32>) -> tensor<1xi1>
// CHECK:     %60 = stablehlo.select %59, %57, %56 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %cst_47 = stablehlo.constant dense<0.000000e+00> : tensor<1xf32>
// CHECK:     %cst_48 = stablehlo.constant dense<0.0223678127> : tensor<1xf32>
// CHECK:     %cst_49 = stablehlo.constant dense<0.0660891905> : tensor<1xf32>
// CHECK:     %cst_50 = stablehlo.constant dense<0.108524457> : tensor<1xf32>
// CHECK:     %cst_51 = stablehlo.constant dense<0.149747118> : tensor<1xf32>
// CHECK:     %cst_52 = stablehlo.constant dense<0.189824566> : tensor<1xf32>
// CHECK:     %cst_53 = stablehlo.constant dense<0.228818685> : tensor<1xf32>
// CHECK:     %cst_54 = stablehlo.constant dense<0.266786546> : tensor<1xf32>
// CHECK:     %cst_55 = stablehlo.constant dense<0.303780735> : tensor<1xf32>
// CHECK:     %cst_56 = stablehlo.constant dense<3.398500e-01> : tensor<1xf32>
// CHECK:     %cst_57 = stablehlo.constant dense<0.375039428> : tensor<1xf32>
// CHECK:     %cst_58 = stablehlo.constant dense<0.409390926> : tensor<1xf32>
// CHECK:     %cst_59 = stablehlo.constant dense<0.442943484> : tensor<1xf32>
// CHECK:     %cst_60 = stablehlo.constant dense<0.475733429> : tensor<1xf32>
// CHECK:     %cst_61 = stablehlo.constant dense<0.507794619> : tensor<1xf32>
// CHECK:     %cst_62 = stablehlo.constant dense<0.539158821> : tensor<1xf32>
// CHECK:     %cst_63 = stablehlo.constant dense<0.56985563> : tensor<1xf32>
// CHECK:     %cst_64 = stablehlo.constant dense<0.599912822> : tensor<1xf32>
// CHECK:     %cst_65 = stablehlo.constant dense<0.629356623> : tensor<1xf32>
// CHECK:     %cst_66 = stablehlo.constant dense<0.65821147> : tensor<1xf32>
// CHECK:     %cst_67 = stablehlo.constant dense<0.686500549> : tensor<1xf32>
// CHECK:     %cst_68 = stablehlo.constant dense<0.714245498> : tensor<1xf32>
// CHECK:     %cst_69 = stablehlo.constant dense<0.741466999> : tensor<1xf32>
// CHECK:     %cst_70 = stablehlo.constant dense<0.768184304> : tensor<1xf32>
// CHECK:     %cst_71 = stablehlo.constant dense<0.794415891> : tensor<1xf32>
// CHECK:     %cst_72 = stablehlo.constant dense<0.820178985> : tensor<1xf32>
// CHECK:     %cst_73 = stablehlo.constant dense<0.845490038> : tensor<1xf32>
// CHECK:     %cst_74 = stablehlo.constant dense<0.870364725> : tensor<1xf32>
// CHECK:     %cst_75 = stablehlo.constant dense<0.894817769> : tensor<1xf32>
// CHECK:     %cst_76 = stablehlo.constant dense<0.918863236> : tensor<1xf32>
// CHECK:     %cst_77 = stablehlo.constant dense<0.942514479> : tensor<1xf32>
// CHECK:     %cst_78 = stablehlo.constant dense<0.965784311> : tensor<1xf32>
// CHECK:     %cst_79 = stablehlo.constant dense<0.988684713> : tensor<1xf32>
// CHECK:     %c_80 = stablehlo.constant dense<1> : tensor<1xi32>
// CHECK:     %61 = stablehlo.and %19, %c_80 : tensor<1xi32>
// CHECK:     %c_81 = stablehlo.constant dense<0> : tensor<1xi32>
// CHECK:     %62 = stablehlo.compare NE, %61, %c_81 : (tensor<1xi32>, tensor<1xi32>) -> tensor<1xi1>
// CHECK:     %63 = stablehlo.select %62, %cst_49, %cst_48 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %64 = stablehlo.select %62, %cst_51, %cst_50 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %65 = stablehlo.select %62, %cst_53, %cst_52 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %66 = stablehlo.select %62, %cst_55, %cst_54 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %67 = stablehlo.select %62, %cst_57, %cst_56 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %68 = stablehlo.select %62, %cst_59, %cst_58 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %69 = stablehlo.select %62, %cst_61, %cst_60 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %70 = stablehlo.select %62, %cst_63, %cst_62 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %71 = stablehlo.select %62, %cst_65, %cst_64 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %72 = stablehlo.select %62, %cst_67, %cst_66 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %73 = stablehlo.select %62, %cst_69, %cst_68 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %74 = stablehlo.select %62, %cst_71, %cst_70 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %75 = stablehlo.select %62, %cst_73, %cst_72 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %76 = stablehlo.select %62, %cst_75, %cst_74 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %77 = stablehlo.select %62, %cst_77, %cst_76 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %78 = stablehlo.select %62, %cst_79, %cst_78 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %c_82 = stablehlo.constant dense<2> : tensor<1xi32>
// CHECK:     %79 = stablehlo.and %19, %c_82 : tensor<1xi32>
// CHECK:     %c_83 = stablehlo.constant dense<0> : tensor<1xi32>
// CHECK:     %80 = stablehlo.compare NE, %79, %c_83 : (tensor<1xi32>, tensor<1xi32>) -> tensor<1xi1>
// CHECK:     %81 = stablehlo.select %80, %64, %63 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %82 = stablehlo.select %80, %66, %65 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %83 = stablehlo.select %80, %68, %67 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %84 = stablehlo.select %80, %70, %69 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %85 = stablehlo.select %80, %72, %71 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %86 = stablehlo.select %80, %74, %73 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %87 = stablehlo.select %80, %76, %75 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %88 = stablehlo.select %80, %78, %77 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %c_84 = stablehlo.constant dense<4> : tensor<1xi32>
// CHECK:     %89 = stablehlo.and %19, %c_84 : tensor<1xi32>
// CHECK:     %c_85 = stablehlo.constant dense<0> : tensor<1xi32>
// CHECK:     %90 = stablehlo.compare NE, %89, %c_85 : (tensor<1xi32>, tensor<1xi32>) -> tensor<1xi1>
// CHECK:     %91 = stablehlo.select %90, %82, %81 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %92 = stablehlo.select %90, %84, %83 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %93 = stablehlo.select %90, %86, %85 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %94 = stablehlo.select %90, %88, %87 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %c_86 = stablehlo.constant dense<8> : tensor<1xi32>
// CHECK:     %95 = stablehlo.and %19, %c_86 : tensor<1xi32>
// CHECK:     %c_87 = stablehlo.constant dense<0> : tensor<1xi32>
// CHECK:     %96 = stablehlo.compare NE, %95, %c_87 : (tensor<1xi32>, tensor<1xi32>) -> tensor<1xi1>
// CHECK:     %97 = stablehlo.select %96, %92, %91 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %98 = stablehlo.select %96, %94, %93 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %c_88 = stablehlo.constant dense<16> : tensor<1xi32>
// CHECK:     %99 = stablehlo.and %19, %c_88 : tensor<1xi32>
// CHECK:     %c_89 = stablehlo.constant dense<0> : tensor<1xi32>
// CHECK:     %100 = stablehlo.compare NE, %99, %c_89 : (tensor<1xi32>, tensor<1xi32>) -> tensor<1xi1>
// CHECK:     %101 = stablehlo.select %100, %98, %97 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %cst_90 = stablehlo.constant dense<3.35335454E-10> : tensor<1xf32>
// CHECK:     %cst_91 = stablehlo.constant dense<-8.49254764E-11> : tensor<1xf32>
// CHECK:     %cst_92 = stablehlo.constant dense<1.57952679E-10> : tensor<1xf32>
// CHECK:     %cst_93 = stablehlo.constant dense<1.15083842E-9> : tensor<1xf32>
// CHECK:     %cst_94 = stablehlo.constant dense<-7.36506189E-9> : tensor<1xf32>
// CHECK:     %cst_95 = stablehlo.constant dense<5.6795204E-9> : tensor<1xf32>
// CHECK:     %cst_96 = stablehlo.constant dense<-4.82015894E-9> : tensor<1xf32>
// CHECK:     %cst_97 = stablehlo.constant dense<1.36380711E-8> : tensor<1xf32>
// CHECK:     %cst_98 = stablehlo.constant dense<-5.60307666E-9> : tensor<1xf32>
// CHECK:     %cst_99 = stablehlo.constant dense<2.87440582E-9> : tensor<1xf32>
// CHECK:     %cst_100 = stablehlo.constant dense<9.77661773E-9> : tensor<1xf32>
// CHECK:     %cst_101 = stablehlo.constant dense<1.22576482E-8> : tensor<1xf32>
// CHECK:     %cst_102 = stablehlo.constant dense<1.77290105E-9> : tensor<1xf32>
// CHECK:     %cst_103 = stablehlo.constant dense<2.1592129E-8> : tensor<1xf32>
// CHECK:     %cst_104 = stablehlo.constant dense<-9.99792604E-9> : tensor<1xf32>
// CHECK:     %cst_105 = stablehlo.constant dense<-2.20668479E-8> : tensor<1xf32>
// CHECK:     %cst_106 = stablehlo.constant dense<1.99405754E-8> : tensor<1xf32>
// CHECK:     %cst_107 = stablehlo.constant dense<-2.61631317E-9> : tensor<1xf32>
// CHECK:     %cst_108 = stablehlo.constant dense<1.31015261E-8> : tensor<1xf32>
// CHECK:     %cst_109 = stablehlo.constant dense<-2.21331877E-8> : tensor<1xf32>
// CHECK:     %cst_110 = stablehlo.constant dense<1.94857339E-8> : tensor<1xf32>
// CHECK:     %cst_111 = stablehlo.constant dense<-1.26528077E-8> : tensor<1xf32>
// CHECK:     %cst_112 = stablehlo.constant dense<2.05395612E-8> : tensor<1xf32>
// CHECK:     %cst_113 = stablehlo.constant dense<-2.48203964E-8> : tensor<1xf32>
// CHECK:     %cst_114 = stablehlo.constant dense<-2.31805153E-8> : tensor<1xf32>
// CHECK:     %cst_115 = stablehlo.constant dense<1.25494468E-8> : tensor<1xf32>
// CHECK:     %cst_116 = stablehlo.constant dense<-6.00634786E-9> : tensor<1xf32>
// CHECK:     %cst_117 = stablehlo.constant dense<-6.21949159E-9> : tensor<1xf32>
// CHECK:     %cst_118 = stablehlo.constant dense<3.70450226E-10> : tensor<1xf32>
// CHECK:     %cst_119 = stablehlo.constant dense<2.6178931E-8> : tensor<1xf32>
// CHECK:     %cst_120 = stablehlo.constant dense<-2.66324687E-8> : tensor<1xf32>
// CHECK:     %cst_121 = stablehlo.constant dense<-2.70683191E-8> : tensor<1xf32>
// CHECK:     %c_122 = stablehlo.constant dense<1> : tensor<1xi32>
// CHECK:     %102 = stablehlo.and %19, %c_122 : tensor<1xi32>
// CHECK:     %c_123 = stablehlo.constant dense<0> : tensor<1xi32>
// CHECK:     %103 = stablehlo.compare NE, %102, %c_123 : (tensor<1xi32>, tensor<1xi32>) -> tensor<1xi1>
// CHECK:     %104 = stablehlo.select %103, %cst_91, %cst_90 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %105 = stablehlo.select %103, %cst_93, %cst_92 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %106 = stablehlo.select %103, %cst_95, %cst_94 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %107 = stablehlo.select %103, %cst_97, %cst_96 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %108 = stablehlo.select %103, %cst_99, %cst_98 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %109 = stablehlo.select %103, %cst_101, %cst_100 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %110 = stablehlo.select %103, %cst_103, %cst_102 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %111 = stablehlo.select %103, %cst_105, %cst_104 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %112 = stablehlo.select %103, %cst_107, %cst_106 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %113 = stablehlo.select %103, %cst_109, %cst_108 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %114 = stablehlo.select %103, %cst_111, %cst_110 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %115 = stablehlo.select %103, %cst_113, %cst_112 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %116 = stablehlo.select %103, %cst_115, %cst_114 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %117 = stablehlo.select %103, %cst_117, %cst_116 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %118 = stablehlo.select %103, %cst_119, %cst_118 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %119 = stablehlo.select %103, %cst_121, %cst_120 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %c_124 = stablehlo.constant dense<2> : tensor<1xi32>
// CHECK:     %120 = stablehlo.and %19, %c_124 : tensor<1xi32>
// CHECK:     %c_125 = stablehlo.constant dense<0> : tensor<1xi32>
// CHECK:     %121 = stablehlo.compare NE, %120, %c_125 : (tensor<1xi32>, tensor<1xi32>) -> tensor<1xi1>
// CHECK:     %122 = stablehlo.select %121, %105, %104 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %123 = stablehlo.select %121, %107, %106 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %124 = stablehlo.select %121, %109, %108 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %125 = stablehlo.select %121, %111, %110 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %126 = stablehlo.select %121, %113, %112 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %127 = stablehlo.select %121, %115, %114 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %128 = stablehlo.select %121, %117, %116 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %129 = stablehlo.select %121, %119, %118 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %c_126 = stablehlo.constant dense<4> : tensor<1xi32>
// CHECK:     %130 = stablehlo.and %19, %c_126 : tensor<1xi32>
// CHECK:     %c_127 = stablehlo.constant dense<0> : tensor<1xi32>
// CHECK:     %131 = stablehlo.compare NE, %130, %c_127 : (tensor<1xi32>, tensor<1xi32>) -> tensor<1xi1>
// CHECK:     %132 = stablehlo.select %131, %123, %122 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %133 = stablehlo.select %131, %125, %124 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %134 = stablehlo.select %131, %127, %126 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %135 = stablehlo.select %131, %129, %128 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %c_128 = stablehlo.constant dense<8> : tensor<1xi32>
// CHECK:     %136 = stablehlo.and %19, %c_128 : tensor<1xi32>
// CHECK:     %c_129 = stablehlo.constant dense<0> : tensor<1xi32>
// CHECK:     %137 = stablehlo.compare NE, %136, %c_129 : (tensor<1xi32>, tensor<1xi32>) -> tensor<1xi1>
// CHECK:     %138 = stablehlo.select %137, %133, %132 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %139 = stablehlo.select %137, %135, %134 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %c_130 = stablehlo.constant dense<16> : tensor<1xi32>
// CHECK:     %140 = stablehlo.and %19, %c_130 : tensor<1xi32>
// CHECK:     %c_131 = stablehlo.constant dense<0> : tensor<1xi32>
// CHECK:     %141 = stablehlo.compare NE, %140, %c_131 : (tensor<1xi32>, tensor<1xi32>) -> tensor<1xi1>
// CHECK:     %142 = stablehlo.select %141, %139, %138 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %cst_132 = stablehlo.constant dense<-1.000000e+00> : tensor<1xf32>
// CHECK:     %cst_133 = stablehlo.constant dense<0.000000e+00> : tensor<1xf32>
// CHECK:     %cst_134 = stablehlo.constant dense<1.000000e+00> : tensor<1xf32>
// CHECK:     %cst_135 = stablehlo.constant dense<0.000000e+00> : tensor<1xf32>
// CHECK:     %143 = stablehlo.add %7, %cst_132 : tensor<1xf32>
// CHECK:     %144 = stablehlo.subtract %143, %cst_132 : tensor<1xf32>
// CHECK:     %145 = stablehlo.subtract %143, %144 : tensor<1xf32>
// CHECK:     %146 = stablehlo.subtract %7, %144 : tensor<1xf32>
// CHECK:     %147 = stablehlo.subtract %cst_132, %145 : tensor<1xf32>
// CHECK:     %148 = stablehlo.add %146, %147 : tensor<1xf32>
// CHECK:     %149 = stablehlo.add %8, %cst_133 : tensor<1xf32>
// CHECK:     %150 = stablehlo.subtract %149, %cst_133 : tensor<1xf32>
// CHECK:     %151 = stablehlo.subtract %149, %150 : tensor<1xf32>
// CHECK:     %152 = stablehlo.subtract %8, %150 : tensor<1xf32>
// CHECK:     %153 = stablehlo.subtract %cst_133, %151 : tensor<1xf32>
// CHECK:     %154 = stablehlo.add %152, %153 : tensor<1xf32>
// CHECK:     %155 = stablehlo.add %143, %149 : tensor<1xf32>
// CHECK:     %156 = stablehlo.subtract %155, %143 : tensor<1xf32>
// CHECK:     %157 = stablehlo.subtract %149, %156 : tensor<1xf32>
// CHECK:     %158 = stablehlo.add %148, %154 : tensor<1xf32>
// CHECK:     %159 = stablehlo.add %158, %157 : tensor<1xf32>
// CHECK:     %160 = stablehlo.add %155, %159 : tensor<1xf32>
// CHECK:     %161 = stablehlo.subtract %160, %155 : tensor<1xf32>
// CHECK:     %162 = stablehlo.subtract %159, %161 : tensor<1xf32>
// CHECK:     %163 = stablehlo.add %7, %cst_134 : tensor<1xf32>
// CHECK:     %164 = stablehlo.subtract %163, %cst_134 : tensor<1xf32>
// CHECK:     %165 = stablehlo.subtract %163, %164 : tensor<1xf32>
// CHECK:     %166 = stablehlo.subtract %7, %164 : tensor<1xf32>
// CHECK:     %167 = stablehlo.subtract %cst_134, %165 : tensor<1xf32>
// CHECK:     %168 = stablehlo.add %166, %167 : tensor<1xf32>
// CHECK:     %169 = stablehlo.add %8, %cst_135 : tensor<1xf32>
// CHECK:     %170 = stablehlo.subtract %169, %cst_135 : tensor<1xf32>
// CHECK:     %171 = stablehlo.subtract %169, %170 : tensor<1xf32>
// CHECK:     %172 = stablehlo.subtract %8, %170 : tensor<1xf32>
// CHECK:     %173 = stablehlo.subtract %cst_135, %171 : tensor<1xf32>
// CHECK:     %174 = stablehlo.add %172, %173 : tensor<1xf32>
// CHECK:     %175 = stablehlo.add %163, %169 : tensor<1xf32>
// CHECK:     %176 = stablehlo.subtract %175, %163 : tensor<1xf32>
// CHECK:     %177 = stablehlo.subtract %169, %176 : tensor<1xf32>
// CHECK:     %178 = stablehlo.add %168, %174 : tensor<1xf32>
// CHECK:     %179 = stablehlo.add %178, %177 : tensor<1xf32>
// CHECK:     %180 = stablehlo.add %175, %179 : tensor<1xf32>
// CHECK:     %181 = stablehlo.subtract %180, %175 : tensor<1xf32>
// CHECK:     %182 = stablehlo.subtract %179, %181 : tensor<1xf32>
// CHECK:     %cst_136 = stablehlo.constant dense<0.000000e+00> : tensor<1xf32>
// CHECK:     %183 = stablehlo.divide %160, %180 : tensor<1xf32>
// CHECK:     %184 = stablehlo.multiply %183, %180 : tensor<1xf32>
// CHECK:     %cst_137 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %185 = stablehlo.multiply %183, %cst_137 : tensor<1xf32>
// CHECK:     %186 = stablehlo.subtract %185, %183 : tensor<1xf32>
// CHECK:     %187 = stablehlo.subtract %185, %186 : tensor<1xf32>
// CHECK:     %188 = stablehlo.subtract %183, %187 : tensor<1xf32>
// CHECK:     %cst_138 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %189 = stablehlo.multiply %180, %cst_138 : tensor<1xf32>
// CHECK:     %190 = stablehlo.subtract %189, %180 : tensor<1xf32>
// CHECK:     %191 = stablehlo.subtract %189, %190 : tensor<1xf32>
// CHECK:     %192 = stablehlo.subtract %180, %191 : tensor<1xf32>
// CHECK:     %193 = stablehlo.multiply %187, %191 : tensor<1xf32>
// CHECK:     %194 = stablehlo.multiply %187, %192 : tensor<1xf32>
// CHECK:     %195 = stablehlo.multiply %188, %191 : tensor<1xf32>
// CHECK:     %196 = stablehlo.multiply %188, %192 : tensor<1xf32>
// CHECK:     %197 = stablehlo.subtract %193, %184 : tensor<1xf32>
// CHECK:     %198 = stablehlo.add %194, %195 : tensor<1xf32>
// CHECK:     %199 = stablehlo.add %197, %198 : tensor<1xf32>
// CHECK:     %200 = stablehlo.add %199, %196 : tensor<1xf32>
// CHECK:     %201 = stablehlo.multiply %183, %182 : tensor<1xf32>
// CHECK:     %202 = stablehlo.multiply %cst_136, %180 : tensor<1xf32>
// CHECK:     %203 = stablehlo.add %201, %202 : tensor<1xf32>
// CHECK:     %204 = stablehlo.add %200, %203 : tensor<1xf32>
// CHECK:     %205 = stablehlo.add %184, %204 : tensor<1xf32>
// CHECK:     %206 = stablehlo.subtract %205, %184 : tensor<1xf32>
// CHECK:     %207 = stablehlo.subtract %204, %206 : tensor<1xf32>
// CHECK:     %208 = stablehlo.negate %205 : tensor<1xf32>
// CHECK:     %209 = stablehlo.negate %207 : tensor<1xf32>
// CHECK:     %210 = stablehlo.add %160, %208 : tensor<1xf32>
// CHECK:     %211 = stablehlo.subtract %210, %208 : tensor<1xf32>
// CHECK:     %212 = stablehlo.subtract %210, %211 : tensor<1xf32>
// CHECK:     %213 = stablehlo.subtract %160, %211 : tensor<1xf32>
// CHECK:     %214 = stablehlo.subtract %208, %212 : tensor<1xf32>
// CHECK:     %215 = stablehlo.add %213, %214 : tensor<1xf32>
// CHECK:     %216 = stablehlo.add %162, %209 : tensor<1xf32>
// CHECK:     %217 = stablehlo.subtract %216, %209 : tensor<1xf32>
// CHECK:     %218 = stablehlo.subtract %216, %217 : tensor<1xf32>
// CHECK:     %219 = stablehlo.subtract %162, %217 : tensor<1xf32>
// CHECK:     %220 = stablehlo.subtract %209, %218 : tensor<1xf32>
// CHECK:     %221 = stablehlo.add %219, %220 : tensor<1xf32>
// CHECK:     %222 = stablehlo.add %210, %216 : tensor<1xf32>
// CHECK:     %223 = stablehlo.subtract %222, %210 : tensor<1xf32>
// CHECK:     %224 = stablehlo.subtract %216, %223 : tensor<1xf32>
// CHECK:     %225 = stablehlo.add %215, %221 : tensor<1xf32>
// CHECK:     %226 = stablehlo.add %225, %224 : tensor<1xf32>
// CHECK:     %227 = stablehlo.add %222, %226 : tensor<1xf32>
// CHECK:     %228 = stablehlo.subtract %227, %222 : tensor<1xf32>
// CHECK:     %229 = stablehlo.subtract %226, %228 : tensor<1xf32>
// CHECK:     %230 = stablehlo.divide %227, %180 : tensor<1xf32>
// CHECK:     %231 = stablehlo.add %183, %230 : tensor<1xf32>
// CHECK:     %232 = stablehlo.subtract %231, %183 : tensor<1xf32>
// CHECK:     %233 = stablehlo.subtract %230, %232 : tensor<1xf32>
// CHECK:     %234 = stablehlo.negate %60 : tensor<1xf32>
// CHECK:     %235 = stablehlo.negate %cst_47 : tensor<1xf32>
// CHECK:     %236 = stablehlo.add %16, %234 : tensor<1xf32>
// CHECK:     %237 = stablehlo.subtract %236, %234 : tensor<1xf32>
// CHECK:     %238 = stablehlo.subtract %236, %237 : tensor<1xf32>
// CHECK:     %239 = stablehlo.subtract %16, %237 : tensor<1xf32>
// CHECK:     %240 = stablehlo.subtract %234, %238 : tensor<1xf32>
// CHECK:     %241 = stablehlo.add %239, %240 : tensor<1xf32>
// CHECK:     %242 = stablehlo.add %17, %235 : tensor<1xf32>
// CHECK:     %243 = stablehlo.subtract %242, %235 : tensor<1xf32>
// CHECK:     %244 = stablehlo.subtract %242, %243 : tensor<1xf32>
// CHECK:     %245 = stablehlo.subtract %17, %243 : tensor<1xf32>
// CHECK:     %246 = stablehlo.subtract %235, %244 : tensor<1xf32>
// CHECK:     %247 = stablehlo.add %245, %246 : tensor<1xf32>
// CHECK:     %248 = stablehlo.add %236, %242 : tensor<1xf32>
// CHECK:     %249 = stablehlo.subtract %248, %236 : tensor<1xf32>
// CHECK:     %250 = stablehlo.subtract %242, %249 : tensor<1xf32>
// CHECK:     %251 = stablehlo.add %241, %247 : tensor<1xf32>
// CHECK:     %252 = stablehlo.add %251, %250 : tensor<1xf32>
// CHECK:     %253 = stablehlo.add %248, %252 : tensor<1xf32>
// CHECK:     %254 = stablehlo.subtract %253, %248 : tensor<1xf32>
// CHECK:     %255 = stablehlo.subtract %252, %254 : tensor<1xf32>
// CHECK:     %256 = stablehlo.add %16, %60 : tensor<1xf32>
// CHECK:     %257 = stablehlo.subtract %256, %60 : tensor<1xf32>
// CHECK:     %258 = stablehlo.subtract %256, %257 : tensor<1xf32>
// CHECK:     %259 = stablehlo.subtract %16, %257 : tensor<1xf32>
// CHECK:     %260 = stablehlo.subtract %60, %258 : tensor<1xf32>
// CHECK:     %261 = stablehlo.add %259, %260 : tensor<1xf32>
// CHECK:     %262 = stablehlo.add %17, %cst_47 : tensor<1xf32>
// CHECK:     %263 = stablehlo.subtract %262, %cst_47 : tensor<1xf32>
// CHECK:     %264 = stablehlo.subtract %262, %263 : tensor<1xf32>
// CHECK:     %265 = stablehlo.subtract %17, %263 : tensor<1xf32>
// CHECK:     %266 = stablehlo.subtract %cst_47, %264 : tensor<1xf32>
// CHECK:     %267 = stablehlo.add %265, %266 : tensor<1xf32>
// CHECK:     %268 = stablehlo.add %256, %262 : tensor<1xf32>
// CHECK:     %269 = stablehlo.subtract %268, %256 : tensor<1xf32>
// CHECK:     %270 = stablehlo.subtract %262, %269 : tensor<1xf32>
// CHECK:     %271 = stablehlo.add %261, %267 : tensor<1xf32>
// CHECK:     %272 = stablehlo.add %271, %270 : tensor<1xf32>
// CHECK:     %273 = stablehlo.add %268, %272 : tensor<1xf32>
// CHECK:     %274 = stablehlo.subtract %273, %268 : tensor<1xf32>
// CHECK:     %275 = stablehlo.subtract %272, %274 : tensor<1xf32>
// CHECK:     %cst_139 = stablehlo.constant dense<0.000000e+00> : tensor<1xf32>
// CHECK:     %276 = stablehlo.divide %253, %273 : tensor<1xf32>
// CHECK:     %277 = stablehlo.multiply %276, %273 : tensor<1xf32>
// CHECK:     %cst_140 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %278 = stablehlo.multiply %276, %cst_140 : tensor<1xf32>
// CHECK:     %279 = stablehlo.subtract %278, %276 : tensor<1xf32>
// CHECK:     %280 = stablehlo.subtract %278, %279 : tensor<1xf32>
// CHECK:     %281 = stablehlo.subtract %276, %280 : tensor<1xf32>
// CHECK:     %cst_141 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %282 = stablehlo.multiply %273, %cst_141 : tensor<1xf32>
// CHECK:     %283 = stablehlo.subtract %282, %273 : tensor<1xf32>
// CHECK:     %284 = stablehlo.subtract %282, %283 : tensor<1xf32>
// CHECK:     %285 = stablehlo.subtract %273, %284 : tensor<1xf32>
// CHECK:     %286 = stablehlo.multiply %280, %284 : tensor<1xf32>
// CHECK:     %287 = stablehlo.multiply %280, %285 : tensor<1xf32>
// CHECK:     %288 = stablehlo.multiply %281, %284 : tensor<1xf32>
// CHECK:     %289 = stablehlo.multiply %281, %285 : tensor<1xf32>
// CHECK:     %290 = stablehlo.subtract %286, %277 : tensor<1xf32>
// CHECK:     %291 = stablehlo.add %287, %288 : tensor<1xf32>
// CHECK:     %292 = stablehlo.add %290, %291 : tensor<1xf32>
// CHECK:     %293 = stablehlo.add %292, %289 : tensor<1xf32>
// CHECK:     %294 = stablehlo.multiply %276, %275 : tensor<1xf32>
// CHECK:     %295 = stablehlo.multiply %cst_139, %273 : tensor<1xf32>
// CHECK:     %296 = stablehlo.add %294, %295 : tensor<1xf32>
// CHECK:     %297 = stablehlo.add %293, %296 : tensor<1xf32>
// CHECK:     %298 = stablehlo.add %277, %297 : tensor<1xf32>
// CHECK:     %299 = stablehlo.subtract %298, %277 : tensor<1xf32>
// CHECK:     %300 = stablehlo.subtract %297, %299 : tensor<1xf32>
// CHECK:     %301 = stablehlo.negate %298 : tensor<1xf32>
// CHECK:     %302 = stablehlo.negate %300 : tensor<1xf32>
// CHECK:     %303 = stablehlo.add %253, %301 : tensor<1xf32>
// CHECK:     %304 = stablehlo.subtract %303, %301 : tensor<1xf32>
// CHECK:     %305 = stablehlo.subtract %303, %304 : tensor<1xf32>
// CHECK:     %306 = stablehlo.subtract %253, %304 : tensor<1xf32>
// CHECK:     %307 = stablehlo.subtract %301, %305 : tensor<1xf32>
// CHECK:     %308 = stablehlo.add %306, %307 : tensor<1xf32>
// CHECK:     %309 = stablehlo.add %255, %302 : tensor<1xf32>
// CHECK:     %310 = stablehlo.subtract %309, %302 : tensor<1xf32>
// CHECK:     %311 = stablehlo.subtract %309, %310 : tensor<1xf32>
// CHECK:     %312 = stablehlo.subtract %255, %310 : tensor<1xf32>
// CHECK:     %313 = stablehlo.subtract %302, %311 : tensor<1xf32>
// CHECK:     %314 = stablehlo.add %312, %313 : tensor<1xf32>
// CHECK:     %315 = stablehlo.add %303, %309 : tensor<1xf32>
// CHECK:     %316 = stablehlo.subtract %315, %303 : tensor<1xf32>
// CHECK:     %317 = stablehlo.subtract %309, %316 : tensor<1xf32>
// CHECK:     %318 = stablehlo.add %308, %314 : tensor<1xf32>
// CHECK:     %319 = stablehlo.add %318, %317 : tensor<1xf32>
// CHECK:     %320 = stablehlo.add %315, %319 : tensor<1xf32>
// CHECK:     %321 = stablehlo.subtract %320, %315 : tensor<1xf32>
// CHECK:     %322 = stablehlo.subtract %319, %321 : tensor<1xf32>
// CHECK:     %323 = stablehlo.divide %320, %273 : tensor<1xf32>
// CHECK:     %324 = stablehlo.add %276, %323 : tensor<1xf32>
// CHECK:     %325 = stablehlo.subtract %324, %276 : tensor<1xf32>
// CHECK:     %326 = stablehlo.subtract %323, %325 : tensor<1xf32>
// CHECK:     %327 = stablehlo.multiply %231, %231 : tensor<1xf32>
// CHECK:     %cst_142 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %328 = stablehlo.multiply %231, %cst_142 : tensor<1xf32>
// CHECK:     %329 = stablehlo.subtract %328, %231 : tensor<1xf32>
// CHECK:     %330 = stablehlo.subtract %328, %329 : tensor<1xf32>
// CHECK:     %331 = stablehlo.subtract %231, %330 : tensor<1xf32>
// CHECK:     %cst_143 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %332 = stablehlo.multiply %231, %cst_143 : tensor<1xf32>
// CHECK:     %333 = stablehlo.subtract %332, %231 : tensor<1xf32>
// CHECK:     %334 = stablehlo.subtract %332, %333 : tensor<1xf32>
// CHECK:     %335 = stablehlo.subtract %231, %334 : tensor<1xf32>
// CHECK:     %336 = stablehlo.multiply %330, %334 : tensor<1xf32>
// CHECK:     %337 = stablehlo.multiply %330, %335 : tensor<1xf32>
// CHECK:     %338 = stablehlo.multiply %331, %334 : tensor<1xf32>
// CHECK:     %339 = stablehlo.multiply %331, %335 : tensor<1xf32>
// CHECK:     %340 = stablehlo.subtract %336, %327 : tensor<1xf32>
// CHECK:     %341 = stablehlo.add %337, %338 : tensor<1xf32>
// CHECK:     %342 = stablehlo.add %340, %341 : tensor<1xf32>
// CHECK:     %343 = stablehlo.add %342, %339 : tensor<1xf32>
// CHECK:     %344 = stablehlo.multiply %231, %233 : tensor<1xf32>
// CHECK:     %345 = stablehlo.multiply %233, %231 : tensor<1xf32>
// CHECK:     %346 = stablehlo.add %344, %345 : tensor<1xf32>
// CHECK:     %347 = stablehlo.add %343, %346 : tensor<1xf32>
// CHECK:     %348 = stablehlo.add %327, %347 : tensor<1xf32>
// CHECK:     %349 = stablehlo.subtract %348, %327 : tensor<1xf32>
// CHECK:     %350 = stablehlo.subtract %347, %349 : tensor<1xf32>
// CHECK:     %351 = stablehlo.multiply %324, %324 : tensor<1xf32>
// CHECK:     %cst_144 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %352 = stablehlo.multiply %324, %cst_144 : tensor<1xf32>
// CHECK:     %353 = stablehlo.subtract %352, %324 : tensor<1xf32>
// CHECK:     %354 = stablehlo.subtract %352, %353 : tensor<1xf32>
// CHECK:     %355 = stablehlo.subtract %324, %354 : tensor<1xf32>
// CHECK:     %cst_145 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %356 = stablehlo.multiply %324, %cst_145 : tensor<1xf32>
// CHECK:     %357 = stablehlo.subtract %356, %324 : tensor<1xf32>
// CHECK:     %358 = stablehlo.subtract %356, %357 : tensor<1xf32>
// CHECK:     %359 = stablehlo.subtract %324, %358 : tensor<1xf32>
// CHECK:     %360 = stablehlo.multiply %354, %358 : tensor<1xf32>
// CHECK:     %361 = stablehlo.multiply %354, %359 : tensor<1xf32>
// CHECK:     %362 = stablehlo.multiply %355, %358 : tensor<1xf32>
// CHECK:     %363 = stablehlo.multiply %355, %359 : tensor<1xf32>
// CHECK:     %364 = stablehlo.subtract %360, %351 : tensor<1xf32>
// CHECK:     %365 = stablehlo.add %361, %362 : tensor<1xf32>
// CHECK:     %366 = stablehlo.add %364, %365 : tensor<1xf32>
// CHECK:     %367 = stablehlo.add %366, %363 : tensor<1xf32>
// CHECK:     %368 = stablehlo.multiply %324, %326 : tensor<1xf32>
// CHECK:     %369 = stablehlo.multiply %326, %324 : tensor<1xf32>
// CHECK:     %370 = stablehlo.add %368, %369 : tensor<1xf32>
// CHECK:     %371 = stablehlo.add %367, %370 : tensor<1xf32>
// CHECK:     %372 = stablehlo.add %351, %371 : tensor<1xf32>
// CHECK:     %373 = stablehlo.subtract %372, %351 : tensor<1xf32>
// CHECK:     %374 = stablehlo.subtract %371, %373 : tensor<1xf32>
// CHECK:     %cst_146 = stablehlo.constant dense<0.412237108> : tensor<1xf32>
// CHECK:     %cst_147 = stablehlo.constant dense<0.000000e+00> : tensor<1xf32>
// CHECK:     %375 = stablehlo.multiply %cst_146, %372 : tensor<1xf32>
// CHECK:     %cst_148 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %376 = stablehlo.multiply %cst_146, %cst_148 : tensor<1xf32>
// CHECK:     %377 = stablehlo.subtract %376, %cst_146 : tensor<1xf32>
// CHECK:     %378 = stablehlo.subtract %376, %377 : tensor<1xf32>
// CHECK:     %379 = stablehlo.subtract %cst_146, %378 : tensor<1xf32>
// CHECK:     %cst_149 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %380 = stablehlo.multiply %372, %cst_149 : tensor<1xf32>
// CHECK:     %381 = stablehlo.subtract %380, %372 : tensor<1xf32>
// CHECK:     %382 = stablehlo.subtract %380, %381 : tensor<1xf32>
// CHECK:     %383 = stablehlo.subtract %372, %382 : tensor<1xf32>
// CHECK:     %384 = stablehlo.multiply %378, %382 : tensor<1xf32>
// CHECK:     %385 = stablehlo.multiply %378, %383 : tensor<1xf32>
// CHECK:     %386 = stablehlo.multiply %379, %382 : tensor<1xf32>
// CHECK:     %387 = stablehlo.multiply %379, %383 : tensor<1xf32>
// CHECK:     %388 = stablehlo.subtract %384, %375 : tensor<1xf32>
// CHECK:     %389 = stablehlo.add %385, %386 : tensor<1xf32>
// CHECK:     %390 = stablehlo.add %388, %389 : tensor<1xf32>
// CHECK:     %391 = stablehlo.add %390, %387 : tensor<1xf32>
// CHECK:     %392 = stablehlo.multiply %cst_146, %374 : tensor<1xf32>
// CHECK:     %393 = stablehlo.multiply %cst_147, %372 : tensor<1xf32>
// CHECK:     %394 = stablehlo.add %392, %393 : tensor<1xf32>
// CHECK:     %395 = stablehlo.add %391, %394 : tensor<1xf32>
// CHECK:     %396 = stablehlo.add %375, %395 : tensor<1xf32>
// CHECK:     %397 = stablehlo.subtract %396, %375 : tensor<1xf32>
// CHECK:     %398 = stablehlo.subtract %395, %397 : tensor<1xf32>
// CHECK:     %cst_151 = stablehlo.constant dense<0.577078044> : tensor<1xf32>
// CHECK:     %cst_150 = stablehlo.constant dense<0.000000e+00> : tensor<1xf32>
// CHECK:     %399 = stablehlo.add %396, %cst_151 : tensor<1xf32>
// CHECK:     %400 = stablehlo.subtract %399, %cst_151 : tensor<1xf32>
// CHECK:     %401 = stablehlo.subtract %399, %400 : tensor<1xf32>
// CHECK:     %402 = stablehlo.subtract %396, %400 : tensor<1xf32>
// CHECK:     %403 = stablehlo.subtract %cst_151, %401 : tensor<1xf32>
// CHECK:     %404 = stablehlo.add %402, %403 : tensor<1xf32>
// CHECK:     %405 = stablehlo.add %398, %cst_150 : tensor<1xf32>
// CHECK:     %406 = stablehlo.subtract %405, %cst_150 : tensor<1xf32>
// CHECK:     %407 = stablehlo.subtract %405, %406 : tensor<1xf32>
// CHECK:     %408 = stablehlo.subtract %398, %406 : tensor<1xf32>
// CHECK:     %409 = stablehlo.subtract %cst_150, %407 : tensor<1xf32>
// CHECK:     %410 = stablehlo.add %408, %409 : tensor<1xf32>
// CHECK:     %411 = stablehlo.add %399, %405 : tensor<1xf32>
// CHECK:     %412 = stablehlo.subtract %411, %399 : tensor<1xf32>
// CHECK:     %413 = stablehlo.subtract %405, %412 : tensor<1xf32>
// CHECK:     %414 = stablehlo.add %404, %410 : tensor<1xf32>
// CHECK:     %415 = stablehlo.add %414, %413 : tensor<1xf32>
// CHECK:     %416 = stablehlo.add %411, %415 : tensor<1xf32>
// CHECK:     %417 = stablehlo.subtract %416, %411 : tensor<1xf32>
// CHECK:     %418 = stablehlo.subtract %415, %417 : tensor<1xf32>
// CHECK:     %419 = stablehlo.multiply %416, %372 : tensor<1xf32>
// CHECK:     %cst_152 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %420 = stablehlo.multiply %416, %cst_152 : tensor<1xf32>
// CHECK:     %421 = stablehlo.subtract %420, %416 : tensor<1xf32>
// CHECK:     %422 = stablehlo.subtract %420, %421 : tensor<1xf32>
// CHECK:     %423 = stablehlo.subtract %416, %422 : tensor<1xf32>
// CHECK:     %cst_153 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %424 = stablehlo.multiply %372, %cst_153 : tensor<1xf32>
// CHECK:     %425 = stablehlo.subtract %424, %372 : tensor<1xf32>
// CHECK:     %426 = stablehlo.subtract %424, %425 : tensor<1xf32>
// CHECK:     %427 = stablehlo.subtract %372, %426 : tensor<1xf32>
// CHECK:     %428 = stablehlo.multiply %422, %426 : tensor<1xf32>
// CHECK:     %429 = stablehlo.multiply %422, %427 : tensor<1xf32>
// CHECK:     %430 = stablehlo.multiply %423, %426 : tensor<1xf32>
// CHECK:     %431 = stablehlo.multiply %423, %427 : tensor<1xf32>
// CHECK:     %432 = stablehlo.subtract %428, %419 : tensor<1xf32>
// CHECK:     %433 = stablehlo.add %429, %430 : tensor<1xf32>
// CHECK:     %434 = stablehlo.add %432, %433 : tensor<1xf32>
// CHECK:     %435 = stablehlo.add %434, %431 : tensor<1xf32>
// CHECK:     %436 = stablehlo.multiply %416, %374 : tensor<1xf32>
// CHECK:     %437 = stablehlo.multiply %418, %372 : tensor<1xf32>
// CHECK:     %438 = stablehlo.add %436, %437 : tensor<1xf32>
// CHECK:     %439 = stablehlo.add %435, %438 : tensor<1xf32>
// CHECK:     %440 = stablehlo.add %419, %439 : tensor<1xf32>
// CHECK:     %441 = stablehlo.subtract %440, %419 : tensor<1xf32>
// CHECK:     %442 = stablehlo.subtract %439, %441 : tensor<1xf32>
// CHECK:     %cst_154 = stablehlo.constant dense<0.9617967> : tensor<1xf32>
// CHECK:     %cst_155 = stablehlo.constant dense<-7.02844404E-9> : tensor<1xf32>
// CHECK:     %443 = stablehlo.add %440, %cst_154 : tensor<1xf32>
// CHECK:     %444 = stablehlo.subtract %443, %cst_154 : tensor<1xf32>
// CHECK:     %445 = stablehlo.subtract %443, %444 : tensor<1xf32>
// CHECK:     %446 = stablehlo.subtract %440, %444 : tensor<1xf32>
// CHECK:     %447 = stablehlo.subtract %cst_154, %445 : tensor<1xf32>
// CHECK:     %448 = stablehlo.add %446, %447 : tensor<1xf32>
// CHECK:     %449 = stablehlo.add %442, %cst_155 : tensor<1xf32>
// CHECK:     %450 = stablehlo.subtract %449, %cst_155 : tensor<1xf32>
// CHECK:     %451 = stablehlo.subtract %449, %450 : tensor<1xf32>
// CHECK:     %452 = stablehlo.subtract %442, %450 : tensor<1xf32>
// CHECK:     %453 = stablehlo.subtract %cst_155, %451 : tensor<1xf32>
// CHECK:     %454 = stablehlo.add %452, %453 : tensor<1xf32>
// CHECK:     %455 = stablehlo.add %443, %449 : tensor<1xf32>
// CHECK:     %456 = stablehlo.subtract %455, %443 : tensor<1xf32>
// CHECK:     %457 = stablehlo.subtract %449, %456 : tensor<1xf32>
// CHECK:     %458 = stablehlo.add %448, %454 : tensor<1xf32>
// CHECK:     %459 = stablehlo.add %458, %457 : tensor<1xf32>
// CHECK:     %460 = stablehlo.add %455, %459 : tensor<1xf32>
// CHECK:     %461 = stablehlo.subtract %460, %455 : tensor<1xf32>
// CHECK:     %462 = stablehlo.subtract %459, %461 : tensor<1xf32>
// CHECK:     %463 = stablehlo.multiply %460, %372 : tensor<1xf32>
// CHECK:     %cst_156 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %464 = stablehlo.multiply %460, %cst_156 : tensor<1xf32>
// CHECK:     %465 = stablehlo.subtract %464, %460 : tensor<1xf32>
// CHECK:     %466 = stablehlo.subtract %464, %465 : tensor<1xf32>
// CHECK:     %467 = stablehlo.subtract %460, %466 : tensor<1xf32>
// CHECK:     %cst_157 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %468 = stablehlo.multiply %372, %cst_157 : tensor<1xf32>
// CHECK:     %469 = stablehlo.subtract %468, %372 : tensor<1xf32>
// CHECK:     %470 = stablehlo.subtract %468, %469 : tensor<1xf32>
// CHECK:     %471 = stablehlo.subtract %372, %470 : tensor<1xf32>
// CHECK:     %472 = stablehlo.multiply %466, %470 : tensor<1xf32>
// CHECK:     %473 = stablehlo.multiply %466, %471 : tensor<1xf32>
// CHECK:     %474 = stablehlo.multiply %467, %470 : tensor<1xf32>
// CHECK:     %475 = stablehlo.multiply %467, %471 : tensor<1xf32>
// CHECK:     %476 = stablehlo.subtract %472, %463 : tensor<1xf32>
// CHECK:     %477 = stablehlo.add %473, %474 : tensor<1xf32>
// CHECK:     %478 = stablehlo.add %476, %477 : tensor<1xf32>
// CHECK:     %479 = stablehlo.add %478, %475 : tensor<1xf32>
// CHECK:     %480 = stablehlo.multiply %460, %374 : tensor<1xf32>
// CHECK:     %481 = stablehlo.multiply %462, %372 : tensor<1xf32>
// CHECK:     %482 = stablehlo.add %480, %481 : tensor<1xf32>
// CHECK:     %483 = stablehlo.add %479, %482 : tensor<1xf32>
// CHECK:     %484 = stablehlo.add %463, %483 : tensor<1xf32>
// CHECK:     %485 = stablehlo.subtract %484, %463 : tensor<1xf32>
// CHECK:     %486 = stablehlo.subtract %483, %485 : tensor<1xf32>
// CHECK:     %cst_158 = stablehlo.constant dense<2.885390e+00> : tensor<1xf32>
// CHECK:     %cst_159 = stablehlo.constant dense<3.85192607E-8> : tensor<1xf32>
// CHECK:     %487 = stablehlo.add %484, %cst_158 : tensor<1xf32>
// CHECK:     %488 = stablehlo.subtract %487, %cst_158 : tensor<1xf32>
// CHECK:     %489 = stablehlo.subtract %487, %488 : tensor<1xf32>
// CHECK:     %490 = stablehlo.subtract %484, %488 : tensor<1xf32>
// CHECK:     %491 = stablehlo.subtract %cst_158, %489 : tensor<1xf32>
// CHECK:     %492 = stablehlo.add %490, %491 : tensor<1xf32>
// CHECK:     %493 = stablehlo.add %486, %cst_159 : tensor<1xf32>
// CHECK:     %494 = stablehlo.subtract %493, %cst_159 : tensor<1xf32>
// CHECK:     %495 = stablehlo.subtract %493, %494 : tensor<1xf32>
// CHECK:     %496 = stablehlo.subtract %486, %494 : tensor<1xf32>
// CHECK:     %497 = stablehlo.subtract %cst_159, %495 : tensor<1xf32>
// CHECK:     %498 = stablehlo.add %496, %497 : tensor<1xf32>
// CHECK:     %499 = stablehlo.add %487, %493 : tensor<1xf32>
// CHECK:     %500 = stablehlo.subtract %499, %487 : tensor<1xf32>
// CHECK:     %501 = stablehlo.subtract %493, %500 : tensor<1xf32>
// CHECK:     %502 = stablehlo.add %492, %498 : tensor<1xf32>
// CHECK:     %503 = stablehlo.add %502, %501 : tensor<1xf32>
// CHECK:     %504 = stablehlo.add %499, %503 : tensor<1xf32>
// CHECK:     %505 = stablehlo.subtract %504, %499 : tensor<1xf32>
// CHECK:     %506 = stablehlo.subtract %503, %505 : tensor<1xf32>
// CHECK:     %cst_160 = stablehlo.constant dense<0.321282297> : tensor<1xf32>
// CHECK:     %cst_161 = stablehlo.constant dense<0.000000e+00> : tensor<1xf32>
// CHECK:     %507 = stablehlo.multiply %cst_160, %348 : tensor<1xf32>
// CHECK:     %cst_162 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %508 = stablehlo.multiply %cst_160, %cst_162 : tensor<1xf32>
// CHECK:     %509 = stablehlo.subtract %508, %cst_160 : tensor<1xf32>
// CHECK:     %510 = stablehlo.subtract %508, %509 : tensor<1xf32>
// CHECK:     %511 = stablehlo.subtract %cst_160, %510 : tensor<1xf32>
// CHECK:     %cst_163 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %512 = stablehlo.multiply %348, %cst_163 : tensor<1xf32>
// CHECK:     %513 = stablehlo.subtract %512, %348 : tensor<1xf32>
// CHECK:     %514 = stablehlo.subtract %512, %513 : tensor<1xf32>
// CHECK:     %515 = stablehlo.subtract %348, %514 : tensor<1xf32>
// CHECK:     %516 = stablehlo.multiply %510, %514 : tensor<1xf32>
// CHECK:     %517 = stablehlo.multiply %510, %515 : tensor<1xf32>
// CHECK:     %518 = stablehlo.multiply %511, %514 : tensor<1xf32>
// CHECK:     %519 = stablehlo.multiply %511, %515 : tensor<1xf32>
// CHECK:     %520 = stablehlo.subtract %516, %507 : tensor<1xf32>
// CHECK:     %521 = stablehlo.add %517, %518 : tensor<1xf32>
// CHECK:     %522 = stablehlo.add %520, %521 : tensor<1xf32>
// CHECK:     %523 = stablehlo.add %522, %519 : tensor<1xf32>
// CHECK:     %524 = stablehlo.multiply %cst_160, %350 : tensor<1xf32>
// CHECK:     %525 = stablehlo.multiply %cst_161, %348 : tensor<1xf32>
// CHECK:     %526 = stablehlo.add %524, %525 : tensor<1xf32>
// CHECK:     %527 = stablehlo.add %523, %526 : tensor<1xf32>
// CHECK:     %528 = stablehlo.add %507, %527 : tensor<1xf32>
// CHECK:     %529 = stablehlo.subtract %528, %507 : tensor<1xf32>
// CHECK:     %530 = stablehlo.subtract %527, %529 : tensor<1xf32>
// CHECK:     %cst_164 = stablehlo.constant dense<0.412197948> : tensor<1xf32>
// CHECK:     %cst_165 = stablehlo.constant dense<0.000000e+00> : tensor<1xf32>
// CHECK:     %531 = stablehlo.add %528, %cst_164 : tensor<1xf32>
// CHECK:     %532 = stablehlo.subtract %531, %cst_164 : tensor<1xf32>
// CHECK:     %533 = stablehlo.subtract %531, %532 : tensor<1xf32>
// CHECK:     %534 = stablehlo.subtract %528, %532 : tensor<1xf32>
// CHECK:     %535 = stablehlo.subtract %cst_164, %533 : tensor<1xf32>
// CHECK:     %536 = stablehlo.add %534, %535 : tensor<1xf32>
// CHECK:     %537 = stablehlo.add %530, %cst_165 : tensor<1xf32>
// CHECK:     %538 = stablehlo.subtract %537, %cst_165 : tensor<1xf32>
// CHECK:     %539 = stablehlo.subtract %537, %538 : tensor<1xf32>
// CHECK:     %540 = stablehlo.subtract %530, %538 : tensor<1xf32>
// CHECK:     %541 = stablehlo.subtract %cst_165, %539 : tensor<1xf32>
// CHECK:     %542 = stablehlo.add %540, %541 : tensor<1xf32>
// CHECK:     %543 = stablehlo.add %531, %537 : tensor<1xf32>
// CHECK:     %544 = stablehlo.subtract %543, %531 : tensor<1xf32>
// CHECK:     %545 = stablehlo.subtract %537, %544 : tensor<1xf32>
// CHECK:     %546 = stablehlo.add %536, %542 : tensor<1xf32>
// CHECK:     %547 = stablehlo.add %546, %545 : tensor<1xf32>
// CHECK:     %548 = stablehlo.add %543, %547 : tensor<1xf32>
// CHECK:     %549 = stablehlo.subtract %548, %543 : tensor<1xf32>
// CHECK:     %550 = stablehlo.subtract %547, %549 : tensor<1xf32>
// CHECK:     %551 = stablehlo.multiply %548, %348 : tensor<1xf32>
// CHECK:     %cst_166 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %552 = stablehlo.multiply %548, %cst_166 : tensor<1xf32>
// CHECK:     %553 = stablehlo.subtract %552, %548 : tensor<1xf32>
// CHECK:     %554 = stablehlo.subtract %552, %553 : tensor<1xf32>
// CHECK:     %555 = stablehlo.subtract %548, %554 : tensor<1xf32>
// CHECK:     %cst_167 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %556 = stablehlo.multiply %348, %cst_167 : tensor<1xf32>
// CHECK:     %557 = stablehlo.subtract %556, %348 : tensor<1xf32>
// CHECK:     %558 = stablehlo.subtract %556, %557 : tensor<1xf32>
// CHECK:     %559 = stablehlo.subtract %348, %558 : tensor<1xf32>
// CHECK:     %560 = stablehlo.multiply %554, %558 : tensor<1xf32>
// CHECK:     %561 = stablehlo.multiply %554, %559 : tensor<1xf32>
// CHECK:     %562 = stablehlo.multiply %555, %558 : tensor<1xf32>
// CHECK:     %563 = stablehlo.multiply %555, %559 : tensor<1xf32>
// CHECK:     %564 = stablehlo.subtract %560, %551 : tensor<1xf32>
// CHECK:     %565 = stablehlo.add %561, %562 : tensor<1xf32>
// CHECK:     %566 = stablehlo.add %564, %565 : tensor<1xf32>
// CHECK:     %567 = stablehlo.add %566, %563 : tensor<1xf32>
// CHECK:     %568 = stablehlo.multiply %548, %350 : tensor<1xf32>
// CHECK:     %569 = stablehlo.multiply %550, %348 : tensor<1xf32>
// CHECK:     %570 = stablehlo.add %568, %569 : tensor<1xf32>
// CHECK:     %571 = stablehlo.add %567, %570 : tensor<1xf32>
// CHECK:     %572 = stablehlo.add %551, %571 : tensor<1xf32>
// CHECK:     %573 = stablehlo.subtract %572, %551 : tensor<1xf32>
// CHECK:     %574 = stablehlo.subtract %571, %573 : tensor<1xf32>
// CHECK:     %cst_168 = stablehlo.constant dense<0.577078044> : tensor<1xf32>
// CHECK:     %cst_169 = stablehlo.constant dense<-2.78275056E-8> : tensor<1xf32>
// CHECK:     %575 = stablehlo.add %572, %cst_168 : tensor<1xf32>
// CHECK:     %576 = stablehlo.subtract %575, %cst_168 : tensor<1xf32>
// CHECK:     %577 = stablehlo.subtract %575, %576 : tensor<1xf32>
// CHECK:     %578 = stablehlo.subtract %572, %576 : tensor<1xf32>
// CHECK:     %579 = stablehlo.subtract %cst_168, %577 : tensor<1xf32>
// CHECK:     %580 = stablehlo.add %578, %579 : tensor<1xf32>
// CHECK:     %581 = stablehlo.add %574, %cst_169 : tensor<1xf32>
// CHECK:     %582 = stablehlo.subtract %581, %cst_169 : tensor<1xf32>
// CHECK:     %583 = stablehlo.subtract %581, %582 : tensor<1xf32>
// CHECK:     %584 = stablehlo.subtract %574, %582 : tensor<1xf32>
// CHECK:     %585 = stablehlo.subtract %cst_169, %583 : tensor<1xf32>
// CHECK:     %586 = stablehlo.add %584, %585 : tensor<1xf32>
// CHECK:     %587 = stablehlo.add %575, %581 : tensor<1xf32>
// CHECK:     %588 = stablehlo.subtract %587, %575 : tensor<1xf32>
// CHECK:     %589 = stablehlo.subtract %581, %588 : tensor<1xf32>
// CHECK:     %590 = stablehlo.add %580, %586 : tensor<1xf32>
// CHECK:     %591 = stablehlo.add %590, %589 : tensor<1xf32>
// CHECK:     %592 = stablehlo.add %587, %591 : tensor<1xf32>
// CHECK:     %593 = stablehlo.subtract %592, %587 : tensor<1xf32>
// CHECK:     %594 = stablehlo.subtract %591, %593 : tensor<1xf32>
// CHECK:     %595 = stablehlo.multiply %592, %348 : tensor<1xf32>
// CHECK:     %cst_170 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %596 = stablehlo.multiply %592, %cst_170 : tensor<1xf32>
// CHECK:     %597 = stablehlo.subtract %596, %592 : tensor<1xf32>
// CHECK:     %598 = stablehlo.subtract %596, %597 : tensor<1xf32>
// CHECK:     %599 = stablehlo.subtract %592, %598 : tensor<1xf32>
// CHECK:     %cst_171 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %600 = stablehlo.multiply %348, %cst_171 : tensor<1xf32>
// CHECK:     %601 = stablehlo.subtract %600, %348 : tensor<1xf32>
// CHECK:     %602 = stablehlo.subtract %600, %601 : tensor<1xf32>
// CHECK:     %603 = stablehlo.subtract %348, %602 : tensor<1xf32>
// CHECK:     %604 = stablehlo.multiply %598, %602 : tensor<1xf32>
// CHECK:     %605 = stablehlo.multiply %598, %603 : tensor<1xf32>
// CHECK:     %606 = stablehlo.multiply %599, %602 : tensor<1xf32>
// CHECK:     %607 = stablehlo.multiply %599, %603 : tensor<1xf32>
// CHECK:     %608 = stablehlo.subtract %604, %595 : tensor<1xf32>
// CHECK:     %609 = stablehlo.add %605, %606 : tensor<1xf32>
// CHECK:     %610 = stablehlo.add %608, %609 : tensor<1xf32>
// CHECK:     %611 = stablehlo.add %610, %607 : tensor<1xf32>
// CHECK:     %612 = stablehlo.multiply %592, %350 : tensor<1xf32>
// CHECK:     %613 = stablehlo.multiply %594, %348 : tensor<1xf32>
// CHECK:     %614 = stablehlo.add %612, %613 : tensor<1xf32>
// CHECK:     %615 = stablehlo.add %611, %614 : tensor<1xf32>
// CHECK:     %616 = stablehlo.add %595, %615 : tensor<1xf32>
// CHECK:     %617 = stablehlo.subtract %616, %595 : tensor<1xf32>
// CHECK:     %618 = stablehlo.subtract %615, %617 : tensor<1xf32>
// CHECK:     %cst_172 = stablehlo.constant dense<0.9617967> : tensor<1xf32>
// CHECK:     %cst_173 = stablehlo.constant dense<-7.02849157E-9> : tensor<1xf32>
// CHECK:     %619 = stablehlo.add %616, %cst_172 : tensor<1xf32>
// CHECK:     %620 = stablehlo.subtract %619, %cst_172 : tensor<1xf32>
// CHECK:     %621 = stablehlo.subtract %619, %620 : tensor<1xf32>
// CHECK:     %622 = stablehlo.subtract %616, %620 : tensor<1xf32>
// CHECK:     %623 = stablehlo.subtract %cst_172, %621 : tensor<1xf32>
// CHECK:     %624 = stablehlo.add %622, %623 : tensor<1xf32>
// CHECK:     %625 = stablehlo.add %618, %cst_173 : tensor<1xf32>
// CHECK:     %626 = stablehlo.subtract %625, %cst_173 : tensor<1xf32>
// CHECK:     %627 = stablehlo.subtract %625, %626 : tensor<1xf32>
// CHECK:     %628 = stablehlo.subtract %618, %626 : tensor<1xf32>
// CHECK:     %629 = stablehlo.subtract %cst_173, %627 : tensor<1xf32>
// CHECK:     %630 = stablehlo.add %628, %629 : tensor<1xf32>
// CHECK:     %631 = stablehlo.add %619, %625 : tensor<1xf32>
// CHECK:     %632 = stablehlo.subtract %631, %619 : tensor<1xf32>
// CHECK:     %633 = stablehlo.subtract %625, %632 : tensor<1xf32>
// CHECK:     %634 = stablehlo.add %624, %630 : tensor<1xf32>
// CHECK:     %635 = stablehlo.add %634, %633 : tensor<1xf32>
// CHECK:     %636 = stablehlo.add %631, %635 : tensor<1xf32>
// CHECK:     %637 = stablehlo.subtract %636, %631 : tensor<1xf32>
// CHECK:     %638 = stablehlo.subtract %635, %637 : tensor<1xf32>
// CHECK:     %639 = stablehlo.multiply %636, %348 : tensor<1xf32>
// CHECK:     %cst_174 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %640 = stablehlo.multiply %636, %cst_174 : tensor<1xf32>
// CHECK:     %641 = stablehlo.subtract %640, %636 : tensor<1xf32>
// CHECK:     %642 = stablehlo.subtract %640, %641 : tensor<1xf32>
// CHECK:     %643 = stablehlo.subtract %636, %642 : tensor<1xf32>
// CHECK:     %cst_175 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %644 = stablehlo.multiply %348, %cst_175 : tensor<1xf32>
// CHECK:     %645 = stablehlo.subtract %644, %348 : tensor<1xf32>
// CHECK:     %646 = stablehlo.subtract %644, %645 : tensor<1xf32>
// CHECK:     %647 = stablehlo.subtract %348, %646 : tensor<1xf32>
// CHECK:     %648 = stablehlo.multiply %642, %646 : tensor<1xf32>
// CHECK:     %649 = stablehlo.multiply %642, %647 : tensor<1xf32>
// CHECK:     %650 = stablehlo.multiply %643, %646 : tensor<1xf32>
// CHECK:     %651 = stablehlo.multiply %643, %647 : tensor<1xf32>
// CHECK:     %652 = stablehlo.subtract %648, %639 : tensor<1xf32>
// CHECK:     %653 = stablehlo.add %649, %650 : tensor<1xf32>
// CHECK:     %654 = stablehlo.add %652, %653 : tensor<1xf32>
// CHECK:     %655 = stablehlo.add %654, %651 : tensor<1xf32>
// CHECK:     %656 = stablehlo.multiply %636, %350 : tensor<1xf32>
// CHECK:     %657 = stablehlo.multiply %638, %348 : tensor<1xf32>
// CHECK:     %658 = stablehlo.add %656, %657 : tensor<1xf32>
// CHECK:     %659 = stablehlo.add %655, %658 : tensor<1xf32>
// CHECK:     %660 = stablehlo.add %639, %659 : tensor<1xf32>
// CHECK:     %661 = stablehlo.subtract %660, %639 : tensor<1xf32>
// CHECK:     %662 = stablehlo.subtract %659, %661 : tensor<1xf32>
// CHECK:     %cst_176 = stablehlo.constant dense<2.885390e+00> : tensor<1xf32>
// CHECK:     %cst_177 = stablehlo.constant dense<3.85192607E-8> : tensor<1xf32>
// CHECK:     %663 = stablehlo.add %660, %cst_176 : tensor<1xf32>
// CHECK:     %664 = stablehlo.subtract %663, %cst_176 : tensor<1xf32>
// CHECK:     %665 = stablehlo.subtract %663, %664 : tensor<1xf32>
// CHECK:     %666 = stablehlo.subtract %660, %664 : tensor<1xf32>
// CHECK:     %667 = stablehlo.subtract %cst_176, %665 : tensor<1xf32>
// CHECK:     %668 = stablehlo.add %666, %667 : tensor<1xf32>
// CHECK:     %669 = stablehlo.add %662, %cst_177 : tensor<1xf32>
// CHECK:     %670 = stablehlo.subtract %669, %cst_177 : tensor<1xf32>
// CHECK:     %671 = stablehlo.subtract %669, %670 : tensor<1xf32>
// CHECK:     %672 = stablehlo.subtract %662, %670 : tensor<1xf32>
// CHECK:     %673 = stablehlo.subtract %cst_177, %671 : tensor<1xf32>
// CHECK:     %674 = stablehlo.add %672, %673 : tensor<1xf32>
// CHECK:     %675 = stablehlo.add %663, %669 : tensor<1xf32>
// CHECK:     %676 = stablehlo.subtract %675, %663 : tensor<1xf32>
// CHECK:     %677 = stablehlo.subtract %669, %676 : tensor<1xf32>
// CHECK:     %678 = stablehlo.add %668, %674 : tensor<1xf32>
// CHECK:     %679 = stablehlo.add %678, %677 : tensor<1xf32>
// CHECK:     %680 = stablehlo.add %675, %679 : tensor<1xf32>
// CHECK:     %681 = stablehlo.subtract %680, %675 : tensor<1xf32>
// CHECK:     %682 = stablehlo.subtract %679, %681 : tensor<1xf32>
// CHECK:     %683 = stablehlo.multiply %231, %680 : tensor<1xf32>
// CHECK:     %cst_178 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %684 = stablehlo.multiply %231, %cst_178 : tensor<1xf32>
// CHECK:     %685 = stablehlo.subtract %684, %231 : tensor<1xf32>
// CHECK:     %686 = stablehlo.subtract %684, %685 : tensor<1xf32>
// CHECK:     %687 = stablehlo.subtract %231, %686 : tensor<1xf32>
// CHECK:     %cst_179 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %688 = stablehlo.multiply %680, %cst_179 : tensor<1xf32>
// CHECK:     %689 = stablehlo.subtract %688, %680 : tensor<1xf32>
// CHECK:     %690 = stablehlo.subtract %688, %689 : tensor<1xf32>
// CHECK:     %691 = stablehlo.subtract %680, %690 : tensor<1xf32>
// CHECK:     %692 = stablehlo.multiply %686, %690 : tensor<1xf32>
// CHECK:     %693 = stablehlo.multiply %686, %691 : tensor<1xf32>
// CHECK:     %694 = stablehlo.multiply %687, %690 : tensor<1xf32>
// CHECK:     %695 = stablehlo.multiply %687, %691 : tensor<1xf32>
// CHECK:     %696 = stablehlo.subtract %692, %683 : tensor<1xf32>
// CHECK:     %697 = stablehlo.add %693, %694 : tensor<1xf32>
// CHECK:     %698 = stablehlo.add %696, %697 : tensor<1xf32>
// CHECK:     %699 = stablehlo.add %698, %695 : tensor<1xf32>
// CHECK:     %700 = stablehlo.multiply %231, %682 : tensor<1xf32>
// CHECK:     %701 = stablehlo.multiply %233, %680 : tensor<1xf32>
// CHECK:     %702 = stablehlo.add %700, %701 : tensor<1xf32>
// CHECK:     %703 = stablehlo.add %699, %702 : tensor<1xf32>
// CHECK:     %704 = stablehlo.add %683, %703 : tensor<1xf32>
// CHECK:     %705 = stablehlo.subtract %704, %683 : tensor<1xf32>
// CHECK:     %706 = stablehlo.subtract %703, %705 : tensor<1xf32>
// CHECK:     %707 = stablehlo.multiply %324, %504 : tensor<1xf32>
// CHECK:     %cst_180 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %708 = stablehlo.multiply %324, %cst_180 : tensor<1xf32>
// CHECK:     %709 = stablehlo.subtract %708, %324 : tensor<1xf32>
// CHECK:     %710 = stablehlo.subtract %708, %709 : tensor<1xf32>
// CHECK:     %711 = stablehlo.subtract %324, %710 : tensor<1xf32>
// CHECK:     %cst_181 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %712 = stablehlo.multiply %504, %cst_181 : tensor<1xf32>
// CHECK:     %713 = stablehlo.subtract %712, %504 : tensor<1xf32>
// CHECK:     %714 = stablehlo.subtract %712, %713 : tensor<1xf32>
// CHECK:     %715 = stablehlo.subtract %504, %714 : tensor<1xf32>
// CHECK:     %716 = stablehlo.multiply %710, %714 : tensor<1xf32>
// CHECK:     %717 = stablehlo.multiply %710, %715 : tensor<1xf32>
// CHECK:     %718 = stablehlo.multiply %711, %714 : tensor<1xf32>
// CHECK:     %719 = stablehlo.multiply %711, %715 : tensor<1xf32>
// CHECK:     %720 = stablehlo.subtract %716, %707 : tensor<1xf32>
// CHECK:     %721 = stablehlo.add %717, %718 : tensor<1xf32>
// CHECK:     %722 = stablehlo.add %720, %721 : tensor<1xf32>
// CHECK:     %723 = stablehlo.add %722, %719 : tensor<1xf32>
// CHECK:     %724 = stablehlo.multiply %324, %506 : tensor<1xf32>
// CHECK:     %725 = stablehlo.multiply %326, %504 : tensor<1xf32>
// CHECK:     %726 = stablehlo.add %724, %725 : tensor<1xf32>
// CHECK:     %727 = stablehlo.add %723, %726 : tensor<1xf32>
// CHECK:     %728 = stablehlo.add %707, %727 : tensor<1xf32>
// CHECK:     %729 = stablehlo.subtract %728, %707 : tensor<1xf32>
// CHECK:     %730 = stablehlo.subtract %727, %729 : tensor<1xf32>
// CHECK:     %731 = stablehlo.convert %12 : (tensor<1xi32>) -> tensor<1xf32>
// CHECK:     %cst_182 = stablehlo.constant dense<0.000000e+00> : tensor<1xf32>
// CHECK:     %732 = stablehlo.add %731, %101 : tensor<1xf32>
// CHECK:     %733 = stablehlo.subtract %732, %101 : tensor<1xf32>
// CHECK:     %734 = stablehlo.subtract %732, %733 : tensor<1xf32>
// CHECK:     %735 = stablehlo.subtract %731, %733 : tensor<1xf32>
// CHECK:     %736 = stablehlo.subtract %101, %734 : tensor<1xf32>
// CHECK:     %737 = stablehlo.add %735, %736 : tensor<1xf32>
// CHECK:     %738 = stablehlo.add %cst_182, %142 : tensor<1xf32>
// CHECK:     %739 = stablehlo.subtract %738, %142 : tensor<1xf32>
// CHECK:     %740 = stablehlo.subtract %738, %739 : tensor<1xf32>
// CHECK:     %741 = stablehlo.subtract %cst_182, %739 : tensor<1xf32>
// CHECK:     %742 = stablehlo.subtract %142, %740 : tensor<1xf32>
// CHECK:     %743 = stablehlo.add %741, %742 : tensor<1xf32>
// CHECK:     %744 = stablehlo.add %732, %738 : tensor<1xf32>
// CHECK:     %745 = stablehlo.subtract %744, %732 : tensor<1xf32>
// CHECK:     %746 = stablehlo.subtract %738, %745 : tensor<1xf32>
// CHECK:     %747 = stablehlo.add %737, %743 : tensor<1xf32>
// CHECK:     %748 = stablehlo.add %747, %746 : tensor<1xf32>
// CHECK:     %749 = stablehlo.add %744, %748 : tensor<1xf32>
// CHECK:     %750 = stablehlo.subtract %749, %744 : tensor<1xf32>
// CHECK:     %751 = stablehlo.subtract %748, %750 : tensor<1xf32>
// CHECK:     %752 = stablehlo.add %749, %728 : tensor<1xf32>
// CHECK:     %753 = stablehlo.subtract %752, %728 : tensor<1xf32>
// CHECK:     %754 = stablehlo.subtract %752, %753 : tensor<1xf32>
// CHECK:     %755 = stablehlo.subtract %749, %753 : tensor<1xf32>
// CHECK:     %756 = stablehlo.subtract %728, %754 : tensor<1xf32>
// CHECK:     %757 = stablehlo.add %755, %756 : tensor<1xf32>
// CHECK:     %758 = stablehlo.add %751, %730 : tensor<1xf32>
// CHECK:     %759 = stablehlo.subtract %758, %730 : tensor<1xf32>
// CHECK:     %760 = stablehlo.subtract %758, %759 : tensor<1xf32>
// CHECK:     %761 = stablehlo.subtract %751, %759 : tensor<1xf32>
// CHECK:     %762 = stablehlo.subtract %730, %760 : tensor<1xf32>
// CHECK:     %763 = stablehlo.add %761, %762 : tensor<1xf32>
// CHECK:     %764 = stablehlo.add %752, %758 : tensor<1xf32>
// CHECK:     %765 = stablehlo.subtract %764, %752 : tensor<1xf32>
// CHECK:     %766 = stablehlo.subtract %758, %765 : tensor<1xf32>
// CHECK:     %767 = stablehlo.add %757, %763 : tensor<1xf32>
// CHECK:     %768 = stablehlo.add %767, %766 : tensor<1xf32>
// CHECK:     %769 = stablehlo.add %764, %768 : tensor<1xf32>
// CHECK:     %770 = stablehlo.subtract %769, %764 : tensor<1xf32>
// CHECK:     %771 = stablehlo.subtract %768, %770 : tensor<1xf32>
// CHECK:     %cst_183 = stablehlo.constant dense<9.375000e-01> : tensor<1xf32>
// CHECK:     %cst_184 = stablehlo.constant dense<1.062500e+00> : tensor<1xf32>
// CHECK:     %772 = stablehlo.compare LT, %cst_183, %7 : (tensor<1xf32>, tensor<1xf32>) -> tensor<1xi1>
// CHECK:     %773 = stablehlo.compare LT, %7, %cst_184 : (tensor<1xf32>, tensor<1xf32>) -> tensor<1xi1>
// CHECK:     %774 = stablehlo.and %772, %773 : tensor<1xi1>
// CHECK:     %775 = stablehlo.select %774, %704, %769 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %776 = stablehlo.select %774, %706, %771 : tensor<1xi1>, tensor<1xf32>
// CHECK:     %cst_185 = stablehlo.constant dense<0.693147182> : tensor<1xf32>
// CHECK:     %cst_186 = stablehlo.constant dense<-1.90465421E-9> : tensor<1xf32>
// CHECK:     %777 = stablehlo.multiply %775, %cst_185 : tensor<1xf32>
// CHECK:     %cst_187 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %778 = stablehlo.multiply %775, %cst_187 : tensor<1xf32>
// CHECK:     %779 = stablehlo.subtract %778, %775 : tensor<1xf32>
// CHECK:     %780 = stablehlo.subtract %778, %779 : tensor<1xf32>
// CHECK:     %781 = stablehlo.subtract %775, %780 : tensor<1xf32>
// CHECK:     %cst_188 = stablehlo.constant dense<4.097000e+03> : tensor<1xf32>
// CHECK:     %782 = stablehlo.multiply %cst_185, %cst_188 : tensor<1xf32>
// CHECK:     %783 = stablehlo.subtract %782, %cst_185 : tensor<1xf32>
// CHECK:     %784 = stablehlo.subtract %782, %783 : tensor<1xf32>
// CHECK:     %785 = stablehlo.subtract %cst_185, %784 : tensor<1xf32>
// CHECK:     %786 = stablehlo.multiply %780, %784 : tensor<1xf32>
// CHECK:     %787 = stablehlo.multiply %780, %785 : tensor<1xf32>
// CHECK:     %788 = stablehlo.multiply %781, %784 : tensor<1xf32>
// CHECK:     %789 = stablehlo.multiply %781, %785 : tensor<1xf32>
// CHECK:     %790 = stablehlo.subtract %786, %777 : tensor<1xf32>
// CHECK:     %791 = stablehlo.add %787, %788 : tensor<1xf32>
// CHECK:     %792 = stablehlo.add %790, %791 : tensor<1xf32>
// CHECK:     %793 = stablehlo.add %792, %789 : tensor<1xf32>
// CHECK:     %794 = stablehlo.multiply %775, %cst_186 : tensor<1xf32>
// CHECK:     %795 = stablehlo.multiply %776, %cst_185 : tensor<1xf32>
// CHECK:     %796 = stablehlo.add %794, %795 : tensor<1xf32>
// CHECK:     %797 = stablehlo.add %793, %796 : tensor<1xf32>
// CHECK:     %798 = stablehlo.add %777, %797 : tensor<1xf32>
// CHECK:     %799 = stablehlo.subtract %798, %777 : tensor<1xf32>
// CHECK:     %800 = stablehlo.subtract %797, %799 : tensor<1xf32>
// CHECK:     %cst_189 = stablehlo.constant dense<0.000000e+00> : tensor<1xf32>
// CHECK:     %cst_190 = stablehlo.constant dense<1.000000e+00> : tensor<1xf32>
// CHECK:     %cst_191 = stablehlo.constant dense<0x7FC00000> : tensor<1xf32>
// CHECK:     %cst_192 = stablehlo.constant dense<0x7F800000> : tensor<1xf32>
// CHECK:     %cst_193 = stablehlo.constant dense<0xFF800000> : tensor<1xf32>
// CHECK:     %801 = stablehlo.compare EQ, %7, %cst_189 : (tensor<1xf32>, tensor<1xf32>) -> tensor<1xi1>
// CHECK:     %802 = stablehlo.compare EQ, %7, %cst_190 : (tensor<1xf32>, tensor<1xf32>) -> tensor<1xi1>
// CHECK:     %803 = stablehlo.compare EQ, %8, %cst_189 : (tensor<1xf32>, tensor<1xf32>) -> tensor<1xi1>
// CHECK:     %804 = stablehlo.and %802, %803 : tensor<1xi1>
// CHECK:     %805 = stablehlo.compare LT, %7, %cst_189 : (tensor<1xf32>, tensor<1xf32>) -> tensor<1xi1>
// CHECK:     %806 = stablehlo.compare EQ, %7, %cst_192 : (tensor<1xf32>, tensor<1xf32>) -> tensor<1xi1>
// CHECK:     %807 = stablehlo.concatenate %798, %800, dim = 0 : (tensor<1xf32>, tensor<1xf32>) -> tensor<2xf32>
// CHECK:     %808 = stablehlo.concatenate %cst_189, %cst_189, dim = 0 : (tensor<1xf32>, tensor<1xf32>) -> tensor<2xf32>
// CHECK:     %809 = stablehlo.concatenate %cst_192, %cst_189, dim = 0 : (tensor<1xf32>, tensor<1xf32>) -> tensor<2xf32>
// CHECK:     %810 = stablehlo.concatenate %cst_193, %cst_189, dim = 0 : (tensor<1xf32>, tensor<1xf32>) -> tensor<2xf32>
// CHECK:     %811 = stablehlo.concatenate %cst_191, %cst_191, dim = 0 : (tensor<1xf32>, tensor<1xf32>) -> tensor<2xf32>
// CHECK:     %812 = stablehlo.broadcast_in_dim %804, dims = {{\[}}0{{\]}} : (tensor<1xi1>) -> tensor<2xi1>
// CHECK:     %813 = stablehlo.broadcast_in_dim %806, dims = {{\[}}0{{\]}} : (tensor<1xi1>) -> tensor<2xi1>
// CHECK:     %814 = stablehlo.broadcast_in_dim %801, dims = {{\[}}0{{\]}} : (tensor<1xi1>) -> tensor<2xi1>
// CHECK:     %815 = stablehlo.broadcast_in_dim %805, dims = {{\[}}0{{\]}} : (tensor<1xi1>) -> tensor<2xi1>
// CHECK:     %816 = stablehlo.select %812, %808, %807 : tensor<2xi1>, tensor<2xf32>
// CHECK:     %817 = stablehlo.select %813, %809, %816 : tensor<2xi1>, tensor<2xf32>
// CHECK:     %818 = stablehlo.select %814, %810, %817 : tensor<2xi1>, tensor<2xf32>
// CHECK:     %819 = stablehlo.select %815, %811, %818 : tensor<2xi1>, tensor<2xf32>
// CHECK:     %820 = stablehlo.convert %819 : (tensor<2xf32>) -> tensor<2xf64>
// CHECK:     %cst_194 = stablehlo.constant dense<0.000000e+00> : tensor<f64>
// CHECK:     %821 = stablehlo.reduce(%820 init: %cst_194) applies stablehlo.add across dimensions = {{\[}}0{{\]}} : (tensor<2xf64>, tensor<f64>) -> tensor<f64>
// CHECK:     return %821 : tensor<f64>
// CHECK:   func.func @main() attributes {enzyme.no_multifloat} {
// CHECK:     %cst = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:     %cst_0 = stablehlo.constant dense<0.000000e+00> : tensor<f64>
// CHECK:     %0 = call @log_test(%cst) : (tensor<f64>) -> tensor<f64>
// CHECK:     check.expect_close %0, %cst_0, max_ulp_difference = 0 : tensor<f64>, tensor<f64>
// CHECK:     %cst_1 = stablehlo.constant dense<0.000000e+00> : tensor<f64>
// CHECK:     %cst_2 = stablehlo.constant dense<0xFFF0000000000000> : tensor<f64>
// CHECK:     %1 = call @log_test(%cst_1) : (tensor<f64>) -> tensor<f64>
// CHECK:     check.expect_close %1, %cst_2, max_ulp_difference = 0 : tensor<f64>, tensor<f64>
// CHECK:     %cst_3 = stablehlo.constant dense<-1.000000e+00> : tensor<f64>
// CHECK:     %2 = call @log_test(%cst_3) : (tensor<f64>) -> tensor<f64>
// CHECK:     %cst_4 = stablehlo.constant dense<0x7FF0000000000000> : tensor<f64>
// CHECK:     %3 = call @log_test(%cst_4) : (tensor<f64>) -> tensor<f64>
// CHECK:     check.expect_close %3, %cst_4, max_ulp_difference = 0 : tensor<f64>, tensor<f64>
// CHECK:     %cst_5 = stablehlo.constant dense<2.000000e+00> : tensor<f64>
// CHECK:     %cst_6 = stablehlo.constant dense<0.6931471805599454> : tensor<f64>
// CHECK:     %4 = call @log_test(%cst_5) : (tensor<f64>) -> tensor<f64>
// CHECK:     check.expect_close %4, %cst_6, max_ulp_difference = 1 : tensor<f64>, tensor<f64>
// CHECK:     %cst_7 = stablehlo.constant dense<0.69314718055994529> : tensor<f64>
// CHECK:     check.expect_close %4, %cst_7, max_ulp_difference = 100 : tensor<f64>, tensor<f64>
// CHECK:     return
// CHECK: }
