// RUN: enzymexlamlir-opt %s --optimize-communication="wrap_to_rotate=1" | FileCheck %s

module {
  func.func @test_wrap_to_rotate_symmetric(%arg0: tensor<10xf32>) -> tensor<14xf32> {
    %wrap = "enzymexla.wrap"(%arg0) <{dimension = 0 : i64, lhs = 2 : i64, rhs = 2 : i64}> : (tensor<10xf32>) -> tensor<14xf32>
    return %wrap : tensor<14xf32>
  }

  func.func @test_wrap_to_rotate_asymmetric(%arg0: tensor<10xf32>) -> tensor<15xf32> {
    %wrap = "enzymexla.wrap"(%arg0) <{dimension = 0 : i64, lhs = 3 : i64, rhs = 2 : i64}> : (tensor<10xf32>) -> tensor<15xf32>
    return %wrap : tensor<15xf32>
  }
}

// CHECK:  func.func @test_wrap_to_rotate_symmetric(%[[ARG0:.+]]: tensor<10xf32>) -> tensor<14xf32> {
// CHECK-NEXT:    %[[ZERO:.+]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK-NEXT:    %[[PAD:.+]] = stablehlo.pad %[[ARG0]], %[[ZERO]], low = [2], high = [2], interior = [0] : (tensor<10xf32>, tensor<f32>) -> tensor<14xf32>
// CHECK-NEXT:    %[[ROTATE1:.+]] = "enzymexla.rotate"(%[[PAD]]) <{amount = 2 : si32, dimension = 0 : si32}> : (tensor<14xf32>) -> tensor<14xf32>
// CHECK-NEXT:    %[[ROTATE2:.+]] = "enzymexla.rotate"(%[[PAD]]) <{amount = -2 : si32, dimension = 0 : si32}> : (tensor<14xf32>) -> tensor<14xf32>
// CHECK-NEXT:    %[[IOTA:.+]] = stablehlo.iota dim = 0 : tensor<14xi32>
// CHECK-NEXT:    %[[MID_THRESHOLD:.+]] = stablehlo.constant dense<12> : tensor<14xi32>
// CHECK-NEXT:    %[[MID_CMP:.+]] = stablehlo.compare LT, %[[IOTA]], %[[MID_THRESHOLD]] : (tensor<14xi32>, tensor<14xi32>) -> tensor<14xi1>
// CHECK-NEXT:    %[[MID_SEL:.+]] = stablehlo.select %[[MID_CMP]], %[[PAD]], %[[ROTATE2]] : tensor<14xi1>, tensor<14xf32>
// CHECK-NEXT:    %[[LHS_THRESHOLD:.+]] = stablehlo.constant dense<2> : tensor<14xi32>
// CHECK-NEXT:    %[[LHS_CMP:.+]] = stablehlo.compare LT, %[[IOTA]], %[[LHS_THRESHOLD]] : (tensor<14xi32>, tensor<14xi32>) -> tensor<14xi1>
// CHECK-NEXT:    %[[RESULT:.+]] = stablehlo.select %[[LHS_CMP]], %[[ROTATE1]], %[[MID_SEL]] : tensor<14xi1>, tensor<14xf32>
// CHECK-NEXT:    return %[[RESULT]] : tensor<14xf32>
// CHECK-NEXT:  }

// CHECK:  func.func @test_wrap_to_rotate_asymmetric(%[[ARG1:.+]]: tensor<10xf32>) -> tensor<15xf32> {
// CHECK-NEXT:    %[[ZERO2:.+]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK-NEXT:    %[[PAD2:.+]] = stablehlo.pad %[[ARG1]], %[[ZERO2]], low = [3], high = [2], interior = [0] : (tensor<10xf32>, tensor<f32>) -> tensor<15xf32>
// CHECK-NEXT:    %[[ROTATE1_2:.+]] = "enzymexla.rotate"(%[[PAD2]]) <{amount = 3 : si32, dimension = 0 : si32}> : (tensor<15xf32>) -> tensor<15xf32>
// CHECK-NEXT:    %[[ROTATE2_2:.+]] = "enzymexla.rotate"(%[[PAD2]]) <{amount = -2 : si32, dimension = 0 : si32}> : (tensor<15xf32>) -> tensor<15xf32>
// CHECK-NEXT:    %[[IOTA2:.+]] = stablehlo.iota dim = 0 : tensor<15xi32>
// CHECK-NEXT:    %[[MID_THRESHOLD2:.+]] = stablehlo.constant dense<13> : tensor<15xi32>
// CHECK-NEXT:    %[[MID_CMP2:.+]] = stablehlo.compare LT, %[[IOTA2]], %[[MID_THRESHOLD2]] : (tensor<15xi32>, tensor<15xi32>) -> tensor<15xi1>
// CHECK-NEXT:    %[[MID_SEL2:.+]] = stablehlo.select %[[MID_CMP2]], %[[PAD2]], %[[ROTATE2_2]] : tensor<15xi1>, tensor<15xf32>
// CHECK-NEXT:    %[[LHS_THRESHOLD2:.+]] = stablehlo.constant dense<3> : tensor<15xi32>
// CHECK-NEXT:    %[[LHS_CMP2:.+]] = stablehlo.compare LT, %[[IOTA2]], %[[LHS_THRESHOLD2]] : (tensor<15xi32>, tensor<15xi32>) -> tensor<15xi1>
// CHECK-NEXT:    %[[RESULT2:.+]] = stablehlo.select %[[LHS_CMP2]], %[[ROTATE1_2]], %[[MID_SEL2]] : tensor<15xi1>, tensor<15xf32>
// CHECK-NEXT:    return %[[RESULT2]] : tensor<15xf32>
// CHECK-NEXT:  }
