name: Test BinaryBuilderBase

on:
  pull_request:
    branches:
    - main

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test-bbb:
    name: BinaryBuilderBase - ${{ matrix.os }} - Julia ${{ matrix.julia_version }}
    runs-on: ${{ matrix.os }}

    container:
      image: ${{ (contains(matrix.os, 'linux') && 'ghcr.io/enzymead/reactant-docker-images@sha256:91e1edb7a7c869d5a70db06e417f22907be0e67ca86641d48adcea221fedc674' ) || '' }}
      options: --privileged

    strategy:
      fail-fast: false
      matrix:
        os:
          - jll
          # - linux-x86-n2-32
        julia_version:
          - '1.11'

    env:
      # FORCE_SANDBOX_MODE: unprivileged
      BINARYBUILDER_RUNNER: privileged
      BINARYBUILDER_AUTOMATIC_APPLE: true

    steps:
      - uses: actions/checkout@v4
        with:
          repository: JuliaPackaging/BinaryBuilderBase.jl
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia_version }}
      - name: Load Julia packages from cache
        id: julia-cache
        uses: julia-actions/cache@v2
      - name: Install BinaryBuilderBase
        timeout-minutes: 20
        shell: julia --project=@. --color=yes {0}
        run: |
          using Pkg
          Pkg.instantiate()
      - name: System info
        run: |
          julia --check-bounds=yes --color=yes --depwarn=yes --inline=yes --project=@. -e "using BinaryBuilderBase; BinaryBuilderBase.versioninfo()"
      - name: Test BinaryBuilderBase
        timeout-minutes: 60
        run: |
          eval `ssh-agent`
          chmod 0600 test/id_ecdsa_deploy_helloworld_c_jll_read_only
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add test/id_ecdsa_deploy_helloworld_c_jll_read_only
          julia --check-bounds=yes --color=yes --depwarn=yes --inline=yes --project=@. -e 'using Pkg; Pkg.instantiate(); Pkg.test(coverage=true)'
      - name: Save Julia depot cache on cancel or failure
        id: julia-cache-save
        if: cancelled() || failure()
        uses: actions/cache/save@v4
        with: 
          path: |
            ${{ steps.julia-cache.outputs.cache-paths }}
          key: ${{ steps.julia-cache.outputs.cache-key }}
