name: Clang-Format

on:
  push:
  pull_request:
  merge_group:

jobs:
  build:
    name: Format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.18.2
      with:
        source: 'src'
        style: 'llvm'
        clangFormatVersion: 16
